In [1]:
%reload_ext autoreload
%autoreload 2


#This is needed to add the repo dir to the path so jupyter
# can load the republic modules directly from the notebooks
import os
import sys
import re
sys.path.append('/Users/rikhoekstra/develop/republic_clean/')

# from collections import defaultdict
import pandas as pd
from collections import Counter, defaultdict
import json
# import republic.model.republic_document_model as rdm

repo_dir = os.path.split(os.getcwd())[0]

if repo_dir not in sys.path:
    sys.path.append(repo_dir)
    
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

In [3]:
me_regent = pd.read_csv('./mdbdump/me_Regent.csv',sep='\t')

In [ ]:
with pd.options(me_regent.head()

,Unnamed: 0,IDRegent,Geslachtsnaam,Tussenvoegsel,IDAdellijkeTitel,IDAcademischeTitel,Voornaam,Adel,Adelspredikaat,Heerlijkheid,Heerlijkheid2,Geboortejaar,OnbepaaldGeboortedatum,Overlijdensjaar,OnbepaaldOverlijdensdatum,Opmerkingen,Periode
0,0,1,Beukelaar,NaN,8.0,3.0,Thomas,1,NaN,Alblasserdam,"Ottoland, 's-Heeraartsberg",NaN,0,1516.0,0,Tresorier van Dordrecht 1482-1483.,0
1,1,3,Ernesink,NaN,1.0,1.0,Frank,0,NaN,NaN,NaN,NaN,0,NaN,0,NaN,0
2,2,7,Esch,van,1.0,3.0,Klaas,0,NaN,NaN,NaN,NaN,0,1543.0,0,Persoonsgegevens: zoon van Jan van Essche.,0
3,3,18,Snouckaert,NaN,11.0,1.0,Jacob,1,NaN,Binckhorst,NaN,1527,0,1575.0,0,Overig: secretaris van Maximiliaan van Bourgon...,0
4,4,19,Schouten,NaN,1.0,3.0,Willem Jansz.,0,NaN,NaN,NaN,1528,0,1604.0,0,NaN,0

In [42]:
[f for f in os.listdir(f'./mdbdump/') if f.startswith('me_')]

['me_TempTable.csv',
 'me_College.csv',
 'me_provinciaal.csv',
 'me_lokaal.csv',
 'me_Bron.csv',
 'me_BronFunctieDetails.csv',
 'me_Regent.csv',
 'me_BovenLokaalCollegeRegentDetails.csv',
 'me_AdellijkeTitel.csv',
 'me_FunctieLokaal.csv',
 'me_AcademischeTitel.csv',
 'me_FunctieBovenLokaal.csv',
 'me_Gewest.csv',
 'me_BronRegentDetails.csv',
 'me_stand.csv',
 'me_Functie.csv',
 'me_Bron_org.csv',
 'me_aliassen.csv',
 'me_BovenLokaalCollegeRegentDetails1.csv',
 'me_Data.csv',
 'me_regionaal.csv']

In [47]:
me_aanst = pd.read_csv('./mdbdump/me_BovenLokaalCollegeRegentDetails.csv',sep='\t')

In [35]:
len(me_regent[me_regent['Opmerkingen'].str.contains('nog:', regex=True, flags=re.I, na=False )])

11

In [58]:
with pd.option_context('max_colwidth', 1000):
    display(me_regent['Opmerkingen'].str.replace('.*(nog.*)','', regex=True, flags=re.I))#, na=False )]) #r'(?P<nog>nog:)', flags=re.I) # ,expand=True))

0                                                                                                    Tresorier van Dordrecht 1482-1483.
1                                                                                                                                   NaN
2                                                                                            Persoonsgegevens: zoon van Jan van Essche.
3                                                                                    Overig: secretaris van Maximiliaan van Bourgondie.
4                                                                                                                                   NaN
                                                                     ...
5288                                                                                               Afwisselend  van Dalem en van Dalen.
5289                                                                                Persoonsgegevens: bastaardzoon van graaf Willem VI.
5290                                                                                                                                NaN
5291    In 1532 wordt hij ambachtsheer en opperschout van Zoeterwoude genoemd.\r\nBij Erfgoed Leiden dubbel klikken op inventarisnr(s).
5292                                                                                                                                NaN
Name: Opmerkingen, Length: 5293, dtype: object

In [60]:
me_regent['Opmerkingen'] = me_regent['Opmerkingen'].str.replace('.*(nog.*)','', regex=True, flags=re.I)

In [64]:
with pd.option_context('max_colwidth', 1000):
    display(me_regent[me_regent['Opmerkingen'].notna()].sample(30))

      Unnamed: 0  IDRegent Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel           Voornaam  Adel Adelspredikaat     Heerlijkheid                                                                  Heerlijkheid2 Geboortejaar  OnbepaaldGeboortedatum  Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                 Opmerkingen  Periode
3940        3940      2138     Naaldwijk           van               6.0                 1.0            Hendrik     1            NaN        Naaldwijk                                                        Groensvoord, Sliedrecht         1367                       0           1427.0                          1                                          Adelstitel: ridder 1399. Erfmaarschalk van Holland\r\nInventaris Heilige Geest van G. 't Hart kent geen nummering.        0
3031        3031      1969   Duvenvoorde           van               6.0                 1.0             Filips     1            NaN          Polanen                                                                            NaN          NaN                       0           1307.0                          0                                                                                                                        Adelstitel: knaap 1292, ridder 1305.        0
3694        3694      5226       Fransz.           NaN               1.0                 1.0           IJsbrand     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                           neemt functie over van zijn vader Frans Pietersz.        0
178          178       378      Ratingen           van               1.0                 1.0              Joost     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                  Streekarchief Voorne-Putten, 033, inleiding kent geen paginering/nummering        0
4242        4242      4964          Raat           NaN               1.0                 1.0   Albrecht Klaasz.     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                       Meilink nr. 2253 voorheen bekend onder inv. nr. 2323.        0
484          484      1460     Gerritsz.           NaN               1.0                 1.0               Dirk     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                   Bij Erfgoed Leiden dubbel klikken op inventarisnummer(s).        0
3855        3855      3924      Arendsz.           NaN               1.0                 1.0             Willem     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                   3 naamgenoten (van Huffer) verwijzen mogelijk naar 1 en dezelfde persoon?        0
5229        5229      1250    Boschuysen           van               1.0                 1.0              Klaas     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                       Bij Erfgoed Leiden dubbel klikken op inventarisnr(s).        0
2223        2223      5126    Drappenier           NaN               1.0                 1.0     Willem Dirksz.     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                           Drappenier stond in tekst tussen haakjes vermeld.        0
5214        5214       835      Jacobsz.           NaN               1.0                 1.0           Albrecht     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                       Bij Erfgoed Leiden dubbel klikken op inventarisnr(s).        0
4453        4453      5578         Bloed            de               1.0                 1.0       Oudzier Huge     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                           Bij Erfgoed Leiden dubbel klikken op inventarisnr(s), staat hier als Oudzier die Bloot genoteerd.        0
284          284       639     Montfoort           van               7.0                 5.0                Jan     1            NaN      Diemerbroek  Harmelen, Zuid-Polsbroek, Linschoten, Hekendorp, Snelrewaard, Purmerend, Neck          NaN                       0           1448.0                          0                       Broer van Lodewijk en Willem van Montfoort.\r\nBurggraaf van Montfoort 1413, ridder 1418.\r\nLid en proost van Domkapittel 1404-1414.        0
3899        3899      3822       Klaasz.           NaN               1.0                 1.0   Hildebrand Klaas     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                                            Dezelfde als Hildebrand Klaasz.?        0
297          297       670      Thamesz.           NaN               1.0                 1.0              Klaas     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                   Bij Erfgoed Leiden dubbel klikken op inventarisnummer(s).        0
3111        3111      2356     Poelgeest           van               6.0                 1.0     Adriaan Jansz.     1            NaN  Klein Poelgeest                                                                            NaN          NaN                       0           1507.0                          0                                                                    Adelstitel: schildknaap 1487, ridder 1499 of 1502.\r\nOverig: hoogheemraad van Rijnland.        0
3910        3910      1326       Hugenz.           NaN               1.0                 1.0                Jan     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                       Bij Erfgoed Leiden dubbel klikken op inventarisnr(s).        0
5224        5224      5363     Roelofsz.           NaN               1.0                 1.0              Jacob     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                       Bij Erfgoed Leiden dubbel klikken op inventarisnr(s).        0
4513        4513       541      Uutkerke           van               6.0                 1.0            Roeland     1            NaN         Heestert        Hemsrode, Heist, Nieuwenburg, Oterleek, Ursem, St. Pancras, Riederwaard          NaN                       0           1442.0                          0                                                                                                    Adelstitel: ridder in de orde van het Gulden Vlies 1430.        0
1429        1429      3685         Vliet       van den               1.0                 1.0  Hendrik Rutgersz.     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                                                       Hollands of Brabants?        0
697          697      2086     Kralingen           NaN               6.0                 1.0              Ogier     1            NaN        Kralingen                                                             Schie, Ijsselmonde          NaN                       0           1395.0                          0                                                                                              Adelstitel: knaap 1350, ridder 1385.\r\nOverig: amnestie 1355.        0
3506        3506      1570     Bouloigne            de               1.0                 1.0              Rober     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                                                                                    0
4065        4065      4533       Schoten           van               1.0                 1.0                Jan     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                  hij is gevestigd op houtvesterij van de Haarlemmerhout, is hij houtvester?        0
3084        3084      2117       Merwede        van de               6.0                 1.0          Daniel IV     1            NaN              NaN                                                                            NaN          NaN                       0           1331.0                          0                                                                                    Adelstitel: ridder 1305.\r\nSmit geeft als overlijdensjaar omtrent 1341.        0
2809        2809       139       Persijn           van               1.0                 1.0       Klaas Jansz.     0            NaN              NaN                                                                            NaN          NaN                       0           1567.0                          1                                                                                                       Persoonsgegevens: zoon van Jan Hendriksz. van Persijn        0
4134        4134      5085       Doublet           NaN               1.0                 1.0                Jan     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                                                   1574: wijlen Jan Doublet.        0
4920        4920      1622       Kapelle       van der               1.0                 3.0             Pieter     0            NaN              NaN                                                                            NaN          NaN                       0           1525.0                          0                                                                Tevens kapelaan van Oost-Souburg (wordt benoemd door zijn naamgenoot, de abt van Middelburg)        0
1736        1736      4251     Pietersz.           NaN               1.0                 1.0           Cornelis     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                                                                                                Inventaris Heilige Geest van G. 't Hart kent geen nummering.        0
3429        3429      4012     Noordwijk           van               1.0                 1.0                Jan     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0                      Bij Huffer (Manboek) p. 844 wordt hij genoemd als baljuw, naast Gijsbrecht van Matenesse die als baljuw van Rijnsburg genoteerd staat.        0
523          523      1545       Brabant           van               1.0                 1.0                Jan     0            NaN              NaN                                                                            NaN          NaN                       0              NaN                          0  Overig: werd na werk in Hollandse dienst muntmeester van Brabant, Henegouwen en in de door Bourgondië geëxploiteerde munthuizen te Amiens en Saint-Quentin        0
780          780      2280    Zadelboger           NaN               1.0                 1.0           Protwitz     0            NaN              NaN                                                                            NaN          NaN                       0           1410.0                          1                                                                                                              In dienst van Albrecht van Beieren vanaf 1359.        0

me_regent[nog.notna()]

In [48]:
me_aanst[me_aanst['Opmerkingen'].str.contains('.*(nog:.*)', regex=True, flags=re.I, na=False )] #r'(?P<nog>nog:)', flags=re.I) # ,expand=True)

Empty DataFrame
Columns: [Unnamed: 0, ID, Periode, IDRegent, IDFunctie, IDCollege, Begindag, Beginmaand, Beginjaar, Einddag, Eindmaand, Eindjaar, Vertegenwoordigend, provinciaal, Opmerkingen, lokaal, regio, stand]
Index: []

## Disambiguate friezen en diverse perioden

In [67]:
[f for f in os.listdir(f'./mdbdump/') if re.search('div|frie',f)]

['divperioden_stand.csv',
 'republiek_friezen_AdellijkeTitel.csv',
 'republiek_friezen_provinciaal.csv',
 'republiek_friezen_stand.csv',
 'divperioden_provinciaal.csv',
 'republiek_friezen_AcademischeTitel.csv',
 'divperioden_Regent.csv',
 'divperioden_FunctieBovenLokaal.csv',
 'divperioden_AdellijkeTitel.csv',
 'republiek_friezen_FunctieLokaal.csv',
 'republiek_friezen_Bron.csv',
 'republiek_friezen_BronRegentDetails.csv',
 'divperioden_Bron.csv',
 'republiek_friezen_BronFunctieDetails.csv',
 'republiek_friezen_College.csv',
 'divperioden_lokaal.csv',
 'divperioden_College.csv',
 'republiek_friezen_aliassen.csv',
 'republiek_friezen_lokaal.csv',
 'divperioden_regionaal.csv',
 'republiek_friezen_FunctieBovenLokaal.csv',
 'divperioden_aliassen.csv',
 'republiek_friezen_Functie.csv',
 'republiek_friezen_regionaal.csv',
 'republiek_friezen_BovenLokaalCollegeRegentDetails.csv',
 'divperioden_AcademischeTitel.csv',
 'divperioden_Functie.csv',
 'divperioden_FunctieLokaal.csv',
 'divperioden_BronFunctieDetails.csv',
 'divperioden_BovenLokaalCollegeRegentDetails.csv',
 'divperioden_BronRegentDetails.csv',
 'republiek_friezen_Regent.csv',
 'republiek_friezen_Data.csv',
 'divperioden_Data.csv']

In [69]:
friezen = pd.read_csv('./mdbdump/republiek_friezen_Regent.csv', sep='\t')

In [70]:
divperiode = pd.read_csv('./mdbdump/divperioden_Regent.csv', sep='\t')

In [ ]:
divperiode.merge(friezen, left_on=['geslachtsnaam','overlijdensjaar'])

      Unnamed: 0  IDRegent Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel     Voornaam  Adel Adelspredikaat Heerlijkheid Heerlijkheid2  Geboortejaar  OnbepaaldGeboortedatum Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                Opmerkingen  Periode  overlijdensdag  overlijdensmaand                                   Opmerkingen2
0              0        16       Leisnig           van                 4                   1         Hugo     1            NaN          NaN           NaN        1465.0                       0            1538                          0                                                                                                                                                                                                        NaN        9            21.0               3.0                                            NaN
1              1        41        Botnia           NaN                 5                   1     Tialingh     1            NaN          NaN           NaN           NaN                       0            1533                          0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9             NaN               NaN                                            NaN
2              2        45        Mulert           NaN                 5                   4       Gerard     1            NaN          NaN           NaN           NaN                       0            1538                          0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9             7.0              12.0                                            NaN
3              3        57       Naarden           van                 1                   4      Maarten     0            NaN          NaN           NaN        1490.0                       1            1567                          0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9             NaN               1.0  identiek aan nr. 371 in database middeleeuwen
4              4        58       Nicolai           NaN                 5                   4      Everard     1            NaN          NaN           NaN        1497.0                       1            1561                          0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9            10.0               5.0                                            NaN
...          ...       ...           ...           ...               ...                 ...          ...   ...            ...          ...           ...           ...                     ...             ...                        ...                                                                                                                                                                                                        ...      ...             ...               ...                                            ...
1017        1017        27    Taubenheim           von                 1                   1     Christof     0            NaN          NaN           NaN           NaN                       0            1536                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1018        1018       839        Winter           NaN                 1                   3  Feijo Johan     0            NaN          NaN           NaN           NaN                       0             NaN                          0                                                                                                                                              Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9             NaN               NaN                                            NaN
1019        1019        24       Ziegler           NaN                 1                   1       Caspar     0            NaN          NaN           NaN           NaN                       0            1518                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1020        1020       336     Bouricius           van                 1                   4      Jacobus     0            NaN          NaN           NaN           NaN                       0            1672                          0                                                                                                                                                              Overig: was grietman van Engwirden 1657-1672.        9            29.0              12.0                                            NaN
1021        1021       338     Bouricius     Crack van                 1                   1     Johannes     0            NaN          NaN           NaN           NaN                       0            1700                          0                                                                                                                                                              Overig: was grietman van Engwirden 1677-1697.        9            27.0               3.0                                            NaN

[1022 rows x 20 columns]

In [72]:
aanst_friezen = pd.read_csv('./mdbdump/republiek_friezen_BovenLokaalCollegeRegentDetails.csv', sep='\t')

In [73]:
aanst = pd.read_pickle('./targetdb_dump_aanstelling.pkl')

In [74]:
aanst.columns

Index(['periode', 'begindag', 'beginmaand', 'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend', 'opmerkingen', 'van_als_bekend', 'tot_als_bekend', 'van', 'tot', 'instelling_id', 'functie_id', 'lokaal_id', 'provincie_id', 'regio_id', 'stand_id', 'persoon_id', 'me', 'republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw', 'divperioden'], dtype='object')

In [181]:
div_en_fr = pd.concat([friezen,divperiode])

In [184]:
div_en_fr.head()

   Unnamed: 0  IDRegent Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel  Voornaam  Adel Adelspredikaat Heerlijkheid Heerlijkheid2  Geboortejaar  OnbepaaldGeboortedatum Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                Opmerkingen  Periode  overlijdensdag  overlijdensmaand                                   Opmerkingen2
0           0        16       Leisnig           van                 4                   1      Hugo     1            NaN          NaN           NaN        1465.0                       0          1538.0                          0                                                                                                                                                                                                        NaN        9            21.0               3.0                                            NaN
1           1        41        Botnia           NaN                 5                   1  Tialingh     1            NaN          NaN           NaN           NaN                       0          1533.0                          0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9             NaN               NaN                                            NaN
2           2        45        Mulert           NaN                 5                   4    Gerard     1            NaN          NaN           NaN           NaN                       0          1538.0                          0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9             7.0              12.0                                            NaN
3           3        57       Naarden           van                 1                   4   Maarten     0            NaN          NaN           NaN        1490.0                       1          1567.0                          0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9             NaN               1.0  identiek aan nr. 371 in database middeleeuwen
4           4        58       Nicolai           NaN                 5                   4   Everard     1            NaN          NaN           NaN        1497.0                       1          1561.0                          0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9            10.0               5.0                                            NaN

In [186]:
concordance = pd.read_excel('./concordance_files/ident20241126.xlsx')

In [194]:
pers_plus = aanst.merge(div_en_fr, left_on='persoon_id',right_on='IDRegent').drop_duplicates()

In [209]:
pers_plus

      periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                  opmerkingen van_als_bekend  ... Heerlijkheid2 Geboortejaar OnbepaaldGeboortedatum  Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                                                                                                                                      Opmerkingen  Periode  overlijdensdag  overlijdensmaand  Opmerkingen2
0           2       2.0        10.0     1801.0      8.0       12.0    1801.0                   0                  Waarnemend.     02-10-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
1           2       2.0        10.0     1801.0      8.0       12.0    1801.0                   0                  Waarnemend.     02-10-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
2           2      16.0         7.0     1799.0      2.0       10.0    1801.0                   0  Gecontinueerd 14 juli 1800.     16-07-1799  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
3           2      16.0         7.0     1799.0      2.0       10.0    1801.0                   0  Gecontinueerd 14 juli 1800.     16-07-1799  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
4           2       3.0        12.0     1801.0     26.0        5.0    1802.0                   0   Beëindigd door overlijden.     03-12-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
...       ...       ...         ...        ...      ...        ...       ...                 ...                          ...            ...  ...           ...          ...                    ...              ...                        ...                                                                                                                                                                                                                                                                                                                              ...      ...             ...               ...           ...
5879        2       NaN         NaN     1811.0      NaN        NaN    1813.0                   0                         None           1811  ...           NaN          NaN                      0              NaN                          0  Persoonsgegevens: het is niet zeker dat de griffier van het Hof van Friesland identiek is aan de gecommitteerde in de provinciale rekenkamer van Friesland; van de gecommitteerde in de rekenkamer is alleen de initiaal van de voornaam bekend (wel zeker is dat de twee termijnen in dat college bij dezelfde persoon horen).        9             NaN               NaN           NaN
5880        2      22.0         3.0     1804.0     12.0        7.0    1806.0                   0                         None     22-03-1804  ...           NaN       1469.0                      0           1557.0                          0                                                                                                                                                                                                                                                                                                                              NaN        9            17.0               3.0           NaN
5881        2      22.0         3.0     1804.0     12.0        7.0    1806.0                   0                         None     22-03-1804  ...           NaN       1469.0                      0             1557                          0                                                                                                                                                                                                                                                                                                                              NaN        9            17.0               3.0           NaN
5882        2      30.0        12.0     1810.0      NaN       11.0    1813.0                   0                         None     30-12-1810  ...           NaN          NaN                      0           1511.0                          0                                                                                                                                                                                                                                                                                                                              NaN        9            25.0              12.0           NaN
5883        2      30.0        12.0     1810.0      NaN       11.0    1813.0                   0                         None     30-12-1810  ...           NaN          NaN                      0             1511                          0                                                                                                                                                                                                                                                                                                                              NaN        9            25.0              12.0           NaN

[5863 rows x 46 columns]

In [227]:
aanst[(aanst.divperioden==1) &(aanst.provincie_id.notna())]

       periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend             opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
25757        1       4.0         5.0     1779.0     14.0        5.0    1781.0                   0                    None     04-05-1779  ...         14.0     28.0      NaN     12520.0   0          0                  0       0                 0            1
25759        1      23.0         5.0     1680.0     13.0        4.0    1682.0                   0                    None     23-05-1680  ...         14.0     21.0      NaN     12422.0   0          0                  0       0                 0            1
25760        1      10.0        10.0     1588.0      NaN        NaN    1597.0                   0                    None     10-10-1588  ...         14.0      NaN      NaN     12423.0   0          0                  0       0                 0            1
25761        1      10.0        10.0     1588.0     26.0        7.0    1593.0                   0                    None     10-10-1588  ...         14.0      NaN      NaN     12904.0   0          0                  0       0                 0            1
25762        1      16.0         5.0     1613.0      3.0        6.0    1614.0                   0                    None     16-05-1613  ...         14.0      NaN      NaN     12904.0   0          0                  0       0                 0            1
...        ...       ...         ...        ...      ...        ...       ...                 ...                     ...            ...  ...          ...      ...      ...         ...  ..        ...                ...     ...               ...          ...
27883        1      24.0         6.0     1697.0     26.0        6.0    1698.0                   0                    None     24-06-1697  ...         14.0      NaN      NaN     13153.0   0          0                  0       0                 0            1
27884        1      30.0         4.0     1733.0      9.0        5.0    1734.0                   0                    None     30-04-1733  ...         14.0      NaN      NaN     13128.0   0          0                  0       0                 0            1
27885        1       1.0         5.0     1724.0     27.0        5.0    1725.0                   0  Aanvang: ingangsdatum.     01-05-1724  ...         14.0     21.0      NaN     13088.0   0          0                  0       0                 0            1
27886        1       1.0         5.0     1655.0     17.0       10.0    1657.0                   0  Aanvang: ingangsdatum.     01-05-1655  ...         14.0     21.0      NaN     13068.0   0          0                  0       0                 0            1
27887        1       1.0         5.0     1713.0     30.0        4.0    1715.0                   0  Aanvang: ingangsdatum.     01-05-1713  ...         14.0      NaN      NaN     13069.0   0          0                  0       0                 0            1

[1213 rows x 26 columns]

In [233]:
divu = divperiode.Geslachtsnaam.unique()

In [234]:
friesu = friezen.Geslachtsnaam.unique()

In [238]:
[n for n in friesu if n not in divu]

['During',
 'Eekens',
 'Viersen',
 'Pla',
 'Staveren',
 'Dutry',
 'Nytzem',
 'Tzjaarda',
 'Jelstanus',
 nan]

In [239]:
friesid = friezen.IDRegent.unique()

In [241]:
divid = divperiode.IDRegent.unique()

In [246]:
divfrid = list(divid) +list(friesid)

In [248]:
len(divperiode)

1022

In [250]:
divperiode

      Unnamed: 0  IDRegent Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel     Voornaam  Adel Adelspredikaat Heerlijkheid Heerlijkheid2  Geboortejaar  OnbepaaldGeboortedatum Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                Opmerkingen  Periode  overlijdensdag  overlijdensmaand                                   Opmerkingen2
0              0        16       Leisnig           van                 4                   1         Hugo     1            NaN          NaN           NaN        1465.0                       0            1538                          0                                                                                                                                                                                                        NaN        9            21.0               3.0                                            NaN
1              1        41        Botnia           NaN                 5                   1     Tialingh     1            NaN          NaN           NaN           NaN                       0            1533                          0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9             NaN               NaN                                            NaN
2              2        45        Mulert           NaN                 5                   4       Gerard     1            NaN          NaN           NaN           NaN                       0            1538                          0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9             7.0              12.0                                            NaN
3              3        57       Naarden           van                 1                   4      Maarten     0            NaN          NaN           NaN        1490.0                       1            1567                          0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9             NaN               1.0  identiek aan nr. 371 in database middeleeuwen
4              4        58       Nicolai           NaN                 5                   4      Everard     1            NaN          NaN           NaN        1497.0                       1            1561                          0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9            10.0               5.0                                            NaN
...          ...       ...           ...           ...               ...                 ...          ...   ...            ...          ...           ...           ...                     ...             ...                        ...                                                                                                                                                                                                        ...      ...             ...               ...                                            ...
1017        1017        27    Taubenheim           von                 1                   1     Christof     0            NaN          NaN           NaN           NaN                       0            1536                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1018        1018       839        Winter           NaN                 1                   3  Feijo Johan     0            NaN          NaN           NaN           NaN                       0             NaN                          0                                                                                                                                              Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9             NaN               NaN                                            NaN
1019        1019        24       Ziegler           NaN                 1                   1       Caspar     0            NaN          NaN           NaN           NaN                       0            1518                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1020        1020       336     Bouricius           van                 1                   4      Jacobus     0            NaN          NaN           NaN           NaN                       0            1672                          0                                                                                                                                                              Overig: was grietman van Engwirden 1657-1672.        9            29.0              12.0                                            NaN
1021        1021       338     Bouricius     Crack van                 1                   1     Johannes     0            NaN          NaN           NaN           NaN                       0            1700                          0                                                                                                                                                              Overig: was grietman van Engwirden 1677-1697.        9            27.0               3.0                                            NaN

[1022 rows x 20 columns]

In [249]:
len(friezen)

1040

In [ ]:
aanst[aanst.persoon_id.isin()]

In [247]:
aanst[aanst.persoon_id.isin(divfrid)]

      periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                                opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
0           2       2.0        10.0     1801.0      8.0       12.0    1801.0                   0                                Waarnemend.     02-10-1801  ...          NaN      NaN      NaN       242.0   0          0                  0       1                 0            0
1           2      16.0         7.0     1799.0      2.0       10.0    1801.0                   0                Gecontinueerd 14 juli 1800.     16-07-1799  ...          NaN      NaN      NaN       242.0   0          0                  0       1                 0            0
2           2       3.0        12.0     1801.0     26.0        5.0    1802.0                   0                 Beëindigd door overlijden.     03-12-1801  ...          NaN      NaN      NaN       242.0   0          0                  0       1                 0            0
3           2       1.0        12.0     1807.0      1.0        1.0    1809.0                   0  Herbenoemd voor 1808 op 14 december 1807.     01-12-1807  ...          NaN      NaN      NaN       128.0   0          0                  0       1                 0            0
4           2      19.0         8.0     1809.0     31.0       12.0    1811.0                   0                                       None     19-08-1809  ...          NaN      NaN      NaN       128.0   0          0                  0       1                 0            0
...       ...       ...         ...        ...      ...        ...       ...                 ...                                        ...            ...  ...          ...      ...      ...         ...  ..        ...                ...     ...               ...          ...
6659        2       NaN         5.0     1805.0      NaN        6.0    1806.0                   0                                       None        05-1805  ...          NaN      NaN      NaN        48.0   0          0                  0       1                 0            0
6710        2       NaN         4.0     1805.0      NaN        NaN       NaN                   0                                       None        04-1805  ...          NaN      NaN      NaN       662.0   0          0                  0       1                 0            0
6716        2       NaN         NaN     1811.0      NaN        NaN    1813.0                   0                                       None           1811  ...          NaN      NaN      NaN       257.0   0          0                  0       1                 0            0
6722        2      22.0         3.0     1804.0     12.0        7.0    1806.0                   0                                       None     22-03-1804  ...          NaN      NaN      NaN        23.0   0          0                  0       1                 0            0
6727        2      30.0        12.0     1810.0      NaN       11.0    1813.0                   0                                       None     30-12-1810  ...          NaN      NaN      NaN        30.0   0          0                  0       1                 0            0

[2951 rows x 26 columns]

In [190]:
duplicates = aanst[aanst.duplicated([ 'tot', 'instelling_id', 'functie_id'], keep=False)]

In [191]:
duplicates[(duplicates['divperioden']==1)]

       periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                                                           opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
25060        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     13258.0   0          0                  0       0                 0            1
25061        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0  Aanvangsdatum: benoeming door Albrecht van Saksen. Eindjaar onzeker.     25-07-1499  ...          NaN      NaN      NaN     12644.0   0          0                  0       0                 0            1
25062        0      23.0         5.0     1501.0      NaN        NaN    1519.0                   0                                                     Eindjaar onzeker.     23-05-1501  ...          NaN      NaN      NaN     12644.0   0          0                  0       0                 0            1
25063        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     12652.0   0          0                  0       0                 0            1
25064        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     12672.0   0          0                  0       0                 0            1
...        ...       ...         ...        ...      ...        ...       ...                 ...                                                                   ...            ...  ...          ...      ...      ...         ...  ..        ...                ...     ...               ...          ...
27883        1      24.0         6.0     1697.0     26.0        6.0    1698.0                   0                                                                  None     24-06-1697  ...         14.0      NaN      NaN     13153.0   0          0                  0       0                 0            1
27884        1      30.0         4.0     1733.0      9.0        5.0    1734.0                   0                                                                  None     30-04-1733  ...         14.0      NaN      NaN     13128.0   0          0                  0       0                 0            1
27885        1       1.0         5.0     1724.0     27.0        5.0    1725.0                   0                                                Aanvang: ingangsdatum.     01-05-1724  ...         14.0     21.0      NaN     13088.0   0          0                  0       0                 0            1
27886        1       1.0         5.0     1655.0     17.0       10.0    1657.0                   0                                                Aanvang: ingangsdatum.     01-05-1655  ...         14.0     21.0      NaN     13068.0   0          0                  0       0                 0            1
27887        1       1.0         5.0     1713.0     30.0        4.0    1715.0                   0                                                Aanvang: ingangsdatum.     01-05-1713  ...         14.0      NaN      NaN     13069.0   0          0                  0       0                 0            1

[2421 rows x 26 columns]

In [192]:
duplicates[(duplicates['republiek_friezen']==1)]

       periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                                                           opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
51577        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     21942.0   0          0                  1       0                 0            0
51578        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0  Aanvangsdatum: benoeming door Albrecht van Saksen. Eindjaar onzeker.     25-07-1499  ...          NaN      NaN      NaN     21326.0   0          0                  1       0                 0            0
51579        0      23.0         5.0     1501.0      NaN        NaN    1519.0                   0                           Aanvangsdatum: commissie. Eindjaar onzeker.     23-05-1501  ...          NaN      NaN      NaN     21326.0   0          0                  1       0                 0            0
51580        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     21334.0   0          0                  1       0                 0            0
51581        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     21354.0   0          0                  1       0                 0            0
...        ...       ...         ...        ...      ...        ...       ...                 ...                                                                   ...            ...  ...          ...      ...      ...         ...  ..        ...                ...     ...               ...          ...
54445        9       NaN         NaN     1579.0      NaN        NaN    1579.0                   0                                                                  None           1579  ...         14.0      NaN      NaN     21163.0   0          0                  1       0                 0            0
54446        9      16.0        11.0     1581.0      NaN        NaN    1583.0                   0                                             Aanvangsdatum: commissie.     16-11-1581  ...         14.0      NaN      NaN     21065.0   0          0                  1       0                 0            0
54447        9      22.0         7.0     1584.0      NaN        NaN    1592.0                   0                                   Aanvangsdatum: eerste aanwezigheid.     22-07-1584  ...         14.0      NaN      NaN     21889.0   0          0                  1       0                 0            0
54449        9       2.0         6.0     1585.0      NaN        NaN    1585.0                   0                                   Aanvangsdatum: eerste aanwezigheid.     02-06-1585  ...         14.0      NaN      NaN     21061.0   0          0                  1       0                 0            0
54450        9       2.0         6.0     1585.0      NaN        NaN    1585.0                   0                                   Aanvangsdatum: eerste aanwezigheid.     02-06-1585  ...         14.0      NaN      NaN     21982.0   0          0                  1       0                 0            0

[2452 rows x 26 columns]

In [193]:
# almost equal

In [107]:
aanst.columns

Index(['periode', 'begindag', 'beginmaand', 'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend', 'opmerkingen', 'van_als_bekend', 'tot_als_bekend', 'van', 'tot', 'instelling_id', 'functie_id', 'lokaal_id', 'provincie_id', 'regio_id', 'stand_id', 'persoon_id', 'me', 'republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw', 'divperioden'], dtype='object')

In [208]:
pers_plus

      periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                  opmerkingen van_als_bekend  ... Heerlijkheid2 Geboortejaar OnbepaaldGeboortedatum  Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                                                                                                                                      Opmerkingen  Periode  overlijdensdag  overlijdensmaand  Opmerkingen2
0           2       2.0        10.0     1801.0      8.0       12.0    1801.0                   0                  Waarnemend.     02-10-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
1           2       2.0        10.0     1801.0      8.0       12.0    1801.0                   0                  Waarnemend.     02-10-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
2           2      16.0         7.0     1799.0      2.0       10.0    1801.0                   0  Gecontinueerd 14 juli 1800.     16-07-1799  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
3           2      16.0         7.0     1799.0      2.0       10.0    1801.0                   0  Gecontinueerd 14 juli 1800.     16-07-1799  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
4           2       3.0        12.0     1801.0     26.0        5.0    1802.0                   0   Beëindigd door overlijden.     03-12-1801  ...           NaN          NaN                      0              NaN                          0                                                                                                                                                                                                                                                                                                                              NaN        9             NaN               NaN           NaN
...       ...       ...         ...        ...      ...        ...       ...                 ...                          ...            ...  ...           ...          ...                    ...              ...                        ...                                                                                                                                                                                                                                                                                                                              ...      ...             ...               ...           ...
5879        2       NaN         NaN     1811.0      NaN        NaN    1813.0                   0                         None           1811  ...           NaN          NaN                      0              NaN                          0  Persoonsgegevens: het is niet zeker dat de griffier van het Hof van Friesland identiek is aan de gecommitteerde in de provinciale rekenkamer van Friesland; van de gecommitteerde in de rekenkamer is alleen de initiaal van de voornaam bekend (wel zeker is dat de twee termijnen in dat college bij dezelfde persoon horen).        9             NaN               NaN           NaN
5880        2      22.0         3.0     1804.0     12.0        7.0    1806.0                   0                         None     22-03-1804  ...           NaN       1469.0                      0           1557.0                          0                                                                                                                                                                                                                                                                                                                              NaN        9            17.0               3.0           NaN
5881        2      22.0         3.0     1804.0     12.0        7.0    1806.0                   0                         None     22-03-1804  ...           NaN       1469.0                      0             1557                          0                                                                                                                                                                                                                                                                                                                              NaN        9            17.0               3.0           NaN
5882        2      30.0        12.0     1810.0      NaN       11.0    1813.0                   0                         None     30-12-1810  ...           NaN          NaN                      0           1511.0                          0                                                                                                                                                                                                                                                                                                                              NaN        9            25.0              12.0           NaN
5883        2      30.0        12.0     1810.0      NaN       11.0    1813.0                   0                         None     30-12-1810  ...           NaN          NaN                      0             1511                          0                                                                                                                                                                                                                                                                                                                              NaN        9            25.0              12.0           NaN

[5863 rows x 46 columns]

In [217]:
print(pers_plus.columns)

Index(['periode', 'begindag', 'beginmaand', 'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend', 'opmerkingen', 'van_als_bekend', 'tot_als_bekend', 'van', 'tot', 'instelling_id', 'functie_id', 'lokaal_id', 'provincie_id', 'regio_id', 'stand_id', 'persoon_id', 'me', 'republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw', 'divperioden', 'Unnamed: 0', 'IDRegent', 'Geslachtsnaam', 'Tussenvoegsel', 'IDAdellijkeTitel', 'IDAcademischeTitel', 'Voornaam', 'Adel', 'Adelspredikaat', 'Heerlijkheid', 'Heerlijkheid2', 'Geboortejaar', 'OnbepaaldGeboortedatum', 'Overlijdensjaar', 'OnbepaaldOverlijdensdatum', 'Opmerkingen', 'Periode', 'overlijdensdag', 'overlijdensmaand', 'Opmerkingen2'], dtype='object')

In [ ]:
aanst_div =

In [221]:
divperiode

      Unnamed: 0  IDRegent Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel     Voornaam  Adel Adelspredikaat Heerlijkheid Heerlijkheid2  Geboortejaar  OnbepaaldGeboortedatum Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                                                                                                Opmerkingen  Periode  overlijdensdag  overlijdensmaand                                   Opmerkingen2
0              0        16       Leisnig           van                 4                   1         Hugo     1            NaN          NaN           NaN        1465.0                       0            1538                          0                                                                                                                                                                                                        NaN        9            21.0               3.0                                            NaN
1              1        41        Botnia           NaN                 5                   1     Tialingh     1            NaN          NaN           NaN           NaN                       0            1533                          0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9             NaN               NaN                                            NaN
2              2        45        Mulert           NaN                 5                   4       Gerard     1            NaN          NaN           NaN           NaN                       0            1538                          0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9             7.0              12.0                                            NaN
3              3        57       Naarden           van                 1                   4      Maarten     0            NaN          NaN           NaN        1490.0                       1            1567                          0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9             NaN               1.0  identiek aan nr. 371 in database middeleeuwen
4              4        58       Nicolai           NaN                 5                   4      Everard     1            NaN          NaN           NaN        1497.0                       1            1561                          0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9            10.0               5.0                                            NaN
...          ...       ...           ...           ...               ...                 ...          ...   ...            ...          ...           ...           ...                     ...             ...                        ...                                                                                                                                                                                                        ...      ...             ...               ...                                            ...
1017        1017        27    Taubenheim           von                 1                   1     Christof     0            NaN          NaN           NaN           NaN                       0            1536                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1018        1018       839        Winter           NaN                 1                   3  Feijo Johan     0            NaN          NaN           NaN           NaN                       0             NaN                          0                                                                                                                                              Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9             NaN               NaN                                            NaN
1019        1019        24       Ziegler           NaN                 1                   1       Caspar     0            NaN          NaN           NaN           NaN                       0            1518                          0                                                                                                                                                                                                        NaN        9             NaN               NaN                                            NaN
1020        1020       336     Bouricius           van                 1                   4      Jacobus     0            NaN          NaN           NaN           NaN                       0            1672                          0                                                                                                                                                              Overig: was grietman van Engwirden 1657-1672.        9            29.0              12.0                                            NaN
1021        1021       338     Bouricius     Crack van                 1                   1     Johannes     0            NaN          NaN           NaN           NaN                       0            1700                          0                                                                                                                                                              Overig: was grietman van Engwirden 1677-1697.        9            27.0               3.0                                            NaN

[1022 rows x 20 columns]

In [220]:
pers_plus[pers_plus.duplicated([ 'Geslachtsnaam','tot', 'instelling_id', 'functie_id',], keep=False)][[ 'Geslachtsnaam','Voornaam','persoon_id','IDRegent','van','tot', 'instelling_id', 'functie_id','republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw']]

     Geslachtsnaam           Voornaam  persoon_id  IDRegent         van         tot  instelling_id  functie_id  republiek  republiek_friezen  batfra  negentiende_eeuw
0            Hoyer            Michiel       242.0       242  1801-10-02  1801-12-08           11.0        31.0          0                  0       1                 0
1            Hoyer            Michiel       242.0       242  1801-10-02  1801-12-08           11.0        31.0          0                  0       1                 0
2            Hoyer            Michiel       242.0       242  1799-07-16  1801-10-02           46.0       299.0          0                  0       1                 0
3            Hoyer            Michiel       242.0       242  1799-07-16  1801-10-02           46.0       299.0          0                  0       1                 0
4            Hoyer            Michiel       242.0       242  1801-12-03  1802-05-26          472.0      1024.0          0                  0       1                 0
...            ...                ...         ...       ...         ...         ...            ...         ...        ...                ...     ...               ...
5879       Boelens          Wibrandus       257.0       257  1811-01-01  1813-12-31           57.0       847.0          0                  0       1                 0
5880      Waldburg  Wilhelm Truchsess        23.0        23  1804-03-22  1806-07-12          419.0       847.0          0                  0       1                 0
5881      Waldburg  Wilhelm Truchsess        23.0        23  1804-03-22  1806-07-12          419.0       847.0          0                  0       1                 0
5882       Minnema              Frans        30.0        30  1810-12-30  1813-12-31          471.0      2056.0          0                  0       1                 0
5883       Minnema              Frans        30.0        30  1810-12-30  1813-12-31          471.0      2056.0          0                  0       1                 0

[5831 rows x 12 columns]

In [206]:
pp_duplicates

0       True
1       True
2       True
3       True
4       True
        ...
5879    True
5880    True
5881    True
5882    True
5883    True
Length: 5863, dtype: bool

In [205]:
pp_duplicates.groupby(['instelling_id', 'functie_id','tot','van']).agg({'persoon_id':tuple, 'Geslachtsnaam':tuple,'batfra':is_periode, 'republiek':is_periode, 'republiek_friezen':lambda x:is_periode(x),'me':is_periode,'divperioden':is_periode})

KeyError: 'instelling_id'

In [139]:
def is_periode(t):
    ones = t[t==1]
    if len(ones)>0:
        return True
    else:
        return False

In [140]:
t = pd.Series([0,0])

In [141]:
t[t==1]

Series([], dtype: int64)

In [148]:
ddup_gr = duplicated.groupby([ 'instelling_id', 'functie_id','tot','van', ]).agg({'persoon_id':tuple, 'batfra':is_periode, 'republiek':is_periode, 'republiek_friezen':lambda x:is_periode(x),'me':is_periode,'divperioden':is_periode})

In [149]:
ddup_gr[ddup_gr.republiek_friezen & ddup_gr.divperioden]

                                                        persoon_id  batfra  republiek  republiek_friezen     me  divperioden
instelling_id functie_id tot        van
5.0           2.0        1788-12-31 1787-05-18  (12407.0, 21089.0)   False      False               True  False         True
              8.0        1633-12-31 1631-04-07  (12752.0, 21434.0)   False      False               True  False         True
              20.0       1602-08-14 1598-01-01  (12749.0, 21431.0)   False      False               True  False         True
                         1603-04-14 1602-08-15  (13241.0, 21925.0)   False      False               True  False         True
                         1623-12-31 1603-04-15  (13313.0, 21996.0)   False      False               True  False         True
...                                                            ...     ...        ...                ...    ...          ...
524.0         847.0      1779-12-31 1755-01-01  (12996.0, 21679.0)   False      False               True  False         True
                         1782-12-31 1780-01-01  (13114.0, 21798.0)   False      False               True  False         True
                         1789-12-31 1782-01-01  (13104.0, 21788.0)   False      False               True  False         True
                         1795-12-31 1785-01-01  (12357.0, 21022.0)   False      False               True  False         True
525.0         847.0      1745-12-31 1742-01-01  (13051.0, 21735.0)   False      False               True  False         True

[1517 rows x 6 columns]

In [156]:
suggested_overlap = ddup_gr[ddup_gr.republiek_friezen & ddup_gr.divperioden].persoon_id.apply(pd.Series)

In [158]:
suggested_overlap[suggested_overlap[3].notna()]

                                                     0        1        2        3        4        5        6        7        8        9        10       11       12       13       14       15
instelling_id functie_id tot        van
5.0           560.0      1603-04-17 1601-04-07  12618.0  12619.0  12620.0  21301.0  21302.0  21300.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1673-04-23 1672-03-16  12647.0  12344.0  21009.0  21329.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1725-04-12 1722-04-16  13119.0  13023.0  21803.0  21707.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1740-04-18 1737-04-16  12352.0  13088.0  21017.0  21772.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
209.0         234.0      1515-12-31 1512-01-01  12672.0  12447.0  13306.0  12841.0  21354.0  21129.0  21989.0  21523.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
              558.0      1538-12-31 1527-07-29  12843.0  12848.0  21525.0  21530.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
              691.0      1500-12-31 1499-07-25  13258.0  12652.0  12713.0  12725.0  12763.0  12766.0  12786.0  12824.0  21942.0  21334.0  21395.0  21407.0  21445.0  21448.0  21468.0  21506.0
                         1515-12-31 1499-07-25  12644.0  12672.0  21326.0  21354.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
              1032.0     1523-12-31 1523-01-01  12850.0  12851.0  12852.0  21532.0  21533.0  21534.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1527-12-31 1515-07-04  12323.0  12843.0  20988.0  21525.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
337.0         560.0      1584-04-28 1582-07-28  12353.0  12383.0  13191.0  13192.0  21018.0  21048.0  21875.0  21876.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1604-02-26 1603-03-25  13157.0  12778.0  21841.0  21460.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1614-01-28 1612-02-22  12722.0  12762.0  21404.0  21444.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1618-05-15 1617-01-01  13262.0  12773.0  21946.0  21455.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1710-12-31 1709-11-17  13056.0  13137.0  21740.0  21821.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1782-02-11 1779-02-12  13017.0  13181.0  21700.0  21865.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1791-02-11 1788-02-12  12468.0  12596.0  21150.0  21278.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1794-02-12 1791-02-12  13036.0  12468.0  21720.0  21150.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
                         1795-12-31 1794-02-12  12733.0  12520.0  21202.0  21415.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
408.0         560.0      1614-06-03 1613-05-16  12904.0  12531.0  21586.0  21213.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [ ]:
pers_plus.groupby

Signature:
suggested_overlap.melt(
    id_vars=None,
    value_vars=None,
    var_name=None,
    value_name: 'Hashable' = 'value',
    col_level: 'Level | None' = None,
    ignore_index: 'bool' = True,
) -> 'DataFrame'
Docstring:
Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.

This function is useful to massage a DataFrame into a format where one
or more columns are identifier variables (`id_vars`), while all other
columns, considered measured variables (`value_vars`), are "unpivoted" to
the row axis, leaving just two non-identifier columns, 'variable' and
'value'.

Parameters
----------
id_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to use as identifier variables.
value_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to unpivot. If not specified, uses all columns that
    are not set as `id_vars`.
var_name : scalar, default None
    Name to use for the 'variable' column. If None it uses
    ``frame.columns.name`` or 'variable'.
value_name : scalar, default 'value'
    Name to use for the 'value' column, can't be an existing column label.
col_level : scalar, optional
    If columns are a MultiIndex then use this level to melt.
ignore_index : bool, default True
    If True, original index is ignored. If False, the original index is retained.
    Index labels will be repeated as necessary.

Returns
-------
DataFrame
    Unpivoted DataFrame.

See Also
--------
melt : Identical method.
pivot_table : Create a spreadsheet-style pivot table as a DataFrame.
DataFrame.pivot : Return reshaped DataFrame organized
    by given index / column values.
DataFrame.explode : Explode a DataFrame from list-like
        columns to long format.

Notes
-----
Reference :ref:`the user guide <reshaping.melt>` for more examples.

Examples
--------
>>> df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
...                    'B': {0: 1, 1: 3, 2: 5},
...                    'C': {0: 2, 1: 4, 2: 6}})
>>> df
   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

>>> df.melt(id_vars=['A'], value_vars=['B'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

>>> df.melt(id_vars=['A'], value_vars=['B', 'C'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

The names of 'variable' and 'value' columns can be customized:

>>> df.melt(id_vars=['A'], value_vars=['B'],
...         var_name='myVarname', value_name='myValname')
   A myVarname  myValname
0  a         B          1
1  b         B          3
2  c         B          5

Original index values can be kept around:

>>> df.melt(id_vars=['A'], value_vars=['B', 'C'], ignore_index=False)
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
0  a        C      2
1  b        C      4
2  c        C      6

If you have multi-index columns:

>>> df.columns = [list('ABC'), list('DEF')]
>>> df
   A  B  C
   D  E  F
0  a  1  2
1  b  3  4
2  c  5  6

>>> df.melt(col_level=0, id_vars=['A'], value_vars=['B'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

>>> df.melt(id_vars=[('A', 'D')], value_vars=[('B', 'E')])
  (A, D) variable_0 variable_1  value
0      a          B          E      1
1      b          B          E      3
2      c          B          E      5
File:      ~/develop/republic_clean/.venv/lib/python3.9/site-packages/pandas/core/frame.py
Type:      method

In [169]:
sug_o = suggested_overlap.melt(ignore_index=False).reset_index()

In [170]:
sug_o[sug_o.value.notna()]

       instelling_id  functie_id         tot         van  variable    value
0                5.0         2.0  1788-12-31  1787-05-18         0  12407.0
1                5.0         8.0  1633-12-31  1631-04-07         0  12752.0
2                5.0        20.0  1602-08-14  1598-01-01         0  12749.0
3                5.0        20.0  1603-04-14  1602-08-15         0  13241.0
4                5.0        20.0  1623-12-31  1603-04-15         0  13313.0
...              ...         ...         ...         ...       ...      ...
17489          209.0       691.0  1500-12-31  1499-07-25        11  21407.0
19006          209.0       691.0  1500-12-31  1499-07-25        12  21445.0
20523          209.0       691.0  1500-12-31  1499-07-25        13  21448.0
22040          209.0       691.0  1500-12-31  1499-07-25        14  21468.0
23557          209.0       691.0  1500-12-31  1499-07-25        15  21506.0

[3098 rows x 6 columns]

In [171]:
regent = pd.read_pickle('./targetdb_dump_persoon.pkl')

In [179]:
sug_res = sug_o.merge(regent, left_on='value', right_on='id').sort_values('geslachtsnaam').drop_duplicates()

In [180]:
sug_res.to_excel('./controle_dubblelen/contr_div_friezen.xlsx')

In [ ]:
sug_o

In [153]:
ddup_gr[ddup_gr.batfra & ddup_gr.republiek]

Empty DataFrame
Columns: [persoon_id, batfra, republiek, republiek_friezen, me, divperioden]
Index: []

In [252]:
aanst_nw = pd.read_pickle('./targetdb_dump_aanstelling.pkl')

In [253]:
regent

           geslachtsnaam   tussenvoegsel         voornaam  adel adelspredikaat             heerlijkheid  geboortejaar  overlijdensjaar                                                                                                                                                                                     opmerkingen  periode  ...  overlijdensdatum                searchable  academischetitel_id  adellijketitel_id me  republiek  republiek_friezen batfra  negentiende_eeuw divperioden
0                  Röell                  Willem Frederik     1           None                                 1767.0           1835.0                                   Adelspredicaat: 1815/adelstitel: 1819.\r\nOverig: bij KB van 20 juni 1810 no. 26 werd aan Röell twee maanden verlof verleend om de wateren te gaan gebruiken.        2  ...        1835-12-31                     Röell                  6.0                1.0  0          0                  0      1                 0           0
1               Mollerus                    Johan Hendrik     1           None  Westkerke en Wulpendaal        1750.0           1834.0  Adelspredicaat: 1816/adelstitel: 1820.\r\nOverig: Mollerus werd op 27 mei 1809 met de rang en het traktement van Minister belast met de uitvoering van de Wet omtrent de Constitutionele Adel.        2  ...        1834-12-31                  Mollerus                  NaN                1.0  0          0                  0      1                 0           0
2      Lodewijk Napoleon                             None     0           None                                 1778.0           1846.0                                                                                                                                                                                            None        2  ...        1846-12-31         Lodewijk Napoleon                  NaN                NaN  0          0                  0      1                 0           0
3              Crommelin  van Wickevoort       Jan Pieter     0           None                                 1763.0           1837.0                                                                                                                                                                                            None        2  ...        1837-12-31  van Wickevoort Crommelin                  NaN                NaN  0          0                  0      1                 0           0
4               Appelius                       Jean Henry     0           None                                 1767.0           1828.0                               Overig: na 13 februari 1807 was Appelius zowel Secretaris-Generaal als lid van de Staatsraad in gewone dienst. In september 1808 kwam hij in Buitengewone Dienst.        2  ...        1828-12-31                  Appelius                  NaN                NaN  0          0                  0      1                 0           0
...                  ...             ...              ...   ...            ...                      ...           ...              ...                                                                                                                                                                                             ...      ...  ...               ...                       ...                  ...                ... ..        ...                ...    ...               ...         ...
22021         Taubenheim             von         Christof     0           None                                    NaN           1536.0                                                                                                                                                                                            None        9  ...        1536-12-31            von Taubenheim                  NaN                NaN  0          0                  1      0                 0           0
22022             Winter                      Feijo Johan     0           None                                    NaN              NaN                                                                                                                                   Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9  ...              None                    Winter                  NaN                NaN  0          0                  1      0                 0           0
22023            Ziegler                           Caspar     0           None                                    NaN           1518.0                                                                                                                                                                                            None        9  ...        1518-12-31                   Ziegler                  NaN                NaN  0          0                  1      0                 0           0
22024          Bouricius             van          Jacobus     0           None                                    NaN           1672.0                                                                                                                                                   Overig: was grietman van Engwirden 1657-1672.        9  ...        1672-12-29             van Bouricius                  NaN                NaN  0          0                  1      0                 0           0
22025          Bouricius       Crack van         Johannes     0           None                                    NaN           1700.0                                                                                                                                                   Overig: was grietman van Engwirden 1677-1697.        9  ...        1700-03-27       Crack van Bouricius                  NaN                NaN  0          0                  1      0                 0           0

[22026 rows x 30 columns]

In [254]:
fr_regent = regent[regent.republiek_friezen==1]

In [256]:
div_regent = regent[regent.divperioden==1]

In [255]:
fr_regent

      geslachtsnaam tussenvoegsel     voornaam  adel adelspredikaat heerlijkheid  geboortejaar  overlijdensjaar                                                                                                                                                                                                opmerkingen  periode  ...  overlijdensdatum           searchable  academischetitel_id  adellijketitel_id me  republiek  republiek_friezen batfra  negentiende_eeuw divperioden
20986       Leisnig           van         Hugo     1           None                     1465.0           1538.0                                                                                                                                                                                                       None        9  ...        1538-03-21          van Leisnig                  NaN                7.0  0          0                  1      0                 0           0
20987        Botnia                   Tialingh     1           None                        NaN           1533.0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9  ...        1533-12-31               Botnia                  NaN               16.0  0          0                  1      0                 0           0
20988        Mulert                     Gerard     1           None                        NaN           1538.0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9  ...        1538-12-07               Mulert                  NaN               16.0  0          0                  1      0                 0           0
20989       Naarden           van      Maarten     0           None                     1490.0           1567.0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9  ...        1567-12-31          van Naarden                  NaN                NaN  0          0                  1      0                 0           0
20990       Nicolai                    Everard     1           None                     1497.0           1561.0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9  ...        1561-05-10              Nicolai                  NaN               16.0  0          0                  1      0                 0           0
...             ...           ...          ...   ...            ...          ...           ...              ...                                                                                                                                                                                                        ...      ...  ...               ...                  ...                  ...                ... ..        ...                ...    ...               ...         ...
22021    Taubenheim           von     Christof     0           None                        NaN           1536.0                                                                                                                                                                                                       None        9  ...        1536-12-31       von Taubenheim                  NaN                NaN  0          0                  1      0                 0           0
22022        Winter                Feijo Johan     0           None                        NaN              NaN                                                                                                                                              Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9  ...              None               Winter                  NaN                NaN  0          0                  1      0                 0           0
22023       Ziegler                     Caspar     0           None                        NaN           1518.0                                                                                                                                                                                                       None        9  ...        1518-12-31              Ziegler                  NaN                NaN  0          0                  1      0                 0           0
22024     Bouricius           van      Jacobus     0           None                        NaN           1672.0                                                                                                                                                              Overig: was grietman van Engwirden 1657-1672.        9  ...        1672-12-29        van Bouricius                  NaN                NaN  0          0                  1      0                 0           0
22025     Bouricius     Crack van     Johannes     0           None                        NaN           1700.0                                                                                                                                                              Overig: was grietman van Engwirden 1677-1697.        9  ...        1700-03-27  Crack van Bouricius                  NaN                NaN  0          0                  1      0                 0           0

[1040 rows x 30 columns]

In [257]:
div_regent

      geslachtsnaam tussenvoegsel     voornaam  adel adelspredikaat heerlijkheid  geboortejaar  overlijdensjaar                                                                                                                                                                                                opmerkingen  periode  ...  overlijdensdatum           searchable  academischetitel_id  adellijketitel_id me  republiek  republiek_friezen batfra  negentiende_eeuw divperioden
12321       Leisnig           van         Hugo     1           None                     1465.0           1538.0                                                                                                                                                                                                       None        9  ...        1538-03-21          van Leisnig                  NaN                7.0  0          0                  0      0                 0           1
12322        Botnia                   Tialingh     1           None                        NaN           1533.0            Adelstitel: ridderslag door stadhouder Floris van Egmond 1 juli 1515.\r\nOverig: was grietman van Ferwerderadeel, van Hennaarderadeel 1513-1524 (vermoedelijk) en van Franekeradeel vanaf 1521.        9  ...        1533-12-31               Botnia                  NaN               16.0  0          0                  0      0                 0           1
12323        Mulert                     Gerard     1           None                        NaN           1538.0  Persoonsgegevens: geboren te Utrecht.\r\nOverig: Memorialen Rosa vermeldt Gerard Mulert als onbezoldigd raadsheer in het Hof van Holland 1516-1519 en 1529. Raadsheer in de Geheime Raad in 1519 of 1523.        9  ...        1538-12-07               Mulert                  NaN               16.0  0          0                  0      0                 0           1
12324       Naarden           van      Maarten     0           None                     1490.0           1567.0                                                                                                                                                    Overig: luitenant Hoofdmannenkamer Groningen 1541-1557.        9  ...        1567-12-31          van Naarden                  NaN                NaN  0          0                  0      0                 0           1
12325       Nicolai                    Everard     1           None                     1497.0           1561.0                                                                                                               Persoonsgegevens: het geboortejaar is mogelijk 1498. Zoon van Nicolas Everaerts (1462-1532).        9  ...        1561-05-10              Nicolai                  NaN               16.0  0          0                  0      0                 0           1
...             ...           ...          ...   ...            ...          ...           ...              ...                                                                                                                                                                                                        ...      ...  ...               ...                  ...                  ...                ... ..        ...                ...    ...               ...         ...
13338    Taubenheim           von     Christof     0           None                        NaN           1536.0                                                                                                                                                                                                       None        9  ...        1536-12-31       von Taubenheim                  NaN                NaN  0          0                  0      0                 0           1
13339        Winter                Feijo Johan     0           None                        NaN              NaN                                                                                                                                              Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9  ...              None               Winter                  NaN                NaN  0          0                  0      0                 0           1
13340       Ziegler                     Caspar     0           None                        NaN           1518.0                                                                                                                                                                                                       None        9  ...        1518-12-31              Ziegler                  NaN                NaN  0          0                  0      0                 0           1
13341     Bouricius           van      Jacobus     0           None                        NaN           1672.0                                                                                                                                                              Overig: was grietman van Engwirden 1657-1672.        9  ...        1672-12-29        van Bouricius                  NaN                NaN  0          0                  0      0                 0           1
13342     Bouricius     Crack van     Johannes     0           None                        NaN           1700.0                                                                                                                                                              Overig: was grietman van Engwirden 1677-1697.        9  ...        1700-03-27  Crack van Bouricius                  NaN                NaN  0          0                  0      0                 0           1

[1022 rows x 30 columns]

In [260]:
adiv = aanst_nw[aanst_nw.persoon_id.isin(div_regent['id'].unique())]

In [261]:
afriz = aanst_nw[aanst_nw.persoon_id.isin(fr_regent['id'].unique())]

In [262]:
adiv

       periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend                                                           opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
25060        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     13258.0   0          0                  0       0                 0            1
25061        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0  Aanvangsdatum: benoeming door Albrecht van Saksen. Eindjaar onzeker.     25-07-1499  ...          NaN      NaN      NaN     12644.0   0          0                  0       0                 0            1
25062        0      23.0         5.0     1501.0      NaN        NaN    1519.0                   0                                                     Eindjaar onzeker.     23-05-1501  ...          NaN      NaN      NaN     12644.0   0          0                  0       0                 0            1
25063        0      25.0         7.0     1499.0      NaN        NaN    1500.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     12652.0   0          0                  0       0                 0            1
25064        0      25.0         7.0     1499.0      NaN        NaN    1515.0                   0                    Aanvangsdatum: benoeming door Albrecht van Saksen.     25-07-1499  ...          NaN      NaN      NaN     12672.0   0          0                  0       0                 0            1
...        ...       ...         ...        ...      ...        ...       ...                 ...                                                                   ...            ...  ...          ...      ...      ...         ...  ..        ...                ...     ...               ...          ...
27883        1      24.0         6.0     1697.0     26.0        6.0    1698.0                   0                                                                  None     24-06-1697  ...         14.0      NaN      NaN     13153.0   0          0                  0       0                 0            1
27884        1      30.0         4.0     1733.0      9.0        5.0    1734.0                   0                                                                  None     30-04-1733  ...         14.0      NaN      NaN     13128.0   0          0                  0       0                 0            1
27885        1       1.0         5.0     1724.0     27.0        5.0    1725.0                   0                                                Aanvang: ingangsdatum.     01-05-1724  ...         14.0     21.0      NaN     13088.0   0          0                  0       0                 0            1
27886        1       1.0         5.0     1655.0     17.0       10.0    1657.0                   0                                                Aanvang: ingangsdatum.     01-05-1655  ...         14.0     21.0      NaN     13068.0   0          0                  0       0                 0            1
27887        1       1.0         5.0     1713.0     30.0        4.0    1715.0                   0                                                Aanvang: ingangsdatum.     01-05-1713  ...         14.0      NaN      NaN     13069.0   0          0                  0       0                 0            1

[2828 rows x 26 columns]

In [270]:
s1 = adiv[['van_als_bekend','tot_als_bekend','functie_id','instelling_id']]

In [ ]:
s1

      van_als_bekend tot_als_bekend  functie_id  instelling_id
25060     25-07-1499           1500       691.0          209.0
25061     25-07-1499           1515       691.0          209.0
25062     23-05-1501           1519       234.0          209.0
25063     25-07-1499           1500       691.0          209.0
25064     25-07-1499           1515       691.0          209.0
...              ...            ...         ...            ...
27883     24-06-1697     26-06-1698       560.0          201.0
27884     30-04-1733     09-05-1734       560.0          201.0
27885     01-05-1724     27-05-1725       560.0          201.0
27886     01-05-1655     17-10-1657       560.0          408.0
27887     01-05-1713     30-04-1715       560.0          408.0

[2828 rows x 4 columns]

In [288]:
aanstdupl = aanst[aanst.duplicated(['van_als_bekend','tot_als_bekend','functie_id','instelling_id'],keep=False)][['van_als_bekend','tot_als_bekend','functie_id','instelling_id','persoon_id','divperioden','republiek_friezen','me','batfra']]

In [291]:
aanstdup_sel = aanstdupl[(aanstdupl['divperioden']==1)|(aanstdupl['republiek_friezen']==1)]

In [293]:
aanstdup_sel_gr = aanstdup_sel.groupby(['van_als_bekend','tot_als_bekend','functie_id','instelling_id']).agg({'persoon_id':list})

In [295]:
ids = aanstdup_sel_gr.persoon_id.apply(pd.Series)

In [298]:
molten = ids.melt(ignore_index=True)

In [300]:
m = molten[molten.value.notna()]

In [305]:
div_ids = list(div_regent['id'].unique())

In [307]:
fr_ids = list(fr_regent['id'].unique())

In [308]:
frdiv_ids = div_ids+fr_ids

In [310]:
m[~m.value.isin(frdiv_ids)]

Empty DataFrame
Columns: [variable, value]
Index: []

In [271]:
s2 = afriz[['van_als_bekend','tot_als_bekend','functie_id','instelling_id']]

In [ ]:
s2

      van_als_bekend tot_als_bekend  functie_id  instelling_id
51577     25-07-1499           1500       691.0          209.0
51578     25-07-1499           1515       691.0          209.0
51579     23-05-1501           1519       234.0          209.0
51580     25-07-1499           1500       691.0          209.0
51581     25-07-1499           1515       691.0          209.0
...              ...            ...         ...            ...
54448     23-05-1634     19-05-1637       560.0            8.0
54449     02-06-1585           1585       561.0          469.0
54450     02-06-1585           1585       561.0          469.0
54451     07-01-1586           1586       561.0          469.0
54452     11-04-1641     21-06-1642       560.0            8.0

[2876 rows x 4 columns]

In [314]:
aanstdupl[aanstdupl.batfra==1]

     van_als_bekend tot_als_bekend  functie_id  instelling_id  persoon_id  divperioden  republiek_friezen  me  batfra
4        19-08-1809     31-12-1811       847.0          219.0       128.0            0                  0   0       1
7        14-12-1801     01-05-1805       847.0          403.0        10.0            0                  0   0       1
12             1811        11-1813      1947.0          363.0      3136.0            0                  0   0       1
16       28-10-1810        11-1813       847.0           60.0       346.0            0                  0   0       1
30       30-06-1809     01-05-1811       847.0           19.0      3057.0            0                  0   0       1
...             ...            ...         ...            ...         ...          ...                ...  ..     ...
6723     14-06-1803        04-1805       821.0          447.0      2380.0            0                  0   0       1
6724     06-02-1795     16-02-1795       847.0          456.0      1439.0            0                  0   0       1
6725        03-1796     22-01-1798       847.0          321.0      1958.0            0                  0   0       1
6726        05-1805        06-1806       821.0          446.0      2383.0            0                  0   0       1
6727     30-12-1810        11-1813      2056.0          471.0        30.0            0                  0   0       1

[3950 rows x 9 columns]

In [ ]:
aanstdupl[aanstdupl.]

In [323]:
me_aanst = aanst[aanst.me==1].eindjaar.value_counts().to_frame()

In [ ]:
me_aanst[me_aanst['count']]

<bound method DataFrame.count of           count
eindjaar
1573.0       86
1477.0       79
1572.0       49
1469.0       46
1418.0       43
...         ...
1618.0        1
1662.0        1
1603.0        1
1609.0        1
146.0         1

[326 rows x 1 columns]>

In [328]:
me_aanst_bj = aanst[aanst.me==1].beginjaar.value_counts().to_frame()

In [343]:
display(me_aanst_bj[(me_aanst_bj.index>1570) & (me_aanst_bj.index<1580)].sum())

count    857
dtype: int64

In [349]:
me_aanst_bj[me_aanst_bj.index<1400].sum()

count    2396
dtype: int64

In [350]:
os.listdir('./dubbelen')

['dubbelen_BronBatFra-DivPerioden.csv',
 'dubbelen_FunctieBatfra-19.csv',
 'dubbelen_AcadTitelME-19.csv',
 'dubbelen_RegentDivPerioden-Republiek.csv',
 'dubbelen_AcadTitelRepubliek-19.csv',
 'dubbelen_RegentDivPerioden-Batfra.csv',
 'dubbelen_AcadTitelDivPerioden-19.csv',
 'dubbelen_RegentME-Republiek.csv',
 'dubbelen_AdellijkeTitelBatFra-Republiek.csv',
 'dubbelen_BronRepubliek-19.csv',
 'dubbelen_AdellijkeTitelME-19.csv',
 'dubbelen_BronDivPerioden-19.csv',
 'dubbelen_AdellijkeTitelME-Republiek.csv',
 'dubbelen_BronME-19.csv',
 'dubbelen_BronBatFra-19.csv',
 'dubbelen_RegentBatFra-19.csv',
 'dubbelen_AcadTitelRepubliek-DivPerioden.csv',
 'dubbelen_AcadTitelBatFra-DivPerioden.csv',
 'dubbelen_AdellijkeTitelME-BatFra.csv',
 'dubbelen_AcadTitelBatFra-19.csv',
 'dubbelen_FunctieBatfra-DivPerioden.csv',
 'dubbelen_CollegeME-Republiek.csv',
 'dubbelen_BronME-DivPerioden.csv',
 'dubbelen_FunctieRepubliek-19.csv',
 'dubbelen_FunctieME-19.csv',
 'dubbelen_AcadTitelME-DivPerioden.csv',
 'dubbelen_FunctieRepubliek-DivPerioden.csv',
 'dubbelen_AdellijkeTitelME-DivPerioden.csv',
 'dubbelen_FunctieDivPerioden-19.csv',
 'dubbelen_AdellijkeTitelRepubliek-DivPerioden.csv',
 'dubbelen_FunctieRepubliek-Batfra.csv',
 'dubbelen_AcadTitelME-Republiek.csv',
 'dubbelen_BronME-Republiek.csv',
 'dubbelen_RegentDivPerioden-19.csv',
 'dubbelen_RegentRepubliek-19.csv',
 'dubbelen_CollegeBatFra-Republiek.csv',
 'dubbelen_FunctieME-BatFra.csv',
 'dubbelen_AdellijkeTitelBatFra-DivPerioden.csv',
 'dubbelen_BronRepubliek-BatFra.csv',
 'dubbelen_CollegeDivPerioden-Republiek.csv',
 'dubbelen_AdellijkeTitelRepubliek-19.csv',
 'dubbelen_RegentBatFra-Republiek.csv',
 'dubbelen_CollegeME-DivPerioden.csv',
 'dubbelen_AcadTitelBatFra-Republiek.csv',
 'dubbelen_CollegeBatfra-DivPerioden.csv',
 'dubbelen_FunctieME-DivPerioden.csv',
 'dubbelen_AdellijkeTitelDivPerioden-19.csv',
 'dubbelen_BronRepubliek-DivPerioden.csv',
 'dubbelen_FunctieME-Republiek.csv',
 'dubbelen_AdellijkeTitelBatFra-19.csv',
 'dubbelen_AcadTitelME-BatFra.csv',
 'dubbelen_BronME-BatFra.csv',
 'dubbelen_RegentME-DivPerioden.csv']

In [358]:
dubbel_me_div = pd.read_csv('./dubbelen/dubbelen_RegentDivPerioden-Republiek.csv', sep='\t')

In [359]:
divperiode[divperiode.IDRegent.isin(dubbel_me_div['DivPerioden'])]

     Unnamed: 0  IDRegent    Geslachtsnaam Tussenvoegsel  IDAdellijkeTitel  IDAcademischeTitel            Voornaam  Adel Adelspredikaat Heerlijkheid                                                                           Heerlijkheid2  Geboortejaar  OnbepaaldGeboortedatum Overlijdensjaar  OnbepaaldOverlijdensdatum                                                                                                                 Opmerkingen  Periode  overlijdensdag  overlijdensmaand Opmerkingen2
218         218       574  Wassenaer-Obdam           van                 4                   1  Jacob Unico Willem     1            NaN    Wassenaar  Lage, Twickel, Obdam, Spierdijk, Wogmeer, Hensbroek, Zuidwijk, Kernhem, Weldam, Olidam        1769.0                       0            1812                          0  Persoonsgegevens: Baerdt geeft ten onrechte jaar van overlijden 1794.\r\nOverig: was grietman van Franekeradeel 1793-1794.        9            31.0               8.0          NaN

In [361]:
regent.loc[regent.geslachtsnaam=='Wassenaer-Obdam']

         geslachtsnaam tussenvoegsel            voornaam  adel adelspredikaat                                                                                         heerlijkheid  geboortejaar  overlijdensjaar                                                                                                                 opmerkingen  periode  ...  overlijdensdatum           searchable  academischetitel_id  adellijketitel_id me  republiek  republiek_friezen batfra  negentiende_eeuw divperioden
12539  Wassenaer-Obdam           van  Jacob Unico Willem     1           None  Wassenaar en Lage, Twickel, Obdam, Spierdijk, Wogmeer, Hensbroek, Zuidwijk, Kernhem, Weldam, Olidam        1769.0           1812.0  Persoonsgegevens: Baerdt geeft ten onrechte jaar van overlijden 1794.\r\nOverig: was grietman van Franekeradeel 1793-1794.        9  ...        1812-08-31  van Wassenaer-Obdam                  NaN                7.0  0          0                  0      0                 0           1
15668  Wassenaer-Obdam           van       Unico Wilhelm     1           None  Wassenaar en Lage, Twickel, Obdam, Hensbroek, Spierdijk, Wogmeer, Zuidwijk, Kernhem, Weldam, Olidam        1692.0           1766.0                                                                                                                        None        1  ...        1766-11-09  van Wassenaer-Obdam                  NaN                7.0  0          1                  0      0                 0           0
15682  Wassenaer-Obdam           van           Jacob Jan     1           None                    Wassenaar en Lage, Obdam, Hensbroek, Spierdijk, Wogmeer, Zuidwijk, Weldam, Olidam        1724.0           1779.0                                                                                                                        None        1  ...        1779-12-25  van Wassenaer-Obdam                  NaN                7.0  0          1                  0      0                 0           0
15759  Wassenaer-Obdam           van  Jacob Unico Willem     1           None  Wassenaar en Lage, Twickel, Obdam, Spierdijk, Wogmeer, Hensbroek, Zuidwijk, Kernhem, Weldam, Olidam        1769.0           1812.0  Persoonsgegevens: Baerdt geeft ten onrechte jaar van overlijden 1794.\r\nOverig: was grietman van Franekeradeel 1793-1794.        1  ...        1812-08-31  van Wassenaer-Obdam                  NaN                7.0  0          1                  0      0                 0           0
21221  Wassenaer-Obdam           van  Jacob Unico Willem     1           None  Wassenaar en Lage, Twickel, Obdam, Spierdijk, Wogmeer, Hensbroek, Zuidwijk, Kernhem, Weldam, Olidam        1769.0           1812.0  Persoonsgegevens: Baerdt geeft ten onrechte jaar van overlijden 1794.\r\nOverig: was grietman van Franekeradeel 1793-1794.        9  ...        1812-08-31  van Wassenaer-Obdam                  NaN                7.0  0          0                  1      0                 0           0

[5 rows x 30 columns]

In [362]:
regent.columns

Index(['geslachtsnaam', 'tussenvoegsel', 'voornaam', 'adel', 'adelspredikaat', 'heerlijkheid', 'geboortejaar', 'overlijdensjaar', 'opmerkingen', 'periode', 'eindcontrole', 'geboortedag', 'geboortemaand', 'doopjaar', 'geboorteplaats', 'overlijdensdag', 'overlijdensmaand', 'overlijdensplaats', 'id', 'geboortedatum', 'overlijdensdatum', 'searchable', 'academischetitel_id', 'adellijketitel_id', 'me', 'republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw', 'divperioden'], dtype='object')

In [390]:
dupl_regent = regent[(regent.divperioden==0)&(regent.me==0)][regent.duplicated(['geslachtsnaam', 'tussenvoegsel', 'voornaam', 'heerlijkheid', 'geboortejaar', 'overlijdensjaar', 'opmerkingen'], keep=False)]

alle lege geslachtsnamen zitten in middeleeuwen

In [407]:
dupl_regent

      geslachtsnaam   tussenvoegsel         voornaam  adel adelspredikaat             heerlijkheid  geboortejaar  overlijdensjaar                                                                                                                                                                                     opmerkingen  periode  ...  overlijdensdatum                searchable  academischetitel_id  adellijketitel_id me  republiek  republiek_friezen batfra  negentiende_eeuw divperioden
0             Röell                  Willem Frederik     1           None                                 1767.0           1835.0                                   Adelspredicaat: 1815/adelstitel: 1819.\r\nOverig: bij KB van 20 juni 1810 no. 26 werd aan Röell twee maanden verlof verleend om de wateren te gaan gebruiken.        2  ...        1835-12-31                     Röell                  6.0                1.0  0          0                  0      1                 0           0
1          Mollerus                    Johan Hendrik     1           None  Westkerke en Wulpendaal        1750.0           1834.0  Adelspredicaat: 1816/adelstitel: 1820.\r\nOverig: Mollerus werd op 27 mei 1809 met de rang en het traktement van Minister belast met de uitvoering van de Wet omtrent de Constitutionele Adel.        2  ...        1834-12-31                  Mollerus                  NaN                1.0  0          0                  0      1                 0           0
3         Crommelin  van Wickevoort       Jan Pieter     0           None                                 1763.0           1837.0                                                                                                                                                                                            None        2  ...        1837-12-31  van Wickevoort Crommelin                  NaN                NaN  0          0                  0      1                 0           0
4          Appelius                       Jean Henry     0           None                                 1767.0           1828.0                               Overig: na 13 februari 1807 was Appelius zowel Secretaris-Generaal als lid van de Staatsraad in gewone dienst. In september 1808 kwam hij in Buitengewone Dienst.        2  ...        1828-12-31                  Appelius                  NaN                NaN  0          0                  0      1                 0           0
5           Cambier                        Jacob Jan     0           None                                 1756.0           1831.0                                                                                  Overig: bij KB van 3 maart 1810 no. 1 werd Cambier reeds tijdelijk mede belast met de portefeuille van Oorlog.        2  ...        1831-12-31                   Cambier                  NaN                NaN  0          0                  0      1                 0           0
...             ...             ...              ...   ...            ...                      ...           ...              ...                                                                                                                                                                                             ...      ...  ...               ...                       ...                  ...                ... ..        ...                ...    ...               ...         ...
22021    Taubenheim             von         Christof     0           None                                    NaN           1536.0                                                                                                                                                                                            None        9  ...        1536-12-31            von Taubenheim                  NaN                NaN  0          0                  1      0                 0           0
22022        Winter                      Feijo Johan     0           None                                    NaN              NaN                                                                                                                                   Persoonsgegevens: mogelijk promotie in de rechten, dus 'mr.'.        9  ...              None                    Winter                  NaN                NaN  0          0                  1      0                 0           0
22023       Ziegler                           Caspar     0           None                                    NaN           1518.0                                                                                                                                                                                            None        9  ...        1518-12-31                   Ziegler                  NaN                NaN  0          0                  1      0                 0           0
22024     Bouricius             van          Jacobus     0           None                                    NaN           1672.0                                                                                                                                                   Overig: was grietman van Engwirden 1657-1672.        9  ...        1672-12-29             van Bouricius                  NaN                NaN  0          0                  1      0                 0           0
22025     Bouricius       Crack van         Johannes     0           None                                    NaN           1700.0                                                                                                                                                   Overig: was grietman van Engwirden 1677-1697.        9  ...        1700-03-27       Crack van Bouricius                  NaN                NaN  0          0                  1      0                 0           0

[2000 rows x 30 columns]

       Unnamed: 0 geslachtsnaam_latest geslachtsnaam_oldnew  id_latest          id_regent_orig  id_oldnew
21150       21150              Pytters              Pytters    21425.0  republiek_friezen_1035        NaN
21222       21222              Idsinga              Idsinga    21927.0  republiek_friezen_1111        NaN
21246       21246             Heemstra             Heemstra    21214.0  republiek_friezen_1133        NaN
21712       21712              Jongema              Jongema    21027.0   republiek_friezen_506        NaN
21757       21757              Bergsma              Bergsma    21783.0   republiek_friezen_558        NaN

In [380]:
concordance.columns

Index(['Unnamed: 0', 'geslachtsnaam_latest', 'geslachtsnaam_oldnew', 'id_latest', 'id_regent_orig', 'id_oldnew'], dtype='object')

In [381]:
dubbel_in_regent = concordance.merge(dupl_regent, left_on='id_latest', right_on='id').sort_values(['geslachtsnaam'])

In [378]:
dubbel_in_regent.to_excel('./controle_dubblelen/dubbel_regent_20241204.xlsx')

## check database

In [395]:
sample = regent.sample(20)

In [399]:
sample_republiek = regent[(regent['republiek']==1) | (regent['republiek_friezen']==1)].sample(20)

In [401]:
r_ids = sample_republiek['id']

In [402]:
sample.columns

Index(['geslachtsnaam', 'tussenvoegsel', 'voornaam', 'adel', 'adelspredikaat', 'heerlijkheid', 'geboortejaar', 'overlijdensjaar', 'opmerkingen', 'periode', 'eindcontrole', 'geboortedag', 'geboortemaand', 'doopjaar', 'geboorteplaats', 'overlijdensdag', 'overlijdensmaand', 'overlijdensplaats', 'id', 'geboortedatum', 'overlijdensdatum', 'searchable', 'academischetitel_id', 'adellijketitel_id', 'me', 'republiek', 'republiek_friezen', 'batfra', 'negentiende_eeuw', 'divperioden'], dtype='object')

In [443]:
#from the conversion code

from data_definitions import *
transposed_graph = {'AcademischeTitel': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'AdellijkeTitel': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'aliassen': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'Bron': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'BronFunctieDetails': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'BronRegentDetails': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'College': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'Data': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'Functie': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'FunctieBovenLokaal': [' batfra',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'FunctieLokaal': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'lokaal': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'provinciaal': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'Regent': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'regionaal': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'stand': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'BovenLokaalCollegeRegentDetails': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' divperioden',
              ' republiek',
              'republiek_friezen'],
             'Gewest': [' batfra',
              ' negentiende eeuw',
              ' me',
              ' republiek',
              'republiek_friezen'],
             'Temp': [' negentiende eeuw'],
             'BovenLokaalCollegeRegentDetails1': [' me'],
             'TempTable': [' me'],
             'RegentOud': [' republiek', 'republiek_friezen']}

common_tables = ['AcademischeTitel',
 'AdellijkeTitel',
 'aliassen',
 'Bron',
 'BronRegentDetails',
 'College',
 'Functie',
 'FunctieBovenLokaal',
 'FunctieLokaal',
 'lokaal',
 'provinciaal',
 'Regent',
 'regionaal',
 'stand',
 'BovenLokaalCollegeRegentDetails']

In [444]:
import json
with open('connection.json','r') as infl:
    con = json.load(infl)

connection_string = con['raa_old']
toedirs = con['toe_dirs']
batfralokatie = con['batfralokatie']
table_dict = defaultdict(dict)
for table in common_tables:
    for periode in transposed_graph[table]:
        periode = periode.strip().replace(' ', '_')
        tname = '_'.join([periode, table]).strip()
        print(f"getting {tname}")
        dftable = pd.read_sql_table(con=connection_string, table_name=tname)
        dftable = dftable.rename(columns={c:c.lower() for c in dftable.columns})
        dftable.reset_index(inplace=True)
        if table.lower() in replacements:
            targettable = replacements[table.lower()]
        else:
            targettable = table.lower()
        print(f"adding {table.lower()} to {periode} as {targettable}")
        table_dict[periode][targettable] = dftable

getting batfra_AcademischeTitel
adding academischetitel to batfra as academischetitel
getting negentiende_eeuw_AcademischeTitel
adding academischetitel to negentiende_eeuw as academischetitel
getting me_AcademischeTitel
adding academischetitel to me as academischetitel
getting divperioden_AcademischeTitel
adding academischetitel to divperioden as academischetitel
getting republiek_AcademischeTitel
adding academischetitel to republiek as academischetitel
getting republiek_friezen_AcademischeTitel
adding academischetitel to republiek_friezen as academischetitel
getting batfra_AdellijkeTitel
adding adellijketitel to batfra as adellijketitel
getting negentiende_eeuw_AdellijkeTitel
adding adellijketitel to negentiende_eeuw as adellijketitel
getting me_AdellijkeTitel
adding adellijketitel to me as adellijketitel
getting divperioden_AdellijkeTitel
adding adellijketitel to divperioden as adellijketitel
getting republiek_AdellijkeTitel
adding adellijketitel to republiek as adellijketitel
getting republiek_friezen_AdellijkeTitel
adding adellijketitel to republiek_friezen as adellijketitel
getting batfra_aliassen
adding aliassen to batfra as aliassen
getting negentiende_eeuw_aliassen
adding aliassen to negentiende_eeuw as aliassen
getting me_aliassen
adding aliassen to me as aliassen
getting divperioden_aliassen
adding aliassen to divperioden as aliassen
getting republiek_aliassen
adding aliassen to republiek as aliassen
getting republiek_friezen_aliassen
adding aliassen to republiek_friezen as aliassen
getting batfra_Bron
adding bron to batfra as bron
getting negentiende_eeuw_Bron
adding bron to negentiende_eeuw as bron
getting me_Bron
adding bron to me as bron
getting divperioden_Bron
adding bron to divperioden as bron
getting republiek_Bron
adding bron to republiek as bron
getting republiek_friezen_Bron
adding bron to republiek_friezen as bron
getting batfra_BronRegentDetails
adding bronregentdetails to batfra as bronregentdetails
getting negentiende_eeuw_BronRegentDetails
adding bronregentdetails to negentiende_eeuw as bronregentdetails
getting me_BronRegentDetails
adding bronregentdetails to me as bronregentdetails
getting divperioden_BronRegentDetails
adding bronregentdetails to divperioden as bronregentdetails
getting republiek_BronRegentDetails
adding bronregentdetails to republiek as bronregentdetails
getting republiek_friezen_BronRegentDetails
adding bronregentdetails to republiek_friezen as bronregentdetails
getting batfra_College
adding college to batfra as college
getting negentiende_eeuw_College
adding college to negentiende_eeuw as college
getting me_College
adding college to me as college
getting divperioden_College
adding college to divperioden as college
getting republiek_College
adding college to republiek as college
getting republiek_friezen_College
adding college to republiek_friezen as college
getting batfra_Functie
adding functie to batfra as functie
getting negentiende_eeuw_Functie
adding functie to negentiende_eeuw as functie
getting me_Functie
adding functie to me as functie
getting divperioden_Functie
adding functie to divperioden as functie
getting republiek_Functie
adding functie to republiek as functie
getting republiek_friezen_Functie
adding functie to republiek_friezen as functie
getting batfra_FunctieBovenLokaal
adding functiebovenlokaal to batfra as functiebovenlokaal
getting me_FunctieBovenLokaal
adding functiebovenlokaal to me as functiebovenlokaal
getting divperioden_FunctieBovenLokaal
adding functiebovenlokaal to divperioden as functiebovenlokaal
getting republiek_FunctieBovenLokaal
adding functiebovenlokaal to republiek as functiebovenlokaal
getting republiek_friezen_FunctieBovenLokaal
adding functiebovenlokaal to republiek_friezen as functiebovenlokaal
getting batfra_FunctieLokaal
adding functielokaal to batfra as functielokaal
getting negentiende_eeuw_FunctieLokaal
adding functielokaal to negentiende_eeuw as functielokaal
getting me_FunctieLokaal
adding functielokaal to me as functielokaal
getting divperioden_FunctieLokaal
adding functielokaal to divperioden as functielokaal
getting republiek_FunctieLokaal
adding functielokaal to republiek as functielokaal
getting republiek_friezen_FunctieLokaal
adding functielokaal to republiek_friezen as functielokaal
getting batfra_lokaal
adding lokaal to batfra as lokaal
getting negentiende_eeuw_lokaal
adding lokaal to negentiende_eeuw as lokaal
getting me_lokaal
adding lokaal to me as lokaal
getting divperioden_lokaal
adding lokaal to divperioden as lokaal
getting republiek_lokaal
adding lokaal to republiek as lokaal
getting republiek_friezen_lokaal
adding lokaal to republiek_friezen as lokaal
getting batfra_provinciaal
adding provinciaal to batfra as provinciaal
getting negentiende_eeuw_provinciaal
adding provinciaal to negentiende_eeuw as provinciaal
getting me_provinciaal
adding provinciaal to me as provinciaal
getting divperioden_provinciaal
adding provinciaal to divperioden as provinciaal
getting republiek_provinciaal
adding provinciaal to republiek as provinciaal
getting republiek_friezen_provinciaal
adding provinciaal to republiek_friezen as provinciaal
getting batfra_Regent
adding regent to batfra as persoon
getting negentiende_eeuw_Regent
adding regent to negentiende_eeuw as persoon
getting me_Regent
adding regent to me as persoon
getting divperioden_Regent
adding regent to divperioden as persoon
getting republiek_Regent
adding regent to republiek as persoon
getting republiek_friezen_Regent
adding regent to republiek_friezen as persoon
getting batfra_regionaal
adding regionaal to batfra as regionaal
getting negentiende_eeuw_regionaal
adding regionaal to negentiende_eeuw as regionaal
getting me_regionaal
adding regionaal to me as regionaal
getting divperioden_regionaal
adding regionaal to divperioden as regionaal
getting republiek_regionaal
adding regionaal to republiek as regionaal
getting republiek_friezen_regionaal
adding regionaal to republiek_friezen as regionaal
getting batfra_stand
adding stand to batfra as stand
getting negentiende_eeuw_stand
adding stand to negentiende_eeuw as stand
getting me_stand
adding stand to me as stand
getting divperioden_stand
adding stand to divperioden as stand
getting republiek_stand
adding stand to republiek as stand
getting republiek_friezen_stand
adding stand to republiek_friezen as stand
getting batfra_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to batfra as aanstelling
getting negentiende_eeuw_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to negentiende_eeuw as aanstelling
getting me_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to me as aanstelling
getting divperioden_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to divperioden as aanstelling
getting republiek_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to republiek as aanstelling
getting republiek_friezen_BovenLokaalCollegeRegentDetails
adding bovenlokaalcollegeregentdetails to republiek_friezen as aanstelling

In [448]:
table_dict.keys()

dict_keys(['batfra', 'negentiende_eeuw', 'me', 'divperioden', 'republiek', 'republiek_friezen'])

In [ ]:
# b.columns

Index(['Unnamed: 0', 'index', 'id', 'periode', 'idregent', 'idfunctie', 'idcollege', 'begindag', 'beginmaand', 'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend', 'provinciaal', 'opmerkingen', 'stand', 'lokaal', 'regio', 'old_id', 'old_idregent', 'old_idfunctie', 'old_idcollege', 'old_lokaal', 'old_provinciaal', 'old_regio', 'old_stand', 'old_vertegenwoordigend'], dtype='object')

In [446]:
sampleids = [f'republiek_{i}' for i in sample_republiek['id']]

In [447]:
sampleids

['republiek_17001',
 'republiek_13872',
 'republiek_21359',
 'republiek_17570',
 'republiek_14096',
 'republiek_16825',
 'republiek_17430',
 'republiek_18025',
 'republiek_21796',
 'republiek_20581',
 'republiek_14954',
 'republiek_17387',
 'republiek_14822',
 'republiek_14418',
 'republiek_13946',
 'republiek_14464',
 'republiek_17739',
 'republiek_14644',
 'republiek_19624',
 'republiek_16117']

In [530]:
r = table_dict['republiek']['persoon']

In [463]:
f = table_dict['republiek_friezen']['persoon']

In [457]:
oldids = concordance[concordance['id_latest'].isin(sample_republiek['id'])].copy()

In [460]:
oldids[['db','idnr']] = oldids['id_regent_orig'].apply(lambda x: pd.Series(x.rsplit('_',1)))

In [474]:
oldids['idnr'] = oldids.idnr.astype("Int64")

In [475]:
oldids

       Unnamed: 0 geslachtsnaam_latest geslachtsnaam_oldnew  id_latest         id_regent_orig  id_oldnew                 db  idnr
13442       13442                 Laen                 Laen    14418.0         republiek_1096    14538.0          republiek  1096
13494       13494            Hoogtwoud            Hoogtwoud    14464.0         republiek_1145    14585.0          republiek  1145
13697       13697             Uythoeck             Uythoeck    14644.0         republiek_1339    14770.0          republiek  1339
13905       13905              Pranger              Pranger    14822.0         republiek_1531    14958.0          republiek  1531
14057       14057                 Witt                 Witt    14954.0         republiek_1708    15093.0          republiek  1708
15083       15083            Rosenboom            Rosenboom    14096.0         republiek_2776    14173.0          republiek  2776
15508       15508                 Goch                 Goch    16117.0         republiek_3190    16300.0          republiek  3190
16317       16317  Moreau van Limburch  Moreau van Limburch    16825.0         republiek_3975    17025.0          republiek  3975
16493       16493                 Goes                 Goes    17001.0         republiek_4153    17181.0          republiek  4153
17144       17144          Bijsterveld          Bijsterveld    17387.0         republiek_4812    17704.0          republiek  4812
17209       17209   Balveren tot Driel   Balveren tot Driel    17430.0         republiek_4874    17757.0          republiek  4874
17458       17458               Sijsen               Sijsen    17570.0         republiek_5106    17967.0          republiek  5106
17714       17714           Wicheringe           Wicheringe    17739.0         republiek_5351    18189.0          republiek  5351
18391       18391                  Zee                  Zee    13872.0          republiek_599    13910.0          republiek   599
18901       18901                 Cock                 Cock    18025.0         republiek_6464    18553.0          republiek  6464
19222       19222            Voorburgh            Voorburgh    13946.0          republiek_677    13987.0          republiek   677
19651       19651                 Wart                 Wart    19624.0         republiek_7185    19793.0          republiek  7185
20103       20103                Rothé                Rothé    20581.0         republiek_7610        NaN          republiek  7610
21792       21792               Ouwens               Ouwens    21796.0  republiek_friezen_591        NaN  republiek_friezen   591
22019       22019             Jeltinga             Jeltinga    21359.0  republiek_friezen_851        NaN  republiek_friezen   851

In [532]:
r[r['idregent']==5106]

      index  idregent geslachtsnaam tussenvoegsel  idadellijketitel  idacademischetitel voornaam  adel adelspredikaat heerlijkheid heerlijkheid2  geboortejaar  onbepaaldgeboortedatum  overlijdensjaar  onbepaaldoverlijdensdatum opmerkingen  opmerkingen2  periode  overlijdensdag  overlijdensmaand
4226   4226      5106        Sijsen           van               1.0                 7.0  Hendrik     0           None         None          None        1705.0                       0           1801.0                          0        None           NaN        1            25.0               1.0

In [476]:
rep_ids = oldids[(oldids['db']=='republiek')]['idnr']

In [478]:
rep_ids.unique()

<IntegerArray>
[1096, 1145, 1339, 1531, 1708, 2776, 3190, 3975, 4153, 4812, 4874, 5106, 5351, 599, 6464, 677, 7185, 7610]
Length: 18, dtype: Int64

In [535]:
comp_cols = ['geslachtsnaam_latest',
  'geslachtsnaam_oldnew',
  'id_latest',
  'id_regent_orig',
  'id_oldnew',
  'db',
  'idnr',
  'geslachtsnaam','idregent']

In [536]:
compres = r.merge(oldids[oldids['db']=='republiek'], left_on='idregent', right_on='idnr')[comp_cols]

In [537]:
compres

   geslachtsnaam_latest geslachtsnaam_oldnew  id_latest  id_regent_orig  id_oldnew         db  idnr        geslachtsnaam  idregent
0                   Zee                  Zee    13872.0   republiek_599    13910.0  republiek   599                  Zee       599
1             Voorburgh            Voorburgh    13946.0   republiek_677    13987.0  republiek   677            Voorburgh       677
2             Rosenboom            Rosenboom    14096.0  republiek_2776    14173.0  republiek  2776            Rosenboom      2776
3                  Laen                 Laen    14418.0  republiek_1096    14538.0  republiek  1096                 Laen      1096
4             Hoogtwoud            Hoogtwoud    14464.0  republiek_1145    14585.0  republiek  1145            Hoogtwoud      1145
5              Uythoeck             Uythoeck    14644.0  republiek_1339    14770.0  republiek  1339             Uythoeck      1339
6               Pranger              Pranger    14822.0  republiek_1531    14958.0  republiek  1531              Pranger      1531
7                  Witt                 Witt    14954.0  republiek_1708    15093.0  republiek  1708                 Witt      1708
8                  Goch                 Goch    16117.0  republiek_3190    16300.0  republiek  3190                 Goch      3190
9   Moreau van Limburch  Moreau van Limburch    16825.0  republiek_3975    17025.0  republiek  3975  Moreau van Limburch      3975
10                 Goes                 Goes    17001.0  republiek_4153    17181.0  republiek  4153                 Goes      4153
11          Bijsterveld          Bijsterveld    17387.0  republiek_4812    17704.0  republiek  4812          Bijsterveld      4812
12   Balveren tot Driel   Balveren tot Driel    17430.0  republiek_4874    17757.0  republiek  4874   Balveren tot Driel      4874
13               Sijsen               Sijsen    17570.0  republiek_5106    17967.0  republiek  5106               Sijsen      5106
14           Wicheringe           Wicheringe    17739.0  republiek_5351    18189.0  republiek  5351           Wicheringe      5351
15                 Cock                 Cock    18025.0  republiek_6464    18553.0  republiek  6464                 Cock      6464
16                 Wart                 Wart    19624.0  republiek_7185    19793.0  republiek  7185                 Wart      7185
17                Rothé                Rothé    20581.0  republiek_7610        NaN  republiek  7610                Rothé      7610

In [538]:
compres[compres['geslachtsnaam']==compres['geslachtsnaam_latest']]

   geslachtsnaam_latest geslachtsnaam_oldnew  id_latest  id_regent_orig  id_oldnew         db  idnr        geslachtsnaam  idregent
0                   Zee                  Zee    13872.0   republiek_599    13910.0  republiek   599                  Zee       599
1             Voorburgh            Voorburgh    13946.0   republiek_677    13987.0  republiek   677            Voorburgh       677
2             Rosenboom            Rosenboom    14096.0  republiek_2776    14173.0  republiek  2776            Rosenboom      2776
3                  Laen                 Laen    14418.0  republiek_1096    14538.0  republiek  1096                 Laen      1096
4             Hoogtwoud            Hoogtwoud    14464.0  republiek_1145    14585.0  republiek  1145            Hoogtwoud      1145
5              Uythoeck             Uythoeck    14644.0  republiek_1339    14770.0  republiek  1339             Uythoeck      1339
6               Pranger              Pranger    14822.0  republiek_1531    14958.0  republiek  1531              Pranger      1531
7                  Witt                 Witt    14954.0  republiek_1708    15093.0  republiek  1708                 Witt      1708
8                  Goch                 Goch    16117.0  republiek_3190    16300.0  republiek  3190                 Goch      3190
9   Moreau van Limburch  Moreau van Limburch    16825.0  republiek_3975    17025.0  republiek  3975  Moreau van Limburch      3975
10                 Goes                 Goes    17001.0  republiek_4153    17181.0  republiek  4153                 Goes      4153
11          Bijsterveld          Bijsterveld    17387.0  republiek_4812    17704.0  republiek  4812          Bijsterveld      4812
12   Balveren tot Driel   Balveren tot Driel    17430.0  republiek_4874    17757.0  republiek  4874   Balveren tot Driel      4874
13               Sijsen               Sijsen    17570.0  republiek_5106    17967.0  republiek  5106               Sijsen      5106
14           Wicheringe           Wicheringe    17739.0  republiek_5351    18189.0  republiek  5351           Wicheringe      5351
15                 Cock                 Cock    18025.0  republiek_6464    18553.0  republiek  6464                 Cock      6464
16                 Wart                 Wart    19624.0  republiek_7185    19793.0  republiek  7185                 Wart      7185
17                Rothé                Rothé    20581.0  republiek_7610        NaN  republiek  7610                Rothé      7610

In [539]:
con

{'raa_old': 'mysql+pymysql://rik:X0chi@localhost/raa_old',
 'raa_out': 'mysql+pymysql://rik:X0chi@localhost/raa_nw',
 'batfralokatie': '/Users/rikhoekstra/Downloads/ing_databases/batfratijd/instelling20240410.csv',
 'toe_dirs': ['./original/brondata/Republiek/Institutionele toelichtingen Republiek/',
  './original/brondata/ME/Institutionele toelichtingen ME/',
  './original/brondata/Negentiende eeuw/Institutionele toelichtingen 19de eeuw/']}

In [540]:

connection_string = con['raa_out']
aanstellingen = pd.read_sql_table(con=connection_string, table_name='aanstelling')

In [542]:
a = table_dict['republiek']['aanstelling']
ares = a[a['idregent'].isin(rep_ids)]
ares #[acc]

       index     id  periode  idregent  idfunctie  idcollege  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend  provinciaal                                                  opmerkingen  lokaal  regio  stand
944      944   2422        1    1145.0        1.0        8.0      25.0         6.0     1638.0      9.0        4.0    1640.0                   0          NaN                 Aanvangsdatum: benoeming door de vroedschap.    14.0    NaN    NaN
945      945   2423        1    1145.0        1.0        8.0       8.0        11.0     1641.0      NaN        NaN    1644.0                   0          NaN                 Aanvangsdatum: benoeming door de vroedschap.    14.0    NaN    NaN
946      946   2424        1    1145.0        1.0       33.0      16.0        11.0     1634.0     30.0        4.0    1637.0                   0          3.0         Aanvangsdatum: benoeming door de Staten van Holland.    14.0    NaN    NaN
947      947   2425        1    1145.0        1.0       33.0       9.0         5.0     1647.0     30.0        4.0    1649.0                   0          3.0                    Aanvangsdatum: commissie Staten-Generaal.    14.0    NaN    NaN
1354    1354   1327        1     599.0        1.0        8.0      16.0         1.0     1718.0     15.0        5.0    1719.0                   0          NaN  Zittingsdata uit Bossaers (zie institutionele toelichting).    18.0    NaN    NaN
...      ...    ...      ...       ...        ...        ...       ...         ...        ...      ...        ...       ...                 ...          ...                                                          ...     ...    ...    ...
21355  21355  14019        1    5106.0        1.0       28.0      10.0         5.0     1776.0     11.0        5.0    1777.0                   0          2.0       Aanvangsdatum: benoeming door de Staten van Groningen.     NaN    0.0    0.0
21361  21361  16908        1    5106.0        1.0       28.0      28.0         3.0     1741.0     26.0        4.0    1742.0                   0          2.0       Aanvangsdatum: benoeming door de Staten van Groningen.     NaN    NaN    0.0
21362  21362  16910        1    5106.0        1.0       28.0       1.0         5.0     1747.0     26.0        5.0    1748.0                   0          2.0       Aanvangsdatum: benoeming door de Staten van Groningen.     NaN    NaN    0.0
21752  21752  22872        1    1145.0       90.0       39.0       NaN         NaN     1632.0      5.0       10.0    1652.0                   0          3.0                                   Beëindigd door overlijden.    14.0    0.0    0.0
23148  23148  26042        1    7610.0       90.0       35.0       NaN         5.0     1632.0     26.0       10.0    1656.0                   0          3.0                                   Beëindigd door overlijden.     6.0    0.0    0.0

[68 rows x 18 columns]

In [527]:
ares.groupby('idregent').agg('count')

          index  id  periode  idfunctie  idcollege  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend  provinciaal  opmerkingen  lokaal  regio  stand
idregent
599.0         4   4        4          4          4         3           3          4        3          3         4                   4            2            3       3      1      1
677.0         2   2        2          2          2         1           1          2        1          1         2                   2            0            1       1      0      0
1096.0        4   4        4          4          4         3           3          4        3          3         4                   4            1            3       3      0      0
1145.0        7   7        7          7          7         5           5          7        5          5         7                   7            4            6       6      2      2
1339.0        2   2        2          2          2         1           1          2        1          1         2                   2            2            1       1      0      0
1531.0        2   2        2          2          2         1           1          2        1          1         2                   2            2            1       1      0      0
1708.0        3   3        3          3          3         1           1          3        3          3         3                   3            2            2       0      1      2
2776.0        2   2        2          2          2         2           2          2        2          2         2                   2            2            2       1      1      1
3190.0        2   2        2          2          2         1           1          2        0          0         1                   2            2            1       1      2      2
3975.0        1   1        1          1          1         1           1          1        0          1         1                   1            1            1       0      1      1
4153.0        1   1        1          1          1         1           1          1        0          0         0                   1            1            1       0      1      1
4812.0        4   4        4          4          4         3           3          3        1          1         1                   4            4            3       2      4      4
4874.0        1   1        1          1          1         1           1          1        0          0         0                   1            1            1       0      1      1
5106.0       23  23       23         23         23        21          21         23       16         17        20                  23           22           22       1     18     23
5351.0        6   6        6          6          6         5           5          6        4          4         5                   6            6            5       0      6      6
6464.0        2   2        2          2          2         1           1          2        0          0         1                   2            2            1       1      2      2
7185.0        1   1        1          1          1         1           1          1        1          1         1                   1            1            1       1      1      1
7610.0        1   1        1          1          1         0           1          1        1          1         1                   1            1            1       1      1      1

In [519]:
aanstres = aanstellingen[aanstellingen['persoon_id'].isin(rep_ids)]

In [526]:
aanstres.groupby('persoon_id').agg('count')

            periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend  opmerkingen  van_als_bekend  ...  lokaal_id  provincie_id  regio_id  stand_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
persoon_id                                                                                                                           ...
599.0             1         1           1          1        1          1         1                   1            0               1  ...          0             0         0         0   1          1                  1       1                 1            1
677.0             6         4           4          6        2          3         5                   6            0               6  ...          0             0         0         0   6          6                  6       6                 6            6
1096.0            1         1           1          1        0          0         0                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
1145.0            1         1           1          1        0          0         0                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
1339.0            1         1           1          1        0          0         1                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
1531.0            1         1           1          1        1          1         1                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
1708.0            1         1           1          1        1          1         1                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
2776.0            2         1           1          1        1          2         2                   2            0               2  ...          0             0         0         0   2          2                  2       2                 2            2
3190.0            1         1           1          1        0          0         0                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
3975.0            4         4           4          4        3          3         3                   4            0               4  ...          0             1         0         0   4          4                  4       4                 4            4
4153.0            1         1           1          1        1          1         1                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
4812.0            1         1           1          1        1          1         1                   1            1               1  ...          0             0         0         0   1          1                  1       1                 1            1
4874.0            2         2           2          2        2          2         2                   2            0               2  ...          0             0         0         0   2          2                  2       2                 2            2
5106.0            1         1           1          1        1          1         1                   1            0               1  ...          1             0         0         0   1          1                  1       1                 1            1
5351.0            1         1           1          1        1          1         1                   1            1               1  ...          0             1         0         0   1          1                  1       1                 1            1
6464.0            1         1           1          1        1          1         1                   1            1               1  ...          0             0         0         1   1          1                  1       1                 1            1
7185.0            1         0           0          1        0          0         0                   1            0               1  ...          0             0         0         0   1          1                  1       1                 1            1
7610.0            1         0           0          1        0          0         0                   1            0               1  ...          0             0         0         0   1          1                  1       1                 1            1

[18 rows x 25 columns]

In [543]:
ares[ares['idregent']==1145]

       index     id  periode  idregent  idfunctie  idcollege  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend  provinciaal                                                              opmerkingen  lokaal  regio  stand
944      944   2422        1    1145.0        1.0        8.0      25.0         6.0     1638.0      9.0        4.0    1640.0                   0          NaN                             Aanvangsdatum: benoeming door de vroedschap.    14.0    NaN    NaN
945      945   2423        1    1145.0        1.0        8.0       8.0        11.0     1641.0      NaN        NaN    1644.0                   0          NaN                             Aanvangsdatum: benoeming door de vroedschap.    14.0    NaN    NaN
946      946   2424        1    1145.0        1.0       33.0      16.0        11.0     1634.0     30.0        4.0    1637.0                   0          3.0                     Aanvangsdatum: benoeming door de Staten van Holland.    14.0    NaN    NaN
947      947   2425        1    1145.0        1.0       33.0       9.0         5.0     1647.0     30.0        4.0    1649.0                   0          3.0                                Aanvangsdatum: commissie Staten-Generaal.    14.0    NaN    NaN
2970    2970   3636        1    1145.0       28.0       83.0       NaN         NaN     1626.0      NaN        NaN    1652.0                   1          NaN                                                                     None     NaN    NaN    NaN
9355    9355  12032        1    1145.0        1.0        8.0       2.0         4.0     1652.0      5.0       10.0    1652.0                   0          0.0  Aanvangsdatum: benoeming door de vroedschap. Beëindigd door overlijden.    14.0    0.0    0.0
21752  21752  22872        1    1145.0       90.0       39.0       NaN         NaN     1632.0      5.0       10.0    1652.0                   0          3.0                                               Beëindigd door overlijden.    14.0    0.0    0.0

In [546]:
r[r['idregent']==1145]

      index  idregent geslachtsnaam tussenvoegsel  idadellijketitel  idacademischetitel          voornaam  adel adelspredikaat heerlijkheid heerlijkheid2  geboortejaar  onbepaaldgeboortedatum  overlijdensjaar  onbepaaldoverlijdensdatum                                                                                                                                                                       opmerkingen  opmerkingen2  periode  overlijdensdag  overlijdensmaand
1120   1120      1145     Hoogtwoud          None               1.0                 NaN  Claes Cornelisz.     0           None         None          None           NaN                       0           1652.0                          0  Vroedschap: Bonke geeft 1618 als aanvang in de vroedschap, maar lijkt hem te hebben verward met vader Cornelisz. Claesz. (zie Jaarboek van het Centraal Bureau voor Genealogie).           NaN        1             5.0              10.0

In [549]:
oldids[oldids['id_regent_orig']=='republiek_1145']

       Unnamed: 0 geslachtsnaam_latest geslachtsnaam_oldnew  id_latest  id_regent_orig  id_oldnew         db  idnr
13494       13494            Hoogtwoud            Hoogtwoud    14464.0  republiek_1145    14585.0  republiek  1145

In [544]:
aanst[aanst.persoon_id==1145]

      periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
2350        2      13.0         4.0     1795.0      NaN        NaN       NaN                   0        None     13-04-1795  ...          NaN      NaN      NaN      1145.0   0          0                  0       1                 0            0

[1 rows x 26 columns]

In [528]:
aanstres[aanstres['persoon_id']==5106]

      periode  begindag  beginmaand  beginjaar  einddag  eindmaand  eindjaar  vertegenwoordigend opmerkingen van_als_bekend  ... provincie_id regio_id stand_id  persoon_id  me  republiek  republiek_friezen  batfra  negentiende_eeuw  divperioden
9605        2       2.0        11.0     1852.0      6.0        7.0    1880.0                   0        None     02-11-1852  ...          NaN      NaN      NaN      5106.0   0          0                  0       0                 1            0

[1 rows x 26 columns]

In [507]:
acc = ['begindag', 'beginmaand', 'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend', 'opmerkingen']

In [511]:
print(len(aanstres),len(ares))

28 68

In [ ]:
for i in sample_republiek:
    for k in raw:
        r = raw['regent']

In [ ]:
concordance[concordance['id_latest'].isin(])]

In [ ]:
[raw.loc[raw['id'].isin()]

KeyError: 'id'

In [554]:
connection_string = con['raa_out']
bron = pd.read_sql_table(con=connection_string, table_name='bronregentdetails')

ValueError: Table bronregentdetails not found

In [555]:
import pickle

In [557]:
with open('./extab.pkl','rb') as infile:
    dumped = pickle.load(infile)

In [560]:
for k in dumped:
    print(k)

academische_titel
adellijke_titel
persoon
alias
bron
bron_details
instelling
functie
lokaal
provincie
regio
stand
aanstelling