In [75]:
basedir = './institutionele_toelichtingen/'

In [76]:
import os

In [77]:
flist = [f for f in os.listdir(f'{basedir}') if os.path.splitext(f)[-1]=='.html']

In [78]:
# flist

In [79]:
for f in flist:
    fn,ext = os.path.splitext(f)
    fn = os.path.splitext(fn)[0]
    outfile = fn+'.html'
    os.rename(f'{basedir}/{f}',f'{basedir}/{outfile}')
    print(f'renamed{basedir}/{f} to {basedir}/{outfile}')

renamed./institutionele_toelichtingen//IT_HollandGecRaZuid.html to ./institutionele_toelichtingen//IT_HollandGecRaZuid.html
renamed./institutionele_toelichtingen//IT_UtrechtHof.html to ./institutionele_toelichtingen//IT_UtrechtHof.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocRot.html to ./institutionele_toelichtingen//IT_GeneraliteitVocRot.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdZee.html to ./institutionele_toelichtingen//IT_GeneraliteitAdZee.html
renamed./institutionele_toelichtingen//IT_GeneraliteitRaSta.html to ./institutionele_toelichtingen//IT_GeneraliteitRaSta.html
renamed./institutionele_toelichtingen//IT_GelderlandGedStaVeluwe.html to ./institutionele_toelichtingen//IT_GelderlandGedStaVeluwe.html
renamed./institutionele_toelichtingen//IT_UtrechtGedSta.html to ./institutionele_toelichtingen//IT_UtrechtGedSta.html
renamed./institutionele_toelichtingen//IT_FrieslandGedSta.html to ./institutionele_toelichtingen//IT_FrieslandGedSta.html
renamed./institutionele_toelichtingen//IT_GroningenHof.html to ./institutionele_toelichtingen//IT_GroningenHof.html
renamed./institutionele_toelichtingen//IT_GroningenRekProv.html to ./institutionele_toelichtingen//IT_GroningenRekProv.html
renamed./institutionele_toelichtingen//IT_GeneraliteitWicRot.html to ./institutionele_toelichtingen//IT_GeneraliteitWicRot.html
renamed./institutionele_toelichtingen//IT_ZeelandGecRa.html to ./institutionele_toelichtingen//IT_ZeelandGecRa.html
renamed./institutionele_toelichtingen//IT_GroningenGedSta.html to ./institutionele_toelichtingen//IT_GroningenGedSta.html
renamed./institutionele_toelichtingen//IT_HollandHof.html to ./institutionele_toelichtingen//IT_HollandHof.html
renamed./institutionele_toelichtingen//IT_HollandRekZuid.html to ./institutionele_toelichtingen//IT_HollandRekZuid.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocMid.html to ./institutionele_toelichtingen//IT_GeneraliteitVocMid.html
renamed./institutionele_toelichtingen//IT_HollandHogeRaad.html to ./institutionele_toelichtingen//IT_HollandHogeRaad.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdFries.html to ./institutionele_toelichtingen//IT_GeneraliteitAdFries.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdSup.html to ./institutionele_toelichtingen//IT_GeneraliteitAdSup.html
renamed./institutionele_toelichtingen//IT_ZeelandRekProv.html to ./institutionele_toelichtingen//IT_ZeelandRekProv.html
renamed./institutionele_toelichtingen//IT_GeneraliteitWicMid.html to ./institutionele_toelichtingen//IT_GeneraliteitWicMid.html
renamed./institutionele_toelichtingen//IT_GeneraliteitWicGron.html to ./institutionele_toelichtingen//IT_GeneraliteitWicGron.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocDelft.html to ./institutionele_toelichtingen//IT_GeneraliteitVocDelft.html
renamed./institutionele_toelichtingen//IT_OverijsselGedSta.html to ./institutionele_toelichtingen//IT_OverijsselGedSta.html
renamed./institutionele_toelichtingen//IT_GelderlandHof.html to ./institutionele_toelichtingen//IT_GelderlandHof.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdNoord.html to ./institutionele_toelichtingen//IT_GeneraliteitAdNoord.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdAms.html to ./institutionele_toelichtingen//IT_GeneraliteitAdAms.html
renamed./institutionele_toelichtingen//IT_GeneraliteitWicAms.html to ./institutionele_toelichtingen//IT_GeneraliteitWicAms.html
renamed./institutionele_toelichtingen//IT_HollandRekProv.html to ./institutionele_toelichtingen//IT_HollandRekProv.html
renamed./institutionele_toelichtingen//IT_GelderlandGedStaNijmegen.html to ./institutionele_toelichtingen//IT_GelderlandGedStaNijmegen.html
renamed./institutionele_toelichtingen//IT_HollandRekNoord.html to ./institutionele_toelichtingen//IT_HollandRekNoord.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocAms.html to ./institutionele_toelichtingen//IT_GeneraliteitVocAms.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocEnk.html to ./institutionele_toelichtingen//IT_GeneraliteitVocEnk.html
renamed./institutionele_toelichtingen//IT_GeneraliteitRaVla.html to ./institutionele_toelichtingen//IT_GeneraliteitRaVla.html
renamed./institutionele_toelichtingen//IT_GeneraliteitAdMaze.html to ./institutionele_toelichtingen//IT_GeneraliteitAdMaze.html
renamed./institutionele_toelichtingen//IT_GeneraliteitVocHoorn.html to ./institutionele_toelichtingen//IT_GeneraliteitVocHoorn.html
renamed./institutionele_toelichtingen//IT_UtrechtRekProv.html to ./institutionele_toelichtingen//IT_UtrechtRekProv.html
renamed./institutionele_toelichtingen//IT_FrieslandRekProv.html to ./institutionele_toelichtingen//IT_FrieslandRekProv.html
renamed./institutionele_toelichtingen//IT_GeneraliteitRaBra.html to ./institutionele_toelichtingen//IT_GeneraliteitRaBra.html
renamed./institutionele_toelichtingen//IT_HollandGrafRek.html to ./institutionele_toelichtingen//IT_HollandGrafRek.html
renamed./institutionele_toelichtingen//IT_HollandGecRaNoord.html to ./institutionele_toelichtingen//IT_HollandGecRaNoord.html
renamed./institutionele_toelichtingen//IT_GeneraliteitRek.html to ./institutionele_toelichtingen//IT_GeneraliteitRek.html
renamed./institutionele_toelichtingen//IT_FrieslandHof.html to ./institutionele_toelichtingen//IT_FrieslandHof.html
renamed./institutionele_toelichtingen//IT_GeneraliteitWicNoord.html to ./institutionele_toelichtingen//IT_GeneraliteitWicNoord.html

In [80]:
import pandas as pd

In [81]:
concordance = pd.read_excel('./concordance_files/ident20241126.xlsx')

In [82]:
colleges = pd.read_csv('./mdbdump/rawconvert/college.csv', sep=',')

In [83]:
toelichting_conc = pd.read_excel('./institutionele_toelichtingen/Concordantie_InsitutioneleToelichtingen.xlsx')

In [84]:
colleges.head()

,Unnamed: 0,college_id,college,old_idcollege
0,0,0,Administrateurs de la Loterie Impériale de France,['batfra_269']
1,1,1,Administrateurs der Posterijen,['batfra_250']
2,2,2,Administration Générale des Poudres et Salpêtres,['batfra_173']
3,3,3,Administration des Monnaies,['batfra_203']
4,4,4,Admiraliteit in Friesland (1596-1795),"['divperioden_6', 'republiek_34', 'republiek_f..."

In [85]:
toelichting_conc['toel_id'] = [f'republiek_{tid}' for tid in toelichting_conc['ID in Database'].unique()]

In [86]:
toelichting_conc.head()

,Bestandsnaam Word,Naam in Database,ID in Database,toel_id
0,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19
1,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21
2,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20
3,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163
4,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162

In [87]:
# def pandas_match(patlist=[],df=None,field=''):
#     t_pat = re.compile(r"(%s)" % r")\b|\b(".join(patlist),  flags=re.I|re.U)
#     ps = df[field].str.extract(t_pat)
#     molten = ps.melt(ignore_index=False)
#     result = molten[molten.value.notna()]
#     return result
    
# def merge_pat(patlist=[],df=None,field=''):
#     molten = pandas_match(patlist=patlist,df=df,field=field)
#     result = molten.merge(df, left_on='value', right_on=field)
#     return result

In [88]:
from pandas_matcher import merge_pat as mp

In [89]:
import re

In [90]:
toelichting_conc['tnm'] = toelichting_conc['Bestandsnaam Word'].apply(lambda x:os.path.splitext(x)[0])

In [91]:
toelichting_conc.head()

,Bestandsnaam Word,Naam in Database,ID in Database,toel_id,tnm
0,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19,IT_FrieslandGedSta
1,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21,IT_FrieslandHof
2,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20,IT_FrieslandRekProv
3,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163,IT_GelderlandGedStaNijmegen
4,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162,IT_GelderlandGedStaVeluwe

In [92]:
toelichting_conc.to_json(orient='records')

'[{"Bestandsnaam Word":"IT_FrieslandGedSta.docx","Naam in Database":"Gedeputeerde Staten van Friesland (1577-1795)","ID in Database":19,"toel_id":"republiek_19","tnm":"IT_FrieslandGedSta"},{"Bestandsnaam Word":"IT_FrieslandHof.docx","Naam in Database":"Hof van Friesland (1515-1795)","ID in Database":21,"toel_id":"republiek_21","tnm":"IT_FrieslandHof"},{"Bestandsnaam Word":"IT_FrieslandRekProv.docx","Naam in Database":"Provinciale Rekenkamer van Friesland (1582-1795)","ID in Database":20,"toel_id":"republiek_20","tnm":"IT_FrieslandRekProv"},{"Bestandsnaam Word":"IT_GelderlandGedStaNijmegen.docx","Naam in Database":"Gedeputeerde Staten van het Kwartier Nijmegen (1593-1795)","ID in Database":163,"toel_id":"republiek_163","tnm":"IT_GelderlandGedStaNijmegen"},{"Bestandsnaam Word":"IT_GelderlandGedStaVeluwe.docx","Naam in Database":"Gedeputeerde Staten van het Kwartier Veluwe (1580-1795)","ID in Database":162,"toel_id":"republiek_162","tnm":"IT_GelderlandGedStaVeluwe"},{"Bestandsnaam Word":"IT_GelderlandGedStaZutphen.docx","Naam in Database":"Gedeputeerde Staten van het Graafschap Zutphen (1598-1795)","ID in Database":164,"toel_id":"republiek_164","tnm":"IT_GelderlandGedStaZutphen"},{"Bestandsnaam Word":"IT_GelderlandHof.docx","Naam in Database":"Hof van Gelre en Zutphen (1588-1795)","ID in Database":142,"toel_id":"republiek_142","tnm":"IT_GelderlandHof"},{"Bestandsnaam Word":"IT_GelderlandRekProv.docx","Naam in Database":"Provinciale Rekenkamer van Gelderland (1581-1795)","ID in Database":161,"toel_id":"republiek_161","tnm":"IT_GelderlandRekProv"},{"Bestandsnaam Word":"IT_GeneraliteitAdAms.docx","Naam in Database":"Admiraliteit te Amsterdam (1586-1795)","ID in Database":31,"toel_id":"republiek_31","tnm":"IT_GeneraliteitAdAms"},{"Bestandsnaam Word":"IT_GeneraliteitAdFries.docx","Naam in Database":"Admiraliteit in Friesland (1596-1795)","ID in Database":34,"toel_id":"republiek_34","tnm":"IT_GeneraliteitAdFries"},{"Bestandsnaam Word":"IT_GeneraliteitAdMaze.docx","Naam in Database":"Admiraliteit op de Maze (1586-1795)","ID in Database":30,"toel_id":"republiek_30","tnm":"IT_GeneraliteitAdMaze"},{"Bestandsnaam Word":"IT_GeneraliteitAdNoord.docx","Naam in Database":"Admiraliteit in het Noorderkwartier (1589-1795)","ID in Database":33,"toel_id":"republiek_33","tnm":"IT_GeneraliteitAdNoord"},{"Bestandsnaam Word":"IT_GeneraliteitAdSup.docx","Naam in Database":"College van Superintendentie der Admiralteit (1589-1593)","ID in Database":130,"toel_id":"republiek_130","tnm":"IT_GeneraliteitAdSup"},{"Bestandsnaam Word":"IT_GeneraliteitAdZee.docx","Naam in Database":"Admiraliteit in Zeeland (1584-1795)","ID in Database":32,"toel_id":"republiek_32","tnm":"IT_GeneraliteitAdZee"},{"Bestandsnaam Word":"IT_GeneraliteitRaBra.docx","Naam in Database":"Raad van Brabant (1591-1795)","ID in Database":46,"toel_id":"republiek_46","tnm":"IT_GeneraliteitRaBra"},{"Bestandsnaam Word":"IT_GeneraliteitRaSta.docx","Naam in Database":"Raad van State (1588-1795)","ID in Database":28,"toel_id":"republiek_28","tnm":"IT_GeneraliteitRaSta"},{"Bestandsnaam Word":"IT_GeneraliteitRaVla.docx","Naam in Database":"Raad van Vlaanderen (1599-1795)","ID in Database":47,"toel_id":"republiek_47","tnm":"IT_GeneraliteitRaVla"},{"Bestandsnaam Word":"IT_GeneraliteitRek.docx","Naam in Database":"Generaliteitsrekenkamer (1608-1799)","ID in Database":29,"toel_id":"republiek_29","tnm":"IT_GeneraliteitRek"},{"Bestandsnaam Word":"IT_GeneraliteitStaGe.docx","Naam in Database":"Staten-Generaal der Verenigde Nederlanden (1576-1795)","ID in Database":27,"toel_id":"republiek_27","tnm":"IT_GeneraliteitStaGe"},{"Bestandsnaam Word":"IT_GeneraliteitVocAms.docx","Naam in Database":"VOC ter Kamer Amsterdam","ID in Database":35,"toel_id":"republiek_35","tnm":"IT_GeneraliteitVocAms"},{"Bestandsnaam Word":"IT_GeneraliteitVocDelft.docx","Naam in Database":"VOC ter Kamer Delft","ID in Database":37,"toel_id":"republiek_37","tnm":"IT_GeneraliteitVocDelft"},{"Bestandsnaam Word":"IT_GeneraliteitVocEnk.docx","Naam in Database":"VOC ter Kamer Enkhuizen","ID in Database":40,"toel_id":"republiek_40","tnm":"IT_GeneraliteitVocEnk"},{"Bestandsnaam Word":"IT_GeneraliteitVocHoorn.docx","Naam in Database":"VOC ter Kamer Hoorn","ID in Database":39,"toel_id":"republiek_39","tnm":"IT_GeneraliteitVocHoorn"},{"Bestandsnaam Word":"IT_GeneraliteitVocMid.docx","Naam in Database":"VOC ter Kamer Zeeland","ID in Database":36,"toel_id":"republiek_36","tnm":"IT_GeneraliteitVocMid"},{"Bestandsnaam Word":"IT_GeneraliteitVocRot.docx","Naam in Database":"VOC ter Kamer Rotterdam","ID in Database":38,"toel_id":"republiek_38","tnm":"IT_GeneraliteitVocRot"},{"Bestandsnaam Word":"IT_GeneraliteitWicAms.docx","Naam in Database":"WIC ter Kamer Amsterdam","ID in Database":41,"toel_id":"republiek_41","tnm":"IT_GeneraliteitWicAms"},{"Bestandsnaam Word":"IT_GeneraliteitWicGron.docx","Naam in Database":"WIC ter Kamer Stad en Lande","ID in Database":45,"toel_id":"republiek_45","tnm":"IT_GeneraliteitWicGron"},{"Bestandsnaam Word":"IT_GeneraliteitWicMid.docx","Naam in Database":"WIC ter Kamer Zeeland","ID in Database":42,"toel_id":"republiek_42","tnm":"IT_GeneraliteitWicMid"},{"Bestandsnaam Word":"IT_GeneraliteitWicNoord.docx","Naam in Database":"WIC ter Kamer van het Noorderkwartier","ID in Database":44,"toel_id":"republiek_44","tnm":"IT_GeneraliteitWicNoord"},{"Bestandsnaam Word":"IT_GeneraliteitWicRot.docx","Naam in Database":"WIC ter Kamer op de Maze","ID in Database":43,"toel_id":"republiek_43","tnm":"IT_GeneraliteitWicRot"},{"Bestandsnaam Word":"IT_GroningenGedSta.docx","Naam in Database":"Gedeputeerde Staten van Groningen (1595-1795)","ID in Database":139,"toel_id":"republiek_139","tnm":"IT_GroningenGedSta"},{"Bestandsnaam Word":"IT_GroningenHof.docx","Naam in Database":"Hoofdmannenkamer, vanaf 1749 Hoge Justitiekamer van Groningen (1594-1795)","ID in Database":140,"toel_id":"republiek_140","tnm":"IT_GroningenHof"},{"Bestandsnaam Word":"IT_GroningenRekProv.docx","Naam in Database":"Provinciale Rekenkamer van Groningen (1596-1795)","ID in Database":138,"toel_id":"republiek_138","tnm":"IT_GroningenRekProv"},{"Bestandsnaam Word":"IT_HollandGecRaNoord.docx","Naam in Database":"Gecommitteerde Raden van Holland in het Noorderkwartier (1573-1795)","ID in Database":8,"toel_id":"republiek_8","tnm":"IT_HollandGecRaNoord"},{"Bestandsnaam Word":"IT_HollandGecRaZuid.docx","Naam in Database":"Gecommitteerde Raden van Holland in het Zuiderkwartier (1590-1795)","ID in Database":7,"toel_id":"republiek_7","tnm":"IT_HollandGecRaZuid"},{"Bestandsnaam Word":"IT_HollandGrafRek.docx","Naam in Database":"Grafelijkheidsrekenkamer van Holland (1588-1728)","ID in Database":137,"toel_id":"republiek_137","tnm":"IT_HollandGrafRek"},{"Bestandsnaam Word":"IT_HollandHof.docx","Naam in Database":"Hof van Holland en Zeeland (1572-1795)","ID in Database":13,"toel_id":"republiek_13","tnm":"IT_HollandHof"},{"Bestandsnaam Word":"IT_HollandHogeRaad.docx","Naam in Database":"Hoge Raad van Holland en Zeeland (1582-1795)","ID in Database":12,"toel_id":"republiek_12","tnm":"IT_HollandHogeRaad"},{"Bestandsnaam Word":"IT_HollandRekNoord.docx","Naam in Database":"Rekenkamer ter Auditie van Holland in het Noorderkwartier (1590-1752)","ID in Database":10,"toel_id":"republiek_10","tnm":"IT_HollandRekNoord"},{"Bestandsnaam Word":"IT_HollandRekProv.docx","Naam in Database":"Provinciale Rekenkamer van Holland (1752-1795)","ID in Database":11,"toel_id":"republiek_11","tnm":"IT_HollandRekProv"},{"Bestandsnaam Word":"IT_HollandRekZuid.docx","Naam in Database":"Rekenkamer ter Auditie van Holland in het Zuiderkwartier (1590-1752)","ID in Database":9,"toel_id":"republiek_9","tnm":"IT_HollandRekZuid"},{"Bestandsnaam Word":"IT_OverijsselGedSta.docx","Naam in Database":"Gedeputeerde Staten van Overijssel (1591-1795)","ID in Database":22,"toel_id":"republiek_22","tnm":"IT_OverijsselGedSta"},{"Bestandsnaam Word":"IT_UtrechtGedSta.docx","Naam in Database":"Gedeputeerde Staten van Utrecht (1577-1795)","ID in Database":145,"toel_id":"republiek_145","tnm":"IT_UtrechtGedSta"},{"Bestandsnaam Word":"IT_UtrechtHof.docx","Naam in Database":"Hof van Utrecht (1588-1795)","ID in Database":143,"toel_id":"republiek_143","tnm":"IT_UtrechtHof"},{"Bestandsnaam Word":"IT_UtrechtRekProv.docx","Naam in Database":"Kamer ter Finantie van Utrecht (1663-1795)","ID in Database":144,"toel_id":"republiek_144","tnm":"IT_UtrechtRekProv"},{"Bestandsnaam Word":"IT_ZeelandGecRa.docx","Naam in Database":"Gecommitteerde Raden van Zeeland (1578-1795)","ID in Database":14,"toel_id":"republiek_14","tnm":"IT_ZeelandGecRa"},{"Bestandsnaam Word":"IT_ZeelandRekProv.docx","Naam in Database":"Provinciale Rekenkamer van Zeeland (1596-1795)","ID in Database":15,"toel_id":"republiek_15","tnm":"IT_ZeelandRekProv"}]'

In [93]:
import json
with open('connection.json','r') as infl:
    con = json.load(infl)
    
# connection_string = con['raa_out']

In [94]:
con['toe_dirs']

['./original/brondata/Republiek/Institutionele toelichtingen Republiek/',
 './original/brondata/ME/Institutionele toelichtingen ME/',
 './original/brondata/Negentiende eeuw/Institutionele toelichtingen 19de eeuw/']

In [95]:
from bs4 import BeautifulSoup
toelichtingen = {}
flnms = {}
fllst = [f for f in os.listdir(basedir) if os.path.splitext(f)[-1]=='.html']
for item in fllst:
    nm = os.path.splitext(item)[0]
    knm = nm.split('(')[0].strip()
    lnm = f'{os.path.join(basedir,item)}'
    flnms[nm] = lnm
    with open(os.path.join(basedir,item),encoding='utf8') as infl:
        # print (f'parsing {infl}')
        htmlsource = BeautifulSoup(infl, 'lxml')
        # print(htmlsource)
        toelichting = htmlsource('body')[0].renderContents().strip()
        toelichtingen[knm] = toelichting
        # clgs[nm] = toelichting
        # clgs[knm] = toelichting

In [96]:
toelichting_conc['toelichting'] = toelichting_conc['tnm'].map(toelichtingen)

In [97]:
toelichting_conc

,Bestandsnaam Word,Naam in Database,ID in Database,toel_id,tnm,toelichting
0,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19,IT_FrieslandGedSta,"b'<h1 id=""institutionele-toelichting-gedeputee..."
1,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21,IT_FrieslandHof,"b'<h1 id=""institutionele-toelichting-hof-van-f..."
2,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20,IT_FrieslandRekProv,"b'<h1 id=""institutionele-toelichting-provincia..."
3,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163,IT_GelderlandGedStaNijmegen,"b'<h1 id=""institutionele-toelichting-gedeputee..."
4,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162,IT_GelderlandGedStaVeluwe,"b'<h1 id=""institutionele-toelichting-gedeputee..."
5,IT_GelderlandGedStaZutphen.docx,Gedeputeerde Staten van het Graafschap Zutphen...,164,republiek_164,IT_GelderlandGedStaZutphen,NaN
6,IT_GelderlandHof.docx,Hof van Gelre en Zutphen (1588-1795),142,republiek_142,IT_GelderlandHof,"b'<h1 id=""institutionele-toelichting-hof-van-g..."
7,IT_GelderlandRekProv.docx,Provinciale Rekenkamer van Gelderland (1581-1795),161,republiek_161,IT_GelderlandRekProv,NaN
8,IT_GeneraliteitAdAms.docx,Admiraliteit te Amsterdam (1586-1795),31,republiek_31,IT_GeneraliteitAdAms,"b'<h1 id=""institutionele-toelichting-admiralit..."
9,IT_GeneraliteitAdFries.docx,Admiraliteit in Friesland (1596-1795),34,republiek_34,IT_GeneraliteitAdFries,"b'<h1 id=""institutionele-toelichting-admiralit..."
10,IT_GeneraliteitAdMaze.docx,Admiraliteit op de Maze (1586-1795),30,republiek_30,IT_GeneraliteitAdMaze,"b'<h1 id=""institutionele-toelichting-admiralit..."
11,IT_GeneraliteitAdNoord.docx,Admiraliteit in het Noorderkwartier (1589-1795),33,republiek_33,IT_GeneraliteitAdNoord,"b'<h1 id=""institutionele-toelichting-admiralit..."
12,IT_GeneraliteitAdSup.docx,College van Superintendentie der Admiralteit (...,130,republiek_130,IT_GeneraliteitAdSup,"b'<h1 id=""institutionele-toelichting-college-v..."
13,IT_GeneraliteitAdZee.docx,Admiraliteit in Zeeland (1584-1795),32,republiek_32,IT_GeneraliteitAdZee,"b'<h1 id=""institutionele-toelichting-admiralit..."
14,IT_GeneraliteitRaBra.docx,Raad van Brabant (1591-1795),46,republiek_46,IT_GeneraliteitRaBra,"b'<h1 id=""institutionele-toelichting-raad-van-..."
15,IT_GeneraliteitRaSta.docx,Raad van State (1588-1795),28,republiek_28,IT_GeneraliteitRaSta,"b'<h1 id=""institutionele-toelichting-raad-van-..."
16,IT_GeneraliteitRaVla.docx,Raad van Vlaanderen (1599-1795),47,republiek_47,IT_GeneraliteitRaVla,"b'<h1 id=""institutionele-toelichting-raad-van-..."
17,IT_GeneraliteitRek.docx,Generaliteitsrekenkamer (1608-1799),29,republiek_29,IT_GeneraliteitRek,"b'<h1 id=""institutionele-toelichting-generalit..."
18,IT_GeneraliteitStaGe.docx,Staten-Generaal der Verenigde Nederlanden (157...,27,republiek_27,IT_GeneraliteitStaGe,NaN
19,IT_GeneraliteitVocAms.docx,VOC ter Kamer Amsterdam,35,republiek_35,IT_GeneraliteitVocAms,"b'<h1 id=""institutionele-toelichting-voc-amste..."
20,IT_GeneraliteitVocDelft.docx,VOC ter Kamer Delft,37,republiek_37,IT_GeneraliteitVocDelft,"b'<h1 id=""institutionele-toelichting-voc-delft..."
21,IT_GeneraliteitVocEnk.docx,VOC ter Kamer Enkhuizen,40,republiek_40,IT_GeneraliteitVocEnk,"b'<h1 id=""institutionele-toelichting-voc-enkhu..."
22,IT_GeneraliteitVocHoorn.docx,VOC ter Kamer Hoorn,39,republiek_39,IT_GeneraliteitVocHoorn,"b'<h1 id=""institutionele-toelichting-voc-hoorn..."
23,IT_GeneraliteitVocMid.docx,VOC ter Kamer Zeeland,36,republiek_36,IT_GeneraliteitVocMid,"b'<h1 id=""institutionele-toelichting-voc-midde..."
24,IT_GeneraliteitVocRot.docx,VOC ter Kamer Rotterdam,38,republiek_38,IT_GeneraliteitVocRot,"b'<h1 id=""institutionele-toelichting-voc-rotte..."
25,IT_GeneraliteitWicAms.docx,WIC ter Kamer Amsterdam,41,republiek_41,IT_GeneraliteitWicAms,"b'<h1 id=""institutionele-toelichting-wic-amste..."
26,IT_GeneraliteitWicGron.docx,WIC ter Kamer Stad en Lande,45,republiek_45,IT_GeneraliteitWicGron,"b'<h1 id=""institutionele-toelichting-wic-groni..."
27,IT_GeneraliteitWicMid.docx,WIC ter Kamer Zeeland,42,republiek_42,IT_GeneraliteitWicMid,"b'<h1 id=""institutionele-toelichting-wic-zeela..."
28,IT_GeneraliteitWicNoord.docx,WIC ter Kamer van het Noorderkwartier,44,republiek_44,IT_GeneraliteitWicNoord,"b'<h1 id=""institutionele-toelichting-wic-noord..."
29,IT_GeneraliteitWicRot.docx,WIC ter Kamer op de Maze,43,republiek_43,IT_GeneraliteitWicRot,"b'<h1 id=""institutionele-toelichting-wic-rotte..."
30,IT_GroningenGedSta.docx,Gedeputeerde Staten van Groningen (1595-1795),139,republiek_139,IT_GroningenGedSta,b'<p><strong>Institutionele toelichting Gedepu...
31,IT_GroningenHof.docx,"Hoofdmannenkamer, vanaf 1749 Hoge Justitiekame...",140,republiek_140,IT_GroningenHof,b'<p><strong>Institutionele toelichting Hoofdm...
32,IT_GroningenRekProv.docx,Provinciale Rekenkamer van Groningen (1596-1795),138,republiek_138,IT_GroningenRekProv,b'<p><strong>Institutionele toelichting Provin...
33,IT_HollandGecRaNoord.docx,Gecommitteerde Raden van Holland in het Noorde...,8,republiek_8,IT_HollandGecRaNoord,"b'<h1 id=""institutionele-toelichting-gecommitt..."
34,IT_HollandGecRaZuid.docx,Gecommitteerde Raden van Holland in het Zuider...,7,republiek_7,IT_HollandGecRaZuid,"b'<h1 id=""institutionele-toelichting-gecommitt..."
35,IT_HollandGrafRek.docx,Grafelijkheidsrekenkamer van Holland (1588-1728),137,republiek_137,IT_HollandGrafRek,"b'<h1 id=""institutionele-toelichting-grafelijk..."
36,IT_HollandHof.docx,Hof van Holland en Zeeland (1572-1795),13,republiek_13,IT_HollandHof,b'<p>Institutionele toelichting Hof van Hollan...
37,IT_HollandHogeRaad.docx,Hoge Raad van Holland en Zeeland (1582-1795),12,republiek_12,IT_HollandHogeRaad,b'<p>Institutionele toelichting Hoge Raad van ...
38,IT_HollandRekNoord.docx,Rekenkamer ter Auditie van Holland in het Noor...,10,republiek_10,IT_HollandRekNoord,"b'<h1 id=""institutionele-toelichting-rekenkame..."
39,IT_HollandRekProv.docx,Provinciale Rekenkamer van Holland (1752-1795),11,republiek_11,IT_HollandRekProv,"b'<h1 id=""institutionele-toelichting-provincia..."
40,IT_HollandRekZuid.docx,Rekenkamer ter Auditie van Holland in het Zuid...,9,republiek_9,IT_HollandRekZuid,"b'<h1 id=""institutionele-toelichting-rekenkame..."
41,IT_OverijsselGedSta.docx,Gedeputeerde Staten van Overijssel (1591-1795),22,republiek_22,IT_OverijsselGedSta,"b'<h1 id=""institutionele-toelichting-gedeputee..."
42,IT_UtrechtGedSta.docx,Gedeputeerde Staten van Utrecht (1577-1795),145,republiek_145,IT_UtrechtGedSta,"b'<h1 id=""institutionele-toelichting-gedeputee..."
43,IT_UtrechtHof.docx,Hof van Utrecht (1588-1795),143,republiek_143,IT_UtrechtHof,"b'<h1 id=""institutionele-toelichting-hof-van-u..."
44,IT_UtrechtRekProv.docx,Kamer ter Finantie van Utrecht (1663-1795),144,republiek_144,IT_UtrechtRekProv,"b'<h1 id=""institutionele-toelichting-kamer-van..."
45,IT_ZeelandGecRa.docx,Gecommitteerde Raden van Zeeland (1578-1795),14,republiek_14,IT_ZeelandGecRa,"b'<h1 id=""institutionele-toelichting-gecommitt..."
46,IT_ZeelandRekProv.docx,Provinciale Rekenkamer van Zeeland (1596-1795),15,republiek_15,IT_ZeelandRekProv,"b'<h1 id=""institutionele-toelichting-provincia..."

In [98]:
def kill_trema(x): #
    return x.replace('ë','ë')

In [99]:
colleges.college = colleges.college.apply(kill_trema)

In [100]:
cnms = [nm.split('(')[0].strip() for nm in colleges.college.unique()]
cnms

['Administrateurs de la Loterie Impériale de France',
 'Administrateurs der Posterijen',
 'Administration Générale des Poudres et Salpêtres',
 'Administration des Monnaies',
 'Admiraliteit in Friesland',
 'Admiraliteit in Zeeland',
 'Admiraliteit in het Noorderkwartier',
 'Admiraliteit op de Maze',
 'Admiraliteit te Amsterdam',
 'Agentschap van Buitenlandse Betrekkingen',
 'Agentschap van Financiën',
 'Agentschap van Inwendige Politie en Waterstaat',
 'Agentschap van Justitie',
 'Agentschap van Marine',
 'Agentschap van Nationale Oeconomie',
 'Agentschap van Nationale Opvoeding',
 'Agentschap van Oorlog',
 'Algemeen Bestuur',
 'Algemeen Bestuur van Weldadigheid',
 'Algemene Administratie van de Waterstaat',
 'Algemene Directie der Posterijen',
 'Algemene Rekenkamer',
 'Algemene Secretarie van Staat',
 'Algemene Secretarie van het Uitvoerend Bewind',
 'Amortisatiekas',
 "Archives de l' Empire",
 'Banque de France',
 'Betaalmeester van de Armée',
 "Bureau Statistique de l' Empire",
 'College van Administratie van de Domeinen van Nassau',
 'College van Geëligeerden van Utrecht',
 'College van Superintendentie der Admiraliteit',
 'College van Superintendentie der Admiralteit',
 'Comité tot de Algemene Zaken van het Bondgenootschap te Lande',
 'Comité tot de Oost-Indische Handel en Bezittingen',
 'Comité tot de Zaken van de Koloniën en Bezittingen op de kust van Guinea en in Amerika',
 'Comité tot de Zaken van de Marine',
 'Comité van Algemeen Welzijn, Waakzaamheid en Veiligheid van Zeeland',
 'Comité-Centraal van de Waterstaat',
 'Commissariaat der Franse troepen in soldij der Bataafse Republiek',
 'Commissaris tot de Gecedeerde Landen aan de Bataafse Republiek',
 'Commissaris-Liquidateur van de Pretentiën van Gepreste Schippers',
 'Commissarissen der Bataafse Posterijen',
 'Commissarissen der Nationale Beleenbank',
 'Commissarissen van de Generale Beleenbank',
 'Commissarissen van de Nationale Rekening',
 'Commissarissen van het Uitvoerend Bewind bij de Departementale Besturen',
 'Commissarissen van het Uitvoerend Bewind bij de Departementale Gerechtshoven',
 "Commissie van 's Lands Advocaten",
 'Commissie van Superintendentie der Rivieren',
 'Commissie van Superintendentie over de Waterstaat der Bataafse Republiek',
 'Commissie van Superintendentie van Zeehavens en Zeegaten',
 'Commissie vervangende het Hof van Rekeningen',
 'Commissie voor de Zaken van Holland',
 'Conseil Général de Commerce',
 'Conseil Général des Ponts et Chaussées',
 'Conseil Impérial des Prises',
 "Conseil d' Administration des Postes-Relais",
 "Conseil d' Etat",
 'Conseil de Liquidation à Amsterdam',
 'Conseil des Poids et Mesures',
 'Constituerende Vergadering representerende het Bataafse Volk',
 'Constitutiecommissie van 1796',
 'Constitutiecommissie van 1797',
 'Constitutiecommissie van 1798',
 'Corps Législatif',
 'Cour Impériale en Hollande',
 'Cour de Cassation',
 'Cour des Comptes',
 'Criminele Rechtbank',
 'Departement van Binnenlandse Zaken',
 'Departement van Binnenlandse Zaken, Onderwijs en Waterstaat',
 'Departement van Binnenlandse Zaken, Waterstaat en Publieke Werken',
 'Departement van Buitenlandse Zaken',
 'Departement van Buitenlandse Zaken',
 'Departement van Financiën',
 'Departement van Hervormde Eredienst',
 'Departement van Justitie',
 'Departement van Koloniën',
 'Departement van Koophandel en Koloniën',
 'Departement van Marine',
 'Departement van Marine en Koloniën',
 'Departement van Nationale Nijverheid en Koloniën',
 'Departement van Onderwijs, Kunsten en Wetenschappen',
 'Departement van Ontvangsten',
 'Departement van Oorlog',
 'Departement van Politie',
 'Departement van Politie in de Zuidelijke Nederlanden',
 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën',
 'Departement van Rooms-Katholieke Eredienst',
 'Departement van Waterstaat',
 'Departement van Waterstaat en Publieke Werken',
 'Departement van Waterstaat, Nationale Nijverheid en Koloniën',
 'Departementaal Bestuur van Brabant',
 'Departementaal Bestuur van Brabant',
 'Departementaal Bestuur van Friesland',
 'Departementaal Bestuur van Friesland',
 'Departementaal Bestuur van Gelderland',
 'Departementaal Bestuur van Gelderland',
 'Departementaal Bestuur van Groningen',
 'Departementaal Bestuur van Groningen',
 'Departementaal Bestuur van Holland',
 'Departementaal Bestuur van Holland',
 'Departementaal Bestuur van Overijssel',
 'Departementaal Bestuur van Overijssel',
 'Departementaal Bestuur van Texel',
 'Departementaal Bestuur van Utrecht',
 'Departementaal Bestuur van Utrecht',
 'Departementaal Bestuur van Zeeland',
 'Departementaal Bestuur van Zeeland',
 'Departementaal Bestuur van de Amstel',
 'Departementaal Bestuur van de Delf',
 'Departementaal Bestuur van de Dommel',
 'Departementaal Bestuur van de Eems',
 'Departementaal Bestuur van de Landschap Drenthe',
 'Departementaal Bestuur van de Oude IJssel',
 'Departementaal Bestuur van de Rijn',
 'Departementaal Bestuur van de Schelde en Maas',
 'Departementaal Gerechtshof',
 'Departementaal Gerechtshof van Brabant',
 'Departementaal Gerechtshof van Friesland',
 'Departementaal Gerechtshof van Gelderland',
 'Departementaal Gerechtshof van Groningen',
 'Departementaal Gerechtshof van Holland',
 'Departementaal Gerechtshof van Overijssel',
 'Departementaal Gerechtshof van Utrecht',
 'Departementaal Gerechtshof van Zeeland',
 'Departementaal Gerechtshof van de Oude IJssel',
 'Depot-Generaal van Oorlog',
 'Directeur van de Administratie van Oorlog',
 'Directie van de Landelijke Telegrafische Beseiningen',
 'Directie van de Levantse Handel',
 'Direction Principale des Douanes en Hollande à Amsterdam',
 'Direction Principale des Postes en Hollande à Amsterdam',
 'Direction de la Caisse Centrale à Amsterdam',
 'Direction du Grand Livre de la Dette Public en Hollande',
 "Direction-Générale de l' Enregistrement et des Domaines",
 "Direction-Générale de l' Imprimerie et de la Librairie",
 "Direction-Générale de la Caisse d' Amortissement",
 'Direction-Générale de la Comptabilité des Communes et des Hospices',
 'Direction-Générale de la Police en Hollande',
 'Direction-Générale des Douanes',
 'Direction-Générale des Droits Réunis',
 'Direction-Générale des Forêts',
 'Direction-Générale des Mines',
 'Direction-Générale des Ponts et Chaussées, Navigation intérieure, Ports de Commerce, Phares et Fanaux, et Lignes Télégraphiques.',
 'Direction-Générale des Postes',
 'Direction-Générale des Revues et de la Conscription Militaire',
 'Direction-Générale des Vivres',
 'Directoraat-Generaal van Justitie en Politie',
 'Directoraat-Generaal van Openbaar Onderwijs en Wetenschappen',
 'Directoraat-Generaal van Schone Kunsten',
 'Directoraat-Generaal van Wetenschappen en Kunsten',
 'Directoraat-Generaal van de Posterijen',
 'Directoraat-Generaal van de Publieke Schatkist',
 'Directoraat-Generaal van de Publieke Schuld',
 'Directoraat-Generaal van de Waterstaat',
 'Directoraat-Generaal voor de Zaken van Oorlog',
 'Directoraat-Generaal voor de Zaken van de Indiën, de Koophandel en Koloniën',
 'Drossaard en Raden in de Etstoel',
 'Dépot Général de la Guerre',
 'Eerste Kamer der Staten-Generaal',
 'Eerste Nationale Vergadering, representerende het volk van Nederland',
 'Essayeur-Generaal van de Munt',
 'Financiële Commissie van Holland',
 'Gecommitteerde Raden van Holland in het Noorderkwartier',
 'Gecommitteerde Raden van Holland in het Zuiderkwartier',
 'Gecommitteerde Raden van Zeeland',
 'Gedeputeerd Bestuur van Holland',
 'Gedeputeerde Staten van Drenthe',
 'Gedeputeerde Staten van Friesland',
 'Gedeputeerde Staten van Friesland',
 'Gedeputeerde Staten van Gelderland',
 'Gedeputeerde Staten van Groningen',
 'Gedeputeerde Staten van Groningen',
 'Gedeputeerde Staten van Limburg',
 'Gedeputeerde Staten van Noord-Brabant',
 'Gedeputeerde Staten van Noord-Holland',
 'Gedeputeerde Staten van Overijssel',
 'Gedeputeerde Staten van Overijssel',
 'Gedeputeerde Staten van Utrecht',
 'Gedeputeerde Staten van Utrecht',
 'Gedeputeerde Staten van Zeeland',
 'Gedeputeerde Staten van Zuid-Holland',
 'Gedeputeerde Staten van het Graafschap Zutphen',
 'Gedeputeerde Staten van het Kwartier Nijmegen',
 'Gedeputeerde Staten van het Kwartier Veluwe',
 'Geheime Raad',
 'Gendarmerie Impériale',
 'Generale Directie der Centrale Kas',
 'Generale Directie der Centrale Kas en Nationale Schuld',
 'Generale Directie der Convooien en Licenten',
 'Generale Directie der Directe Belastingen en Posterijen',
 'Generale Directie der In- en Uitgaande Rechten en Indirecte Belastingen',
 'Generale Directie der Indirecte Belastingen',
 'Generale Directie der Indirecte Belastingen en Convooien en Licenten',
 'Generale Directie der Nationale Schuld',
 'Generale Directie der Ontvangsten',
 'Generaliteitsloterij',
 'Generaliteitsmuntkamer',
 'Generaliteitsrekenkamer',
 'Gouvernement-Generaal van Oost-Friesland',
 'Gouvernement-Général des Départements de la Hollande',
 'Gouverneur-Generaal van Indië',
 'Grafelijkheid van Holland',
 'Grafelijkheid van Zeeland',
 'Grafelijkheidsrekenkamer van Holland',
 'Grote Raad',
 'Hof van Friesland',
 'Hof van Friesland',
 'Hof van Gelre en Zutphen',
 'Hof van Gelre en Zutphen',
 'Hof van Holland en Zeeland',
 'Hof van Holland, Zeeland en West-Friesland',
 'Hof van Holland, Zeeland en West-Friesland',
 'Hof van Justitie',
 'Hof van Justitie van Brabant',
 'Hof van Justitie van Gelderland',
 'Hof van Rekeningen van het Koninkrijk Holland',
 'Hof van Utrecht',
 'Hof van Utrecht',
 'Hof van Utrecht',
 'Hoge Militaire Vierschaar',
 'Hoge Militaire Vierschaar',
 'Hoge Militaire Vierschaar in Holland',
 'Hoge Raad',
 'Hoge Raad van Holland en Zeeland',
 'Hoge Zeekrijgsraad',
 'Hoge Zeekrijgsraad',
 'Hoofdadministratie der Domeinen',
 'Hoofdmannenkamer, vanaf 1749 Hoge Justitiekamer van Groningen',
 'Hoog Gerechtshof',
 'Hoog Gerechtshof voor Financiën en Zeezaken',
 'Hoog Heraldiek College',
 'Hoog Keizerlijk Gerechtshof in Holland',
 'Hoog Militair Gerechtshof',
 'Hoog Nationaal Gerechtshof',
 'Imprimerie Impériale',
 'Intendance Générale des Finances',
 "Intendance de l' Intérieur en Hollande",
 'Intendance des Domaines de la Couronne en Hollande',
 'Intermediair Administratief Bestuur van Bataafs Brabant',
 'Intermediair Administratief Bestuur van Friesland',
 'Intermediair Administratief Bestuur van Gelderland',
 'Intermediair Administratief Bestuur van Groningen',
 'Intermediair Administratief Bestuur van Holland',
 'Intermediair Administratief Bestuur van Overijssel',
 'Intermediair Administratief Bestuur van Utrecht',
 'Intermediair Administratief Bestuur van Zeeland',
 'Intermediair Administratief Bestuur van het voormalige gewest Drenthe',
 'Intermediair Bestuur over de Zaken der Koloniën en Bezittingen in Amerika en op de Kust van Guinea',
 'Intermediair Uitvoerend Bewind',
 'Intermediair Wetgevend Lichaam van het Bataafse Volk',
 'Kabinet des Konings',
 'Kabinet van de Koning van Holland',
 'Kamer ter Finantie van Utrecht',
 'Kanselarij graven van Holland en Zeeland',
 'Kanselarij van het Wetgevend Lichaam',
 'Keizer van Frankrijk, Napoleon',
 'Koning van Holland, Lodewijk Napoleon',
 'Koningin van Holland, Hortensia Eugenia',
 'Koninklijke Courant',
 'Koninklijke Orde van Verdiensten',
 'Koninklijke Orde van de Unie',
 'Koninklijke Secretarie',
 'Koninklijke Staatsdrukkerij',
 'Landdrost en Assessoren van Amstelland',
 'Landdrost en Assessoren van Brabant',
 'Landdrost en Assessoren van Drenthe',
 'Landdrost en Assessoren van Friesland',
 'Landdrost en Assessoren van Gelderland',
 'Landdrost en Assessoren van Groningen',
 'Landdrost en Assessoren van Maasland',
 'Landdrost en Assessoren van Oost-Friesland',
 'Landdrost en Assessoren van Overijssel',
 'Landdrost en Assessoren van Utrecht',
 'Landdrost en Assessoren van Zeeland',
 'Landdrost en Kwartierdrosten van Zeeland',
 'Landsadvocaten ter advies van het Staatsbewind',
 'Landsdrukkerij',
 "Lieutenant-Général de l' Empereur en Hollande",
 "Légion d' Honneur",
 "Maître des Requêtes chargé de l' Administration des Polders, Digues et Routes",
 'Maître des Requêtes chargé du Service des Ponts et Chaussées dans les Départements de la Hollande',
 'Ministerie van Binnenlandse Zaken',
 'Ministerie van Binnenlandse Zaken',
 'Ministerie van Buitenlandse Zaken',
 'Ministerie van Eredienst en Binnenlandse Zaken',
 'Ministerie van Financiën',
 'Ministerie van Justitie en Politie',
 'Ministerie van Koophandel en Koloniën',
 'Ministerie van Marine',
 'Ministerie van Marine en Koloniën',
 'Ministerie van Oorlog',
 'Ministerie van Openbare Eredienst',
 'Ministerie van de Waterstaat',
 "Ministère de l' Administration de la Guerre",
 "Ministère de l' Intérieur",
 'Ministère de la Guerre',
 'Ministère de la Justice',
 'Ministère de la Marine et des Colonies',
 'Ministère de la Police Générale',
 'Ministère des Cultes',
 'Ministère des Finances',
 'Ministère des Manufactures et du Commerce',
 'Ministère des Relations Extérieures',
 'Ministère du Trésor Impérial',
 'Mortificatiefonds',
 'Napoleon Louis Koning van Holland',
 'Nationaal Gerechtshof',
 'Nationaal Syndicaat',
 'Nationale Kanselarij',
 'Nationale Rekenkamer',
 'Nationale Rekenkamer',
 'Nationale Rekenkamer',
 'Ommelander Vergadering [onderverdelen in 3 kwartieren]',
 'Ontvanger-Generaal van de Marine',
 'Opperjagermeester',
 'Ordre Impérial de la Réunion',
 'Provinciaal Bestuur van Friesland',
 'Provinciaal Bestuur van Holland',
 'Provinciaal Bestuur van Utrecht',
 'Provinciaal College van Politie, Financie en Algemeen Welzijn van Gelderland',
 'Provinciaal Comité van Holland',
 'Provinciaal Gerechtshof van Drenthe',
 'Provinciaal Gerechtshof van Friesland',
 'Provinciaal Gerechtshof van Gelderland',
 'Provinciaal Gerechtshof van Groningen',
 'Provinciaal Gerechtshof van Holland',
 'Provinciaal Gerechtshof van Limburg',
 'Provinciaal Gerechtshof van Noord-Brabant',
 'Provinciaal Gerechtshof van Noord-Holland',
 'Provinciaal Gerechtshof van Overijssel',
 'Provinciaal Gerechtshof van Utrecht',
 'Provinciaal Gerechtshof van Zeeland',
 'Provinciaal Gerechtshof van Zuid-Holland',
 'Provinciale Rekenkamer van Friesland',
 'Provinciale Rekenkamer van Gelderland',
 'Provinciale Rekenkamer van Groningen',
 'Provinciale Rekenkamer van Holland',
 'Provinciale Rekenkamer van Zeeland',
 'Provinciale Staten van Drenthe',
 'Provinciale Staten van Friesland',
 'Provinciale Staten van Gelderland',
 'Provinciale Staten van Groningen',
 'Provinciale Staten van Holland',
 'Provinciale Staten van Limburg',
 'Provinciale Staten van Noord-Brabant',
 'Provinciale Staten van Noord-Holland',
 'Provinciale Staten van Overijssel',
 'Provinciale Staten van Utrecht',
 'Provinciale Staten van Zeeland',
 'Provinciale Staten van Zuid-Holland',
 'Provisionele Raad van Regentschap van het Koninkrijk Holland',
 'Provisionele Rekenkamer',
 'Provisionele Representanten van het Volk van Bataafs Brabant',
 'Provisionele Representanten van het Volk van Drenthe',
 'Provisionele Representanten van het Volk van Friesland',
 'Provisionele Representanten van het Volk van Holland',
 'Provisionele Representanten van het Volk van Overijssel',
 'Provisionele Representanten van het Volk van Zeeland',
 'Préfecture Maritime de la Hollande',
 "Préfet du Département de l' Ems-Occidental",
 "Préfet du Département de l' Ems-Oriental",
 "Préfet du Département de l' Issel-Supérieur",
 'Préfet du Département de la Frise',
 "Préfet du Département des Bouches-de-l' Escaut",
 "Préfet du Département des Bouches-de-l' Yssel",
 'Préfet du Département des Bouches-de-la-Meuse',
 'Préfet du Département des Bouches-du-Rhin',
 'Préfet du Département du Zuyderzee',
 'Raad der Ministers van de Koning',
 'Raad van Arnhem',
 'Raad van Binnenlandse Zaken',
 'Raad van Brabant',
 'Raad van Brugge',
 'Raad van Deventer',
 'Raad van Doesburg',
 'Raad van Doetinchem',
 'Raad van Elburg',
 'Raad van Financiën',
 'Raad van Financiën in de Landschap Drenthe',
 'Raad van Financiën in het Departement Bataafs Brabant',
 'Raad van Financiën in het Departement Friesland',
 'Raad van Financiën in het Departement Gelderland',
 'Raad van Financiën in het Departement Groningen',
 'Raad van Financiën in het Departement Holland',
 'Raad van Financiën in het Departement Overijssel',
 'Raad van Financiën in het Departement Utrecht',
 'Raad van Financiën in het Departement Zeeland',
 'Raad van Financiën van Stad en Lande',
 'Raad van Groenlo',
 'Raad van Groningen',
 'Raad van Harderwijk',
 'Raad van Hattem',
 'Raad van Judicature over de Middelen te Water en te Lande',
 'Raad van Judicature over de Middelen te Water en te Lande',
 'Raad van Judicature over de Middelen te Water en te Lande',
 'Raad van Judicature voor de Middelen te Water en te Lande in Holland',
 'Raad van Kampen',
 'Raad van Leeuwarden',
 'Raad van Lochem',
 'Raad van Marine',
 'Raad van Mons',
 'Raad van Nijmegen',
 'Raad van Oorlog',
 'Raad van State',
 'Raad van State',
 'Raad van State',
 'Raad van Tiel',
 'Raad van Vlaanderen',
 'Raad van Wageningen',
 'Raad van Zaltbommel',
 'Raad van Zutphen',
 'Raad van Zwolle',
 'Raad van de Amerikaanse Bezittingen en Etablissementen',
 'Raad van de Amerikaanse Koloniën en Bezittingen',
 'Raad van de Aziatische Bezittingen en Etablissementen',
 'Raad van de Aziatische Bezittingen en Etablissementen',
 'Raad/Vroedschap van Utrecht',
 'Raadkamer Gelre',
 'Raadpensionaris',
 'Rekenkamer Gelre',
 'Rekenkamer Holland',
 'Rekenkamer ter Auditie van Holland in het Noorderkwartier',
 'Rekenkamer ter Auditie van Holland in het Zuiderkwartier',
 'Representant van de Eerste Edele in Zeeland',
 'Representanten van het Volk van Utrecht',
 'Representanten van het volk van Bataafs Brabant',
 'Representanten van het volk van Drenthe',
 'Representanten van het volk van Friesland',
 'Representanten van het volk van Stad en Lande',
 'Ridderschap van Holland',
 'Ridderschap van Overijssel',
 'Ridderschap van Utrecht',
 'Ridderschap van het Graafschap Zutphen',
 'Ridderschap van het Kwartier Nijmegen',
 'Ridderschap van het Kwartier Veluwe',
 'Secretarie van het Gouvernement van Holland',
 'Secretarie van het Staatsbewind',
 'Secretaris van Staat Departement van Buitenlandse Zaken',
 'Secretaris van Staat voor de Binnenlandse Zaken',
 'Secretaris van Staat voor de Buitenlandse Betrekkingen',
 'Secretaris van Staat voor de Financiën',
 'Secretaris van Staat voor de Zaken der Marine',
 'Secretaris van Staat voor de Zaken van Oorlog',
 'Secretaris van Staat, Departement van Oorlog',
 "Secrétairerie d' État Impériale",
 'Société Maternelle',
 'Staatsbewind der Bataafse Republiek',
 'Staatsdrukkerij',
 'Staatsraad',
 'Staatsraad',
 'Staatssecretarie',
 'Staatssecretarie',
 'Staten',
 'Staten',
 'Staten',
 'Staten van Friesland',
 'Staten van Friesland',
 'Staten van Holland',
 'Staten van Holland',
 'Staten van Overijssel',
 'Staten van Utrecht',
 'Staten van Zeeland',
 'Staten-Generaal',
 'Staten-Generaal',
 'Staten-Generaal der Verenigde Nederlanden',
 'Staten-Generaal der Verenigde Nederlandse Provinciën',
 'Syndicat de Hollande',
 'Sénat Conservateur',
 'Thesaurier-Generaal en Raden van Financiën',
 'Tweede Kamer der Staten-Generaal',
 'Tweede Nationale Vergadering',
 'Uitvoerend Bewind',
 'Uitvoerend Bewind der Bataafse Republiek',
 'Université Impériale',
 'VOC ter Kamer Amsterdam',
 'VOC ter Kamer Delft',
 'VOC ter Kamer Enkhuizen',
 'VOC ter Kamer Hoorn',
 'VOC ter Kamer Rotterdam',
 'VOC ter Kamer Zeeland',
 'VOC ter kamer Amsterdam',
 'Vergadering van Notabelen',
 'Vertegenwoordigend Lichaam',
 'Vertegenwoordigend Lichaam',
 'Vroedschap van Alkmaar',
 'Vroedschap van Amersfoort',
 'Vroedschap van Amsterdam',
 'Vroedschap van Bolsward',
 'Vroedschap van Delft',
 'Vroedschap van Den Briel',
 'Vroedschap van Dokkum',
 'Vroedschap van Dordrecht',
 'Vroedschap van Edam',
 'Vroedschap van Enkhuizen',
 'Vroedschap van Franeker',
 'Vroedschap van Goes',
 'Vroedschap van Gorinchem',
 'Vroedschap van Gouda',
 'Vroedschap van Haarlem',
 'Vroedschap van Harlingen',
 'Vroedschap van Hindeloopen',
 'Vroedschap van Hoorn',

In [101]:
import os
from bs4 import BeautifulSoup
clgs = {}
for toedir in [d for d in con['toe_dirs'] if 'Republiek' not in d]:
    fllst = os.listdir(toedir)
    for item in fllst:
        item = kill_trema(item)
        nm = os.path.splitext(item)[0]
        knm = nm.split('(')[0].strip()
        if nm in cnms:
            naam = nm
        elif knm in cnms:
            naam = knm
        else:
            print(nm)
            # if nm in ['Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824)',
            #           'Departement van Koloniën (1814-1861)',
            #           'Hoog Gerechtshof (1813-1838)']: #wtf
            #     continue
            # else:
            break
        lnm = f'{os.path.join(basedir,item)}'
        flnms[nm] = lnm
        # print(nm)
        with open(os.path.join(toedir,item),encoding='latin1') as infl:
            htmlsource = BeautifulSoup(infl, 'html.parser')
            toelichting = htmlsource('body')[0].renderContents().strip()

            clgs[nm] = {'filename':lnm,'dbnaam':nm, 'naam':naam,'toelichting':toelichting}
            # clgs[knm] = toelichting

Schive Utrecht (1474-1477)

In [102]:
con_dic = toelichting_conc.to_dict(orient='records')

In [103]:
clgs

{'Raadkamer Gelre (1473-1477)': {'filename': './institutionele_toelichtingen/Raadkamer Gelre (1473-1477).htm',
  'dbnaam': 'Raadkamer Gelre (1473-1477)',
  'naam': 'Raadkamer Gelre',
  'toelichting': b"<h3>Institutionele toelichting Raadkamer Gelre (1473-1477)</h3>\n<p><b>Naam</b>:<br/>\nRaadkamer Gelre; er werd ook van het Hof gesproken en over het gerecht van de Schive.</p>\n<p><b>Datum oprichting</b>:<br/>\nOp 16 juli 1473 werd door hertog Karel van Bourgondi\xc3\xab commissie verleend aan Willem van Egmond als stadhouder-generaal van Gelre en Zutphen. Naast de stadhouder werden justiti\xc3\xable raadkamers ingesteld in Arnhem, Nijmegen, Zutphen, Roermond en Venlo. De competentie van de raadkamers werd door Karel de Stoute vastgelegd in een ordonnantie van 22 april 1474. De Raadkamer te Arnhem was primair bestemd voor het gehele hertogdom Gelre. In de loop van 1473 en 1474 werden de ambtenaren bij deze Raad aangesteld. De raadkamer begon haar werk in september 1473.</p>\n<p><b>Datum opheffing</b>:<br/>\nIn januari 1477 sneuvelde Karel de Stoute bij Nancy, waarna de Bourgondische ambtenaren uit Gelre vluchtten.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nArnhem.</p>\n<p><b>Zetelaantal</b>:<br/>\nDe Raadkamer had tien leden. Naast de president en negen andere raadsheren werd een procureur-generaal aangesteld.</p>\n<p><b>Personeel</b>:<br/>\nAan de Raadkamer waren een griffier, secretarissen en een ontvanger van de exploiten verbonden.</p>\n<p><b>Benoeming</b>:<br/>\nHet benoemingsrecht was voorbehouden aan de vorst.</p>\n<p><b>Naamlijsten</b>:<br/>\n-Maris, J.A., 'De raadkamers of hoven van Karel den Stoute in Gelre en Zutphen, 1473-1477', in <i>Bijdragen en Mededelingen Gelre</i> LVI (1957) 58-61.</p>\n<p><b>Literatuur</b>:<br/>\n-Aalbers, P.G., <i>Justitiae Sacrum. Zeven eeuwen rechtspraak in Arnhem</i> (Utrecht 1998) 105-108.<br/>\n\n-Maris, J.A., 'De raadkamers of hoven van Karel den Stoute in Gelre en Zutphen, 1473-1477', in <i>Bijdragen en Mededelingen Gelre</i> LVI (1957) 45-123.</p>"},
 'Departement van Politie (1813-1818)': {'filename': './institutionele_toelichtingen/Departement van Politie (1813-1818).htm',
  'dbnaam': 'Departement van Politie (1813-1818)',
  'naam': 'Departement van Politie',
  'toelichting': b'<h3>Institutionele toelichting departement van Politie (1813-1818)</h3>\n<p>Zie bij departement van Justitie.</p>'},
 'Departement van Binnenlandse Zaken (1813-1861)': {'filename': './institutionele_toelichtingen/Departement van Binnenlandse Zaken (1813-1861).htm',
  'dbnaam': 'Departement van Binnenlandse Zaken (1813-1861)',
  'naam': 'Departement van Binnenlandse Zaken',
  'toelichting': b"<h3>Institutionele toelichting departement van Binnenlandse Zaken (1813-1861)</h3>\n<p><b>Naam</b>:<br/>\nHet commissariaat-generaal voor de Binnenlandse Zaken werd op 6 april 1814 het secretariaat voor de Binnenlandse Zaken. Op 16 september 1815 werd besloten tot het ministerie van Binnenlandse Zaken. Daarnaast werden vier zelfstandige departementen van Waterstaat en Publieke Werken, Onderwijs, Kunsten en Wetenschappen, Hervormde Erediensten en Rooms-Katholieke Eredienst ingesteld. Met ingang van 1 januari 1820 ontstond als gevolg van hereniging het ministerie van Binnenlandse Zaken, Waterstaat en Publieke Werken, en op 1 april 1824 het ministerie van Binnenlandse Zaken, Onderwijs en Waterstaat. Met ingang van 9 april 1825 werd de naam ministerie van Binnenlandse Zaken.</p>\n<p><b>Datum oprichting</b>:<br/>\nOp 29 november 1813 (<i>Staatsblad</i> 1) besloot het Algemeen Bestuur om een commissaris-generaal aan het hoofd van een departement van Binnenlandse Zaken te stellen.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nTot 1830 afwisselend te 's-Gravenhage en te Brussel, daarna te 's-Gravenhage.</p>\n<p><b>Personeel</b>:<br/>\nAan het hoofd van het departement stond van 1 december 1813 tot 6 april 1814 een commissaris-generaal; daarna een secretaris van staat en sedert 16 september 1815 een minister.<br/>\nFuncties op het departement die zijn opgenomen in dit repertorium: secretaris-generaal (aanvankelijk secretaris), commissaris, administrateur, raadadviseur en referendaris.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe commissaris-generaal van Binnenlandse Zaken werd op 29 november 1813 benoemd door het Algemeen Bestuur en door de souvereine vorst gehandhaafd. Met de invoering van de grondwet op 29 maart 1814 werden de hoofden van de departementen van algemeen bestuur aangesteld door de koning; na de grondwetswijziging van 1848 gebeurde dit op voordracht van een formateur.</p>\n<p><b>Aanvangs- en einddata in het Repertorium</b>:<br/>\nDe aanvangsdatum voor ministers is de datum van aantreden, voorzover bekend of in het k.b. vermeld. Bij ambtenaren is de datum van de besluiten tot benoeming of ontslag gevolgd.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Traktementsregisters Binnenlandse Zaken (2.04.25) nrs. 1-124; Kabinetsarchief Binnenlandse Zaken (2.04.26.02) nr. 275 (dienststaten ambtenaren); Algemene Rekenkamer, Bureau Vaste Posten (2.02.09.04) nrs. 709 en 734.</p>\n<p><b>Naamlijsten</b>:<br/>\n-Ette, A.J.H. van, <i>Onze ministers sinds 1798</i> (Alphen aan den Rijn 1948).<br/>\n\n-<i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> II ('s-Gravenhage 1986) 92-94 [ministers en secretarissen-generaal].<br/>\n\n-<i>Naamlijst van de hoofden der departementen van Algemeen Bestuur, van de ministers van Staat, en van de leden der Staten-Generaal van de Vereenigde Nederlanden en van het Koningrijk der Nederlanden, 1813-1851. Met opgave van den tijd van benoeming en aftreding.</i> Samengest. door H. Tollius Drabbe ('s-Gravenhage 1851).<br/>\n\n-<i>Onze bestuurders in moederland en koloni\xc3\xabn</i> (Leiden 1885).</p>\n<p><b>Literatuur</b>:<br/>\n-Beth, J.C., <i>De departementen van Algemeen Bestuur gedurende het tijdvak 1798-1907</i> (Groningen 1907).<br/>\n\n-Brauw, W.M. de, <i>De departementen van algemeen bestuur in Nederland, sedert de omwenteling van 1795</i> (Utrecht 1864).<br/>\n\n-Dooijeweert-Roth, A.J. van, 'Enige historische aantekeningen over de taak van het departement van Binnenlandse Zaken', in <i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> I ('s-Gravenhage 1986) 29-42.<br/>\n\n-IJsselmuiden, P.G., <i>Binnenlandse Zaken en het ontstaan van de moderne overheidsbureaucratie in Nederland 1813-1940</i> (Kampen 1988).<br/>\n\n-Otten, F.J.M., <i>Gids voor de archieven van de ministeries en de Hoge Colleges van Staat 1813-1940</i> (Den Haag 2004).<br/>\n\n-Ribberink, A.E.M. en H.A.J. van Schie, 'Uit de geschiedenis van Binnenlandse Zaken', in <i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> I ('s-Gravenhage 1986) 11-27.<br/>\n\n-Secker, W.P., <i>Ministers in beeld. De sociale en functionele herkomst van de Nederlandse ministers (1848-1990)</i> (Leiden 1991).</p>"},
 'Hoog Gerechtshof (1813-1838)': {'filename': './institutionele_toelichtingen/Hoog Gerechtshof (1813-1838).htm',
  'dbnaam': 'Hoog Gerechtshof (1813-1838)',
  'naam': 'Hoog Gerechtshof',
  'toelichting': b"<h3>Institutionele toelichting Hoog Gerechtshof (1813-1838)</h3>\n<p><b>Naam</b>:<br/>\nHoog Gerechtshof der Verenigde Nederlanden.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet sb van 1 december 1813 (<i>Staatsblad</i> nr. 3) ontbond het Keizerlijk Gerechtshof en reconstitueerde dit hof tegelijk als Hoog Gerechtshof der Verenigde Nederlanden. Op 3 december 1813 vond de eerste bijeenkomst plaats van het 'nieuwe' college. Bij kb van 25 februari 1817 werd voorzien in de be\xc3\xabdiging van de leden (8 maart legden de leden de eed af).</p>\n<p><b>Datum opheffing</b>:<br/>\nEen kb van 10 april 1838 (<i>Staatsblad</i> nr. 12) bepaalde dat de nieuwe rechterlijke organisatie per 1 oktober 1838 zou gaan functioneren. De laatste bijeenkomst van het Hoog Gerechtshof vond plaats op 29 september 1838.</p>\n<p><b>Vestigingsplaats</b>:<br/>\n's-Gravenhage.</p>\n<p><b>Samenstelling</b>:<br/>\nEr waren vier kamerpresidenten en omtrent dertig raadsheren. Het openbaar ministerie werd gevormd door een procureur-generaal, omtrent tien substituten en drie of vier advocaten-generaal. De substituut-procureurs-generaal waren toegevoegd aan de procureur-generaal bij het Hoog Gerechtshof om dienst te doen bij de Hoven van Assisen, die in de departementen en provincies functioneerden (zij werden als zodanig procureurs-crimineel genoemd). Het Hoog Gerechtshof had een griffier.</p>\n<p><b>Zittingstermijn</b>:<br/>\nDe leden werden voor het leven benoemd.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe raadsheren werden door de koning benoemd. Voor de aanstelling van de griffiers werd op 4 oktober 1824 bepaald dat door het Hoog Gerechtshof een voordracht aan de minister van Justitie en de koning werd gedaan.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe begindatum is de datum dat de benoemde leden de eed aflegden en zitting namen. De einddatum is de datum van overlijden of verlenen van ontslag.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Hoog Gerechtshof (2.09.17) nr. 2 (notulen); nrs. 4-8 (bijlagen notulen); nr. 19 e.v. (juridische benoemingen in alle soorten rechtbanken en functies 1811-1838); nr. 32 (eden); nr. 142 (benoemingsbesluiten rechterlijke ambtenaren 1839, 1845 en 1846 en nog enige daartussenin); nrs. 725-728 (sollicitaties en benoemingen 1825-1838); Justitie (2.09.01) nrs. 5325-5414 (bezoldigingsregisters rechterlijke macht).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Bl\xc3\xa9court, A.S. de, en E.M. Meijers (red.), <i>Memorialen van het Hof (den Raad) van Holland, Zeeland en West-Friesland, van den secretaris Jan Rosa</i> (Haarlem 1929) LXVII-LXXIII (presidenten, raden, procureurs-generaal, advocaten-generaal, griffiers en commiezen-griffiers).<br/>\n\n-Kok, G.Chr., <i>In dienst van het recht. Uit de geschiedenis van het Gerechtshof van 's-Gravenhage en de daaraan voorafgegane hoven (1428-heden)</i> (Hilversum 2005).<br/>\n\n-Boven, Maarten van, de website Rechters in 1811, http://members.home.nl/m.v.boven.</p>\n<p><b>Literatuur</b>:<br/>\n-Kok, G.Chr., <i>In dienst van het recht. Uit de geschiedenis van het Gerechtshof van 's-Gravenhage en de daaraan voorafgegane hoven (1428-heden)</i> (Hilversum 2005).<br/>\n\n-S., 'Hooge Raad en Hof te 's-Gravenhage in de negentiende eeuw', in <i>Van onzen Tijd</i> 16 (1915/1916) 553-561 en 566-568.<br/>\n\n-Vrijland, C.W.D., <i>Die dag was memorabel\xc2\x85 La Cour Imp\xc3\xa9riale en Het Hoog Geregtshof der Vereenigde Nederlanden (1810-1838). Grepen uit de historie</i> (z.pl. [1992]).</p>\n<p><b>Opmerkingen</b>:<br/>\nDe eerste president van het Hoog Gerechtshof werkte, zo werd bij sb van 7 december 1813 bepaald, 'onmiddellijk met den Vorst'. Hij werd niet als hoofd van een departement van Algemeen Bestuur aangemerkt. Dit was met de procureur-generaal van het Hoog Gerechtshof wel het geval, omdat hij het oppertoezicht had over het departement van Politie in de Noordelijke Nederlanden. Nadat op 4 oktober 1815 Van Maanen tot minister van Justitie werd benoemd, werd twee dagen later bepaald dat hij daarnaast eerste president van het Hoog Gerechtshof bleef.</p>"},
 'Algemeen Bestuur (1813)': {'filename': './institutionele_toelichtingen/Algemeen Bestuur (1813).htm',
  'dbnaam': 'Algemeen Bestuur (1813)',
  'naam': 'Algemeen Bestuur',
  'toelichting': b"<h3>Institutionele toelichting Algemeen Bestuur (1813)</h3>\n<p><b>Naam</b>:<br/>\nDe proclamatie van Van Hogendorp en Van der Duyn van Maasdam van 21 november 1813 sprak van het 'Algemeen Bestuur der Vereenigde Nederlanden'.</p>\n<p><b>Datum oprichting</b>:<br/>\nOpgericht bij proclamatie van 21 november 1813.</p>\n<p><b>Datum opheffing</b>:<br/>\nOp 2 december 1813 nam de prins van Oranje de souvereiniteit aan.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nDe proclamatie werd te 's-Gravenhage uitgegeven.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nVan Hogendorp en Van der Duyn van Maasdam riepen zichzelf tot de twee leden van het Algemeen Bestuur uit, in afwachting van de komst van de prins van Oranje.</p>\n<p><b>Literatuur</b>:<br/>\n-Bannier, G.W., <i>Grondwetten van Nederland. Teksten der achtereenvolgende staatsregelingen en grondwetten sedert 1795</i> (Zwolle 1936) 251-255.</p>"},
 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824)': {'filename': './institutionele_toelichtingen/Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824).htm',
  'dbnaam': 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824)',
  'naam': 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën',
  'toelichting': b'<h3>Institutionele toelichting departement van Publiek Onderwijs, Nationale Nijverheid en Koloni\xc3\xabn (1818-1824)</h3>\n<p>Zie bij departement van Koloni\xc3\xabn.</p>'},
 'Gedeputeerde Staten van Utrecht (1814-1861)': {'filename': './institutionele_toelichtingen/Gedeputeerde Staten van Utrecht (1814-1861).htm',
  'dbnaam': 'Gedeputeerde Staten van Utrecht (1814-1861)',
  'naam': 'Gedeputeerde Staten van Utrecht',
  'toelichting': b'<h3>Institutionele toelichting Gedeputeerde Staten van Utrecht (1814-1861)</h3>\n<p><b>Naam</b>:<br/>\nGedeputeerde Staten van Utrecht.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet college werd op 24 oktober 1814 ge\xc3\xafnstalleerd.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nUtrecht.</p>\n<p><b>Zetelaantal</b>:<br/>\n1814-1825: 9.<br/>\n1825-1850: 5.<br/>\nSedert 1850: 6.</p>\n<p><b>Zetelverdeling</b>:<br/>\n1814-1825: ridderschap 3, steden 3, landelijke stand 3.<br/>\n1825-1850: ridderschap 1, steden 1, landelijke stand 1, en 2 naar welgevallen.</p>\n<p><b>Zittingstermijn</b>:<br/>\n1814-1825: drie jaar.<br/>\n1825-1850: zes jaar.<br/>\nSedert 1850: zes jaar.</p>\n<p><b>Rooster van aftreden</b>:<br/>\n1814-1825: jaarlijks trad een derde deel van de leden af, tegelijk met de leden van de Staten.<br/>\n1825-1850: om de twee jaar trad een derde deel van de leden af, tegelijk met de leden van de Staten. Als overgangsregeling gold dat wie in 1825 was gekozen vier jaar lid was en wie in 1826 was gekozen vijf jaar. Daarna trad de volledige termijn van zes jaar in werking. Omdat het aantal gedeputeerden van negen naar vijf ging werd van de drie openvallende plaatsen in 1825 er geen vervuld, waarna in 1826 nog een vacature onvervuld werd gelaten.<br/>\nSedert 1850: om de drie jaar trad de helft van de leden af, op de eerste dinsdag van juli. Verkiezingen na buitengewone vacatures vonden plaats binnen twee maanden na het ontstaan ervan.<br/>\nVoor de gehele periode 1817-1861 volgde de systematiek van het rooster van aftreden bij buitengewone vacatures de zetel, niet de persoon, die derhalve geen volle termijn kreeg.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe eerste bezetting werd door de souvereine vorst benoemd (op voordracht van de gouverneur). Ook in de jaren daarna benoemde de souvereine vorst/koning in geval van vacature. Vanaf 1817 werden de leden van het college van Gedeputeerde Staten door en uit de Provinciale Staten gekozen. De leden werden gekozen door (maar niet per se uit) de standen naar evenredigheid van hun getal. De vertegenwoordiging in standen verdween in 1848 uit de grondwet, en daadwerkelijk met de invoering van de Provinciewet in 1850.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe data zijn genomen uit de traktementsregisters van Binnenlandse Zaken.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Binnenlandse Zaken, traktementsregisters (2.04.25) nrs. 1-12, 73-92 e.v. (benoemings- en ontslagdata).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Beets, A., en W.B. Heins, <i>Inventaris van de archieven van het provinciaal bestuur van Utrecht 1813-1920</i> (Utrecht 1991) 239-240.<br/>\n\n-<i>"Veel tact en de noodige geschiktheid". Gouverneurs en commissarissen in de provincie Utrecht 1814-1997</i>. Onder red. van P.A. Blok e.a. (Utrecht 1997) 218-221 [lijst samengesteld door A.N. Beets].</p>\n<p><b>Literatuur</b>:<br/>\n-Beets, A., en W.B. Heins, inleiding bij <i>Inventaris van de archieven van het provinciaal bestuur van Utrecht 1813-1920</i> (Utrecht 1991).<br/>\n\n-Zie ook bij Provinciale Staten van Utrecht.</p>\n<p><b>Opmerking</b>:\nWie geen lid der Provinciale Staten meer was, was ook geen lid van Gedeputeerde Staten meer. </p>'},
 'Gedeputeerde Staten van Overijssel (1814-1861)': {'filename': './institutionele_toelichtingen/Gedeputeerde Staten van Overijssel (1814-1861).htm',
  'dbnaam': 'Gedeputeerde Staten van Overijssel (1814-1861)',
  'naam': 'Gedeputeerde Staten van Overijssel',
  'toelichting': b"<h3>Institutionele toelichting Gedeputeerde Staten van Overijssel (1814-1861)</h3>\n<p><b>Naam</b>:<br/>\nGedeputeerde Staten van Overijssel.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet college werd op 6 oktober 1814 ge\xc3\xafnstalleerd.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nZwolle.</p>\n<p><b>Zetelaantal</b>:<br/>\n1814-1825: 9.<br/>\n1825-1850: 7.<br/>\nSedert 1850: 6.</p>\n<p><b>Zetelverdeling</b>:<br/>\n1814-1825: ridderschap 3, steden 3, landelijke stand 3.<br/>\n1825-1850: ridderschap 2, steden 2, landelijke stand 2, en 1 naar welgevallen uit een der standen.</p>\n<p><b>Zittingstermijn</b>:<br/>\n1814-1825: drie jaar.<br/>\n1825-1850: zes jaar.<br/>\nSedert 1850: zes jaar.</p>\n<p><b>Rooster van aftreden</b>:<br/>\n1814-1825: jaarlijks trad een derde deel van de leden af, tegelijk met de leden van de Staten.<br/>\n1825-1850: om de twee jaar trad een derde deel van de leden af, tegelijk met de leden van de Staten. Als overgangsregeling gold dat wie in 1825 was gekozen vier jaar lid was en wie in 1826 was gekozen vijf jaar. Daarna trad de volledige termijn van zes jaar in werking. Omdat het aantal gedeputeerden van negen naar zeven ging werd van de drie openvallende plaatsen in 1825 er slechts een vervuld.<br/>\nSedert 1850: om de drie jaar trad de helft van de leden af, op de eerste dinsdag van juli. Verkiezingen na buitengewone vacatures vonden plaats binnen twee maanden na het ontstaan ervan.<br/>\nVoor de gehele periode 1817-1861 volgde de systematiek van het rooster van aftreden bij buitengewone vacatures de zetel, niet de persoon, die derhalve geen volle termijn kreeg.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe eerste bezetting werd door de souvereine vorst benoemd (op voordracht van de gouverneur). Ook in de jaren daarna benoemde de souvereine vorst/koning in geval van vacature. Vanaf 1817 werden de leden van het college van Gedeputeerde Staten door en uit de Provinciale Staten gekozen. De leden werden gekozen door (maar niet per se uit) de standen naar evenredigheid van hun getal. De vertegenwoordiging in standen verdween in 1848 uit de grondwet, en daadwerkelijk met de invoering van de Provinciewet in 1850.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe data zijn genomen uit de traktementsregisters van Binnenlandse Zaken.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Binnenlandse Zaken, traktementsregisters (2.04.25) nrs. 1-12, 73-92 e.v. (benoemings- en ontslagdata).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Heel, Caspar van, <i>400 jaar gedeputeerde staten van Overijssel (Zwolle 1993)</i> 72-74 en 82-83 [gedeputeerden en griffiers].<br/>\n\n-Heel, Caspar van, 'Lijst van provinciale bestuurders, 1813-heden', in <i>Overijssels Contactbericht</i> 10, nr. 1 (maart 1984) 34-42 [gedeputeerden en griffiers].<br/>\n\n-Wigger, J.H., en J. Folkerts, <i>Inventaris van de archieven van het provinciaal bestuur van Overijssel 1813-1920/1948</i> (2 dln.; Zwolle 1994) lxii-lxx [gedeputeerden en griffiers].</p>\n<p><b>Literatuur</b>:<br/>\n-Heel, Caspar van, <i>400 jaar gedeputeerde staten van Overijssel</i> (Zwolle 1993).<br/>\n\n-Wigger, J.H., en J. Folkerts, Inventaris van de archieven van het provinciaal bestuur van Overijssel 1813-1920/1948 (2 dln.; Zwolle 1994).<br/>\n\n-Zie ook bij Provinciale Staten van Overijssel.</p>\n<p><b>Opmerking</b>:<br/>\nWie geen lid der Provinciale Staten meer was, was ook geen lid van Gedeputeerde Staten meer.</p>"},

In [104]:
for r in con_dic:
    clgs[r['Naam in Database']] = {'dbnaam':r['Naam in Database'],
                      'filename':f"{basedir}/{r['tnm']}.html",
                      'toelichting':r['toelichting']}

In [105]:
clgs

{'Raadkamer Gelre (1473-1477)': {'filename': './institutionele_toelichtingen/Raadkamer Gelre (1473-1477).htm',
  'dbnaam': 'Raadkamer Gelre (1473-1477)',
  'naam': 'Raadkamer Gelre',
  'toelichting': b"<h3>Institutionele toelichting Raadkamer Gelre (1473-1477)</h3>\n<p><b>Naam</b>:<br/>\nRaadkamer Gelre; er werd ook van het Hof gesproken en over het gerecht van de Schive.</p>\n<p><b>Datum oprichting</b>:<br/>\nOp 16 juli 1473 werd door hertog Karel van Bourgondi\xc3\xab commissie verleend aan Willem van Egmond als stadhouder-generaal van Gelre en Zutphen. Naast de stadhouder werden justiti\xc3\xable raadkamers ingesteld in Arnhem, Nijmegen, Zutphen, Roermond en Venlo. De competentie van de raadkamers werd door Karel de Stoute vastgelegd in een ordonnantie van 22 april 1474. De Raadkamer te Arnhem was primair bestemd voor het gehele hertogdom Gelre. In de loop van 1473 en 1474 werden de ambtenaren bij deze Raad aangesteld. De raadkamer begon haar werk in september 1473.</p>\n<p><b>Datum opheffing</b>:<br/>\nIn januari 1477 sneuvelde Karel de Stoute bij Nancy, waarna de Bourgondische ambtenaren uit Gelre vluchtten.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nArnhem.</p>\n<p><b>Zetelaantal</b>:<br/>\nDe Raadkamer had tien leden. Naast de president en negen andere raadsheren werd een procureur-generaal aangesteld.</p>\n<p><b>Personeel</b>:<br/>\nAan de Raadkamer waren een griffier, secretarissen en een ontvanger van de exploiten verbonden.</p>\n<p><b>Benoeming</b>:<br/>\nHet benoemingsrecht was voorbehouden aan de vorst.</p>\n<p><b>Naamlijsten</b>:<br/>\n-Maris, J.A., 'De raadkamers of hoven van Karel den Stoute in Gelre en Zutphen, 1473-1477', in <i>Bijdragen en Mededelingen Gelre</i> LVI (1957) 58-61.</p>\n<p><b>Literatuur</b>:<br/>\n-Aalbers, P.G., <i>Justitiae Sacrum. Zeven eeuwen rechtspraak in Arnhem</i> (Utrecht 1998) 105-108.<br/>\n\n-Maris, J.A., 'De raadkamers of hoven van Karel den Stoute in Gelre en Zutphen, 1473-1477', in <i>Bijdragen en Mededelingen Gelre</i> LVI (1957) 45-123.</p>"},
 'Departement van Politie (1813-1818)': {'filename': './institutionele_toelichtingen/Departement van Politie (1813-1818).htm',
  'dbnaam': 'Departement van Politie (1813-1818)',
  'naam': 'Departement van Politie',
  'toelichting': b'<h3>Institutionele toelichting departement van Politie (1813-1818)</h3>\n<p>Zie bij departement van Justitie.</p>'},
 'Departement van Binnenlandse Zaken (1813-1861)': {'filename': './institutionele_toelichtingen/Departement van Binnenlandse Zaken (1813-1861).htm',
  'dbnaam': 'Departement van Binnenlandse Zaken (1813-1861)',
  'naam': 'Departement van Binnenlandse Zaken',
  'toelichting': b"<h3>Institutionele toelichting departement van Binnenlandse Zaken (1813-1861)</h3>\n<p><b>Naam</b>:<br/>\nHet commissariaat-generaal voor de Binnenlandse Zaken werd op 6 april 1814 het secretariaat voor de Binnenlandse Zaken. Op 16 september 1815 werd besloten tot het ministerie van Binnenlandse Zaken. Daarnaast werden vier zelfstandige departementen van Waterstaat en Publieke Werken, Onderwijs, Kunsten en Wetenschappen, Hervormde Erediensten en Rooms-Katholieke Eredienst ingesteld. Met ingang van 1 januari 1820 ontstond als gevolg van hereniging het ministerie van Binnenlandse Zaken, Waterstaat en Publieke Werken, en op 1 april 1824 het ministerie van Binnenlandse Zaken, Onderwijs en Waterstaat. Met ingang van 9 april 1825 werd de naam ministerie van Binnenlandse Zaken.</p>\n<p><b>Datum oprichting</b>:<br/>\nOp 29 november 1813 (<i>Staatsblad</i> 1) besloot het Algemeen Bestuur om een commissaris-generaal aan het hoofd van een departement van Binnenlandse Zaken te stellen.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nTot 1830 afwisselend te 's-Gravenhage en te Brussel, daarna te 's-Gravenhage.</p>\n<p><b>Personeel</b>:<br/>\nAan het hoofd van het departement stond van 1 december 1813 tot 6 april 1814 een commissaris-generaal; daarna een secretaris van staat en sedert 16 september 1815 een minister.<br/>\nFuncties op het departement die zijn opgenomen in dit repertorium: secretaris-generaal (aanvankelijk secretaris), commissaris, administrateur, raadadviseur en referendaris.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe commissaris-generaal van Binnenlandse Zaken werd op 29 november 1813 benoemd door het Algemeen Bestuur en door de souvereine vorst gehandhaafd. Met de invoering van de grondwet op 29 maart 1814 werden de hoofden van de departementen van algemeen bestuur aangesteld door de koning; na de grondwetswijziging van 1848 gebeurde dit op voordracht van een formateur.</p>\n<p><b>Aanvangs- en einddata in het Repertorium</b>:<br/>\nDe aanvangsdatum voor ministers is de datum van aantreden, voorzover bekend of in het k.b. vermeld. Bij ambtenaren is de datum van de besluiten tot benoeming of ontslag gevolgd.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Traktementsregisters Binnenlandse Zaken (2.04.25) nrs. 1-124; Kabinetsarchief Binnenlandse Zaken (2.04.26.02) nr. 275 (dienststaten ambtenaren); Algemene Rekenkamer, Bureau Vaste Posten (2.02.09.04) nrs. 709 en 734.</p>\n<p><b>Naamlijsten</b>:<br/>\n-Ette, A.J.H. van, <i>Onze ministers sinds 1798</i> (Alphen aan den Rijn 1948).<br/>\n\n-<i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> II ('s-Gravenhage 1986) 92-94 [ministers en secretarissen-generaal].<br/>\n\n-<i>Naamlijst van de hoofden der departementen van Algemeen Bestuur, van de ministers van Staat, en van de leden der Staten-Generaal van de Vereenigde Nederlanden en van het Koningrijk der Nederlanden, 1813-1851. Met opgave van den tijd van benoeming en aftreding.</i> Samengest. door H. Tollius Drabbe ('s-Gravenhage 1851).<br/>\n\n-<i>Onze bestuurders in moederland en koloni\xc3\xabn</i> (Leiden 1885).</p>\n<p><b>Literatuur</b>:<br/>\n-Beth, J.C., <i>De departementen van Algemeen Bestuur gedurende het tijdvak 1798-1907</i> (Groningen 1907).<br/>\n\n-Brauw, W.M. de, <i>De departementen van algemeen bestuur in Nederland, sedert de omwenteling van 1795</i> (Utrecht 1864).<br/>\n\n-Dooijeweert-Roth, A.J. van, 'Enige historische aantekeningen over de taak van het departement van Binnenlandse Zaken', in <i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> I ('s-Gravenhage 1986) 29-42.<br/>\n\n-IJsselmuiden, P.G., <i>Binnenlandse Zaken en het ontstaan van de moderne overheidsbureaucratie in Nederland 1813-1940</i> (Kampen 1988).<br/>\n\n-Otten, F.J.M., <i>Gids voor de archieven van de ministeries en de Hoge Colleges van Staat 1813-1940</i> (Den Haag 2004).<br/>\n\n-Ribberink, A.E.M. en H.A.J. van Schie, 'Uit de geschiedenis van Binnenlandse Zaken', in <i>Fragmenten. Uit de geschiedenis van Binnenlandse Zaken</i> I ('s-Gravenhage 1986) 11-27.<br/>\n\n-Secker, W.P., <i>Ministers in beeld. De sociale en functionele herkomst van de Nederlandse ministers (1848-1990)</i> (Leiden 1991).</p>"},
 'Hoog Gerechtshof (1813-1838)': {'filename': './institutionele_toelichtingen/Hoog Gerechtshof (1813-1838).htm',
  'dbnaam': 'Hoog Gerechtshof (1813-1838)',
  'naam': 'Hoog Gerechtshof',
  'toelichting': b"<h3>Institutionele toelichting Hoog Gerechtshof (1813-1838)</h3>\n<p><b>Naam</b>:<br/>\nHoog Gerechtshof der Verenigde Nederlanden.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet sb van 1 december 1813 (<i>Staatsblad</i> nr. 3) ontbond het Keizerlijk Gerechtshof en reconstitueerde dit hof tegelijk als Hoog Gerechtshof der Verenigde Nederlanden. Op 3 december 1813 vond de eerste bijeenkomst plaats van het 'nieuwe' college. Bij kb van 25 februari 1817 werd voorzien in de be\xc3\xabdiging van de leden (8 maart legden de leden de eed af).</p>\n<p><b>Datum opheffing</b>:<br/>\nEen kb van 10 april 1838 (<i>Staatsblad</i> nr. 12) bepaalde dat de nieuwe rechterlijke organisatie per 1 oktober 1838 zou gaan functioneren. De laatste bijeenkomst van het Hoog Gerechtshof vond plaats op 29 september 1838.</p>\n<p><b>Vestigingsplaats</b>:<br/>\n's-Gravenhage.</p>\n<p><b>Samenstelling</b>:<br/>\nEr waren vier kamerpresidenten en omtrent dertig raadsheren. Het openbaar ministerie werd gevormd door een procureur-generaal, omtrent tien substituten en drie of vier advocaten-generaal. De substituut-procureurs-generaal waren toegevoegd aan de procureur-generaal bij het Hoog Gerechtshof om dienst te doen bij de Hoven van Assisen, die in de departementen en provincies functioneerden (zij werden als zodanig procureurs-crimineel genoemd). Het Hoog Gerechtshof had een griffier.</p>\n<p><b>Zittingstermijn</b>:<br/>\nDe leden werden voor het leven benoemd.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe raadsheren werden door de koning benoemd. Voor de aanstelling van de griffiers werd op 4 oktober 1824 bepaald dat door het Hoog Gerechtshof een voordracht aan de minister van Justitie en de koning werd gedaan.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe begindatum is de datum dat de benoemde leden de eed aflegden en zitting namen. De einddatum is de datum van overlijden of verlenen van ontslag.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Hoog Gerechtshof (2.09.17) nr. 2 (notulen); nrs. 4-8 (bijlagen notulen); nr. 19 e.v. (juridische benoemingen in alle soorten rechtbanken en functies 1811-1838); nr. 32 (eden); nr. 142 (benoemingsbesluiten rechterlijke ambtenaren 1839, 1845 en 1846 en nog enige daartussenin); nrs. 725-728 (sollicitaties en benoemingen 1825-1838); Justitie (2.09.01) nrs. 5325-5414 (bezoldigingsregisters rechterlijke macht).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Bl\xc3\xa9court, A.S. de, en E.M. Meijers (red.), <i>Memorialen van het Hof (den Raad) van Holland, Zeeland en West-Friesland, van den secretaris Jan Rosa</i> (Haarlem 1929) LXVII-LXXIII (presidenten, raden, procureurs-generaal, advocaten-generaal, griffiers en commiezen-griffiers).<br/>\n\n-Kok, G.Chr., <i>In dienst van het recht. Uit de geschiedenis van het Gerechtshof van 's-Gravenhage en de daaraan voorafgegane hoven (1428-heden)</i> (Hilversum 2005).<br/>\n\n-Boven, Maarten van, de website Rechters in 1811, http://members.home.nl/m.v.boven.</p>\n<p><b>Literatuur</b>:<br/>\n-Kok, G.Chr., <i>In dienst van het recht. Uit de geschiedenis van het Gerechtshof van 's-Gravenhage en de daaraan voorafgegane hoven (1428-heden)</i> (Hilversum 2005).<br/>\n\n-S., 'Hooge Raad en Hof te 's-Gravenhage in de negentiende eeuw', in <i>Van onzen Tijd</i> 16 (1915/1916) 553-561 en 566-568.<br/>\n\n-Vrijland, C.W.D., <i>Die dag was memorabel\xc2\x85 La Cour Imp\xc3\xa9riale en Het Hoog Geregtshof der Vereenigde Nederlanden (1810-1838). Grepen uit de historie</i> (z.pl. [1992]).</p>\n<p><b>Opmerkingen</b>:<br/>\nDe eerste president van het Hoog Gerechtshof werkte, zo werd bij sb van 7 december 1813 bepaald, 'onmiddellijk met den Vorst'. Hij werd niet als hoofd van een departement van Algemeen Bestuur aangemerkt. Dit was met de procureur-generaal van het Hoog Gerechtshof wel het geval, omdat hij het oppertoezicht had over het departement van Politie in de Noordelijke Nederlanden. Nadat op 4 oktober 1815 Van Maanen tot minister van Justitie werd benoemd, werd twee dagen later bepaald dat hij daarnaast eerste president van het Hoog Gerechtshof bleef.</p>"},
 'Algemeen Bestuur (1813)': {'filename': './institutionele_toelichtingen/Algemeen Bestuur (1813).htm',
  'dbnaam': 'Algemeen Bestuur (1813)',
  'naam': 'Algemeen Bestuur',
  'toelichting': b"<h3>Institutionele toelichting Algemeen Bestuur (1813)</h3>\n<p><b>Naam</b>:<br/>\nDe proclamatie van Van Hogendorp en Van der Duyn van Maasdam van 21 november 1813 sprak van het 'Algemeen Bestuur der Vereenigde Nederlanden'.</p>\n<p><b>Datum oprichting</b>:<br/>\nOpgericht bij proclamatie van 21 november 1813.</p>\n<p><b>Datum opheffing</b>:<br/>\nOp 2 december 1813 nam de prins van Oranje de souvereiniteit aan.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nDe proclamatie werd te 's-Gravenhage uitgegeven.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nVan Hogendorp en Van der Duyn van Maasdam riepen zichzelf tot de twee leden van het Algemeen Bestuur uit, in afwachting van de komst van de prins van Oranje.</p>\n<p><b>Literatuur</b>:<br/>\n-Bannier, G.W., <i>Grondwetten van Nederland. Teksten der achtereenvolgende staatsregelingen en grondwetten sedert 1795</i> (Zwolle 1936) 251-255.</p>"},
 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824)': {'filename': './institutionele_toelichtingen/Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824).htm',
  'dbnaam': 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën (1818-1824)',
  'naam': 'Departement van Publiek Onderwijs, Nationale Nijverheid en Koloniën',
  'toelichting': b'<h3>Institutionele toelichting departement van Publiek Onderwijs, Nationale Nijverheid en Koloni\xc3\xabn (1818-1824)</h3>\n<p>Zie bij departement van Koloni\xc3\xabn.</p>'},
 'Gedeputeerde Staten van Utrecht (1814-1861)': {'filename': './institutionele_toelichtingen/Gedeputeerde Staten van Utrecht (1814-1861).htm',
  'dbnaam': 'Gedeputeerde Staten van Utrecht (1814-1861)',
  'naam': 'Gedeputeerde Staten van Utrecht',
  'toelichting': b'<h3>Institutionele toelichting Gedeputeerde Staten van Utrecht (1814-1861)</h3>\n<p><b>Naam</b>:<br/>\nGedeputeerde Staten van Utrecht.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet college werd op 24 oktober 1814 ge\xc3\xafnstalleerd.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nUtrecht.</p>\n<p><b>Zetelaantal</b>:<br/>\n1814-1825: 9.<br/>\n1825-1850: 5.<br/>\nSedert 1850: 6.</p>\n<p><b>Zetelverdeling</b>:<br/>\n1814-1825: ridderschap 3, steden 3, landelijke stand 3.<br/>\n1825-1850: ridderschap 1, steden 1, landelijke stand 1, en 2 naar welgevallen.</p>\n<p><b>Zittingstermijn</b>:<br/>\n1814-1825: drie jaar.<br/>\n1825-1850: zes jaar.<br/>\nSedert 1850: zes jaar.</p>\n<p><b>Rooster van aftreden</b>:<br/>\n1814-1825: jaarlijks trad een derde deel van de leden af, tegelijk met de leden van de Staten.<br/>\n1825-1850: om de twee jaar trad een derde deel van de leden af, tegelijk met de leden van de Staten. Als overgangsregeling gold dat wie in 1825 was gekozen vier jaar lid was en wie in 1826 was gekozen vijf jaar. Daarna trad de volledige termijn van zes jaar in werking. Omdat het aantal gedeputeerden van negen naar vijf ging werd van de drie openvallende plaatsen in 1825 er geen vervuld, waarna in 1826 nog een vacature onvervuld werd gelaten.<br/>\nSedert 1850: om de drie jaar trad de helft van de leden af, op de eerste dinsdag van juli. Verkiezingen na buitengewone vacatures vonden plaats binnen twee maanden na het ontstaan ervan.<br/>\nVoor de gehele periode 1817-1861 volgde de systematiek van het rooster van aftreden bij buitengewone vacatures de zetel, niet de persoon, die derhalve geen volle termijn kreeg.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe eerste bezetting werd door de souvereine vorst benoemd (op voordracht van de gouverneur). Ook in de jaren daarna benoemde de souvereine vorst/koning in geval van vacature. Vanaf 1817 werden de leden van het college van Gedeputeerde Staten door en uit de Provinciale Staten gekozen. De leden werden gekozen door (maar niet per se uit) de standen naar evenredigheid van hun getal. De vertegenwoordiging in standen verdween in 1848 uit de grondwet, en daadwerkelijk met de invoering van de Provinciewet in 1850.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe data zijn genomen uit de traktementsregisters van Binnenlandse Zaken.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Binnenlandse Zaken, traktementsregisters (2.04.25) nrs. 1-12, 73-92 e.v. (benoemings- en ontslagdata).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Beets, A., en W.B. Heins, <i>Inventaris van de archieven van het provinciaal bestuur van Utrecht 1813-1920</i> (Utrecht 1991) 239-240.<br/>\n\n-<i>"Veel tact en de noodige geschiktheid". Gouverneurs en commissarissen in de provincie Utrecht 1814-1997</i>. Onder red. van P.A. Blok e.a. (Utrecht 1997) 218-221 [lijst samengesteld door A.N. Beets].</p>\n<p><b>Literatuur</b>:<br/>\n-Beets, A., en W.B. Heins, inleiding bij <i>Inventaris van de archieven van het provinciaal bestuur van Utrecht 1813-1920</i> (Utrecht 1991).<br/>\n\n-Zie ook bij Provinciale Staten van Utrecht.</p>\n<p><b>Opmerking</b>:\nWie geen lid der Provinciale Staten meer was, was ook geen lid van Gedeputeerde Staten meer. </p>'},
 'Gedeputeerde Staten van Overijssel (1814-1861)': {'filename': './institutionele_toelichtingen/Gedeputeerde Staten van Overijssel (1814-1861).htm',
  'dbnaam': 'Gedeputeerde Staten van Overijssel (1814-1861)',
  'naam': 'Gedeputeerde Staten van Overijssel',
  'toelichting': b"<h3>Institutionele toelichting Gedeputeerde Staten van Overijssel (1814-1861)</h3>\n<p><b>Naam</b>:<br/>\nGedeputeerde Staten van Overijssel.</p>\n<p><b>Datum oprichting</b>:<br/>\nHet college werd op 6 oktober 1814 ge\xc3\xafnstalleerd.</p>\n<p><b>Vestigingsplaats</b>:<br/>\nZwolle.</p>\n<p><b>Zetelaantal</b>:<br/>\n1814-1825: 9.<br/>\n1825-1850: 7.<br/>\nSedert 1850: 6.</p>\n<p><b>Zetelverdeling</b>:<br/>\n1814-1825: ridderschap 3, steden 3, landelijke stand 3.<br/>\n1825-1850: ridderschap 2, steden 2, landelijke stand 2, en 1 naar welgevallen uit een der standen.</p>\n<p><b>Zittingstermijn</b>:<br/>\n1814-1825: drie jaar.<br/>\n1825-1850: zes jaar.<br/>\nSedert 1850: zes jaar.</p>\n<p><b>Rooster van aftreden</b>:<br/>\n1814-1825: jaarlijks trad een derde deel van de leden af, tegelijk met de leden van de Staten.<br/>\n1825-1850: om de twee jaar trad een derde deel van de leden af, tegelijk met de leden van de Staten. Als overgangsregeling gold dat wie in 1825 was gekozen vier jaar lid was en wie in 1826 was gekozen vijf jaar. Daarna trad de volledige termijn van zes jaar in werking. Omdat het aantal gedeputeerden van negen naar zeven ging werd van de drie openvallende plaatsen in 1825 er slechts een vervuld.<br/>\nSedert 1850: om de drie jaar trad de helft van de leden af, op de eerste dinsdag van juli. Verkiezingen na buitengewone vacatures vonden plaats binnen twee maanden na het ontstaan ervan.<br/>\nVoor de gehele periode 1817-1861 volgde de systematiek van het rooster van aftreden bij buitengewone vacatures de zetel, niet de persoon, die derhalve geen volle termijn kreeg.</p>\n<p><b>Benoeming/verkiezing</b>:<br/>\nDe eerste bezetting werd door de souvereine vorst benoemd (op voordracht van de gouverneur). Ook in de jaren daarna benoemde de souvereine vorst/koning in geval van vacature. Vanaf 1817 werden de leden van het college van Gedeputeerde Staten door en uit de Provinciale Staten gekozen. De leden werden gekozen door (maar niet per se uit) de standen naar evenredigheid van hun getal. De vertegenwoordiging in standen verdween in 1848 uit de grondwet, en daadwerkelijk met de invoering van de Provinciewet in 1850.</p>\n<p><b>Aanvangs- en einddatum in het Repertorium</b>:<br/>\nDe data zijn genomen uit de traktementsregisters van Binnenlandse Zaken.</p>\n<p><b>Bronnen</b>:<br/>\nNA, Binnenlandse Zaken, traktementsregisters (2.04.25) nrs. 1-12, 73-92 e.v. (benoemings- en ontslagdata).</p>\n<p><b>Naamlijsten</b>:<br/>\n-Heel, Caspar van, <i>400 jaar gedeputeerde staten van Overijssel (Zwolle 1993)</i> 72-74 en 82-83 [gedeputeerden en griffiers].<br/>\n\n-Heel, Caspar van, 'Lijst van provinciale bestuurders, 1813-heden', in <i>Overijssels Contactbericht</i> 10, nr. 1 (maart 1984) 34-42 [gedeputeerden en griffiers].<br/>\n\n-Wigger, J.H., en J. Folkerts, <i>Inventaris van de archieven van het provinciaal bestuur van Overijssel 1813-1920/1948</i> (2 dln.; Zwolle 1994) lxii-lxx [gedeputeerden en griffiers].</p>\n<p><b>Literatuur</b>:<br/>\n-Heel, Caspar van, <i>400 jaar gedeputeerde staten van Overijssel</i> (Zwolle 1993).<br/>\n\n-Wigger, J.H., en J. Folkerts, Inventaris van de archieven van het provinciaal bestuur van Overijssel 1813-1920/1948 (2 dln.; Zwolle 1994).<br/>\n\n-Zie ook bij Provinciale Staten van Overijssel.</p>\n<p><b>Opmerking</b>:<br/>\nWie geen lid der Provinciale Staten meer was, was ook geen lid van Gedeputeerde Staten meer.</p>"},

In [106]:
df_toelichting = pd.DataFrame.from_records(clgs).T

In [107]:
df_toelichting

,dbnaam,filename,toelichting,naam
Admiraliteit in Friesland (1596-1795),Admiraliteit in Friesland (1596-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
Admiraliteit in Zeeland (1584-1795),Admiraliteit in Zeeland (1584-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
Admiraliteit in het Noorderkwartier (1589-1795),Admiraliteit in het Noorderkwartier (1589-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
Admiraliteit op de Maze (1586-1795),Admiraliteit op de Maze (1586-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
Admiraliteit te Amsterdam (1586-1795),Admiraliteit te Amsterdam (1586-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
...,...,...,...,...
WIC ter Kamer Amsterdam,WIC ter Kamer Amsterdam,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-amste...",NaN
WIC ter Kamer Stad en Lande,WIC ter Kamer Stad en Lande,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-groni...",NaN
WIC ter Kamer Zeeland,WIC ter Kamer Zeeland,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-zeela...",NaN
WIC ter Kamer op de Maze,WIC ter Kamer op de Maze,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-rotte...",NaN
WIC ter Kamer van het Noorderkwartier,WIC ter Kamer van het Noorderkwartier,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-noord...",NaN

In [108]:
df_toelichting.to_json(f'{basedir}/toelichtingen_concordantie_20241211.json', orient='records')

In [109]:
mcolleges = colleges.merge(df_toelichting, left_on='college',right_on='dbnaam', how='left')

In [110]:
outcols = ['college_id', 'college', 'old_idcollege', 'toelichting']

In [111]:
mcolleges[mcolleges.toelichting.notna()]

,Unnamed: 0,college_id,college,old_idcollege,dbnaam,filename,toelichting,naam
4,4,4,Admiraliteit in Friesland (1596-1795),"['divperioden_6', 'republiek_34', 'republiek_f...",Admiraliteit in Friesland (1596-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
5,5,5,Admiraliteit in Zeeland (1584-1795),['republiek_32'],Admiraliteit in Zeeland (1584-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
6,6,6,Admiraliteit in het Noorderkwartier (1589-1795),"['divperioden_48', 'republiek_33', 'republiek_...",Admiraliteit in het Noorderkwartier (1589-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
7,7,7,Admiraliteit op de Maze (1586-1795),"['divperioden_45', 'republiek_30', 'republiek_...",Admiraliteit op de Maze (1586-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
8,8,8,Admiraliteit te Amsterdam (1586-1795),"['divperioden_7', 'republiek_31', 'republiek_f...",Admiraliteit te Amsterdam (1586-1795),./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-admiralit...",NaN
...,...,...,...,...,...,...,...,...
526,526,526,WIC ter Kamer Amsterdam,['republiek_41'],WIC ter Kamer Amsterdam,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-amste...",NaN
527,527,527,WIC ter Kamer Stad en Lande,['republiek_45'],WIC ter Kamer Stad en Lande,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-groni...",NaN
528,528,528,WIC ter Kamer Zeeland,['republiek_42'],WIC ter Kamer Zeeland,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-zeela...",NaN
529,529,529,WIC ter Kamer op de Maze,['republiek_43'],WIC ter Kamer op de Maze,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-rotte...",NaN
530,530,530,WIC ter Kamer van het Noorderkwartier,['republiek_44'],WIC ter Kamer van het Noorderkwartier,./institutionele_toelichtingen//IT_Generalitei...,"b'<h1 id=""institutionele-toelichting-wic-noord...",NaN

In [112]:
mcolleges[outcols]

,college_id,college,old_idcollege,toelichting
0,0,Administrateurs de la Loterie Impériale de France,['batfra_269'],NaN
1,1,Administrateurs der Posterijen,['batfra_250'],NaN
2,2,Administration Générale des Poudres et Salpêtres,['batfra_173'],NaN
3,3,Administration des Monnaies,['batfra_203'],NaN
4,4,Admiraliteit in Friesland (1596-1795),"['divperioden_6', 'republiek_34', 'republiek_f...","b'<h1 id=""institutionele-toelichting-admiralit..."
...,...,...,...,...
531,531,Wetgevend Lichaam van het Bataafse Gemenebest ...,['batfra_80'],NaN
532,532,"Wetgevend Lichaam, Vergadering van Hun Hoog Mo...",['batfra_243'],NaN
533,533,"Wetgevend Lichaam, Vergadering van Hun Hoog Mo...",['batfra_78'],NaN
534,534,Zeeraad,['batfra_202'],NaN
535,535,schout van Rotterban,['me_103'],NaN

In [113]:
# colleges['filename'] = colleges.college.map(flnms)

In [114]:
# colleges

In [ ]:
# colleges['toelichting'] = colleges.college.map(clgs)

In [115]:
# clgs

In [ ]:
# toelichting_conc

,Bestandsnaam Word,Naam in Database,ID in Database,toel_id
0,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19
1,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21
2,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20
3,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163
4,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162
5,IT_GelderlandGedStaZutphen.docx,Gedeputeerde Staten van het Graafschap Zutphen...,164,republiek_164
6,IT_GelderlandHof.docx,Hof van Gelre en Zutphen (1588-1795),142,republiek_142
7,IT_GelderlandRekProv.docx,Provinciale Rekenkamer van Gelderland (1581-1795),161,republiek_161
8,IT_GeneraliteitAdAms.docx,Admiraliteit te Amsterdam (1586-1795),31,republiek_31
9,IT_GeneraliteitAdFries.docx,Admiraliteit in Friesland (1596-1795),34,republiek_34
10,IT_GeneraliteitAdMaze.docx,Admiraliteit op de Maze (1586-1795),30,republiek_30
11,IT_GeneraliteitAdNoord.docx,Admiraliteit in het Noorderkwartier (1589-1795),33,republiek_33
12,IT_GeneraliteitAdSup.docx,College van Superintendentie der Admiralteit (...,130,republiek_130
13,IT_GeneraliteitAdZee.docx,Admiraliteit in Zeeland (1584-1795),32,republiek_32
14,IT_GeneraliteitRaBra.docx,Raad van Brabant (1591-1795),46,republiek_46
15,IT_GeneraliteitRaSta.docx,Raad van State (1588-1795),28,republiek_28
16,IT_GeneraliteitRaVla.docx,Raad van Vlaanderen (1599-1795),47,republiek_47
17,IT_GeneraliteitRek.docx,Generaliteitsrekenkamer (1608-1799),29,republiek_29
18,IT_GeneraliteitStaGe.docx,Staten-Generaal der Verenigde Nederlanden (157...,27,republiek_27
19,IT_GeneraliteitVocAms.docx,VOC ter Kamer Amsterdam,35,republiek_35
20,IT_GeneraliteitVocDelft.docx,VOC ter Kamer Delft,37,republiek_37
21,IT_GeneraliteitVocEnk.docx,VOC ter Kamer Enkhuizen,40,republiek_40
22,IT_GeneraliteitVocHoorn.docx,VOC ter Kamer Hoorn,39,republiek_39
23,IT_GeneraliteitVocMid.docx,VOC ter Kamer Zeeland,36,republiek_36
24,IT_GeneraliteitVocRot.docx,VOC ter Kamer Rotterdam,38,republiek_38
25,IT_GeneraliteitWicAms.docx,WIC ter Kamer Amsterdam,41,republiek_41
26,IT_GeneraliteitWicGron.docx,WIC ter Kamer Stad en Lande,45,republiek_45
27,IT_GeneraliteitWicMid.docx,WIC ter Kamer Zeeland,42,republiek_42
28,IT_GeneraliteitWicNoord.docx,WIC ter Kamer van het Noorderkwartier,44,republiek_44
29,IT_GeneraliteitWicRot.docx,WIC ter Kamer op de Maze,43,republiek_43
30,IT_GroningenGedSta.docx,Gedeputeerde Staten van Groningen (1595-1795),139,republiek_139
31,IT_GroningenHof.docx,"Hoofdmannenkamer, vanaf 1749 Hoge Justitiekame...",140,republiek_140
32,IT_GroningenRekProv.docx,Provinciale Rekenkamer van Groningen (1596-1795),138,republiek_138
33,IT_HollandGecRaNoord.docx,Gecommitteerde Raden van Holland in het Noorde...,8,republiek_8
34,IT_HollandGecRaZuid.docx,Gecommitteerde Raden van Holland in het Zuider...,7,republiek_7
35,IT_HollandGrafRek.docx,Grafelijkheidsrekenkamer van Holland (1588-1728),137,republiek_137
36,IT_HollandHof.docx,Hof van Holland en Zeeland (1572-1795),13,republiek_13
37,IT_HollandHogeRaad.docx,Hoge Raad van Holland en Zeeland (1582-1795),12,republiek_12
38,IT_HollandRekNoord.docx,Rekenkamer ter Auditie van Holland in het Noor...,10,republiek_10
39,IT_HollandRekProv.docx,Provinciale Rekenkamer van Holland (1752-1795),11,republiek_11
40,IT_HollandRekZuid.docx,Rekenkamer ter Auditie van Holland in het Zuid...,9,republiek_9
41,IT_OverijsselGedSta.docx,Gedeputeerde Staten van Overijssel (1591-1795),22,republiek_22
42,IT_UtrechtGedSta.docx,Gedeputeerde Staten van Utrecht (1577-1795),145,republiek_145
43,IT_UtrechtHof.docx,Hof van Utrecht (1588-1795),143,republiek_143
44,IT_UtrechtRekProv.docx,Kamer ter Finantie van Utrecht (1663-1795),144,republiek_144
45,IT_ZeelandGecRa.docx,Gecommitteerde Raden van Zeeland (1578-1795),14,republiek_14
46,IT_ZeelandRekProv.docx,Provinciale Rekenkamer van Zeeland (1596-1795),15,republiek_15

In [ ]:
# toelichting_conc['knm'] = toelichting_conc['Bestandsnaam Word'].apply(lambda x: x.split('.')[0])

In [ ]:
# toelichting_conc

,Bestandsnaam Word,Naam in Database,ID in Database,toel_id,knm
0,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19,IT_FrieslandGedSta
1,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21,IT_FrieslandHof
2,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20,IT_FrieslandRekProv
3,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163,IT_GelderlandGedStaNijmegen
4,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162,IT_GelderlandGedStaVeluwe
5,IT_GelderlandGedStaZutphen.docx,Gedeputeerde Staten van het Graafschap Zutphen...,164,republiek_164,IT_GelderlandGedStaZutphen
6,IT_GelderlandHof.docx,Hof van Gelre en Zutphen (1588-1795),142,republiek_142,IT_GelderlandHof
7,IT_GelderlandRekProv.docx,Provinciale Rekenkamer van Gelderland (1581-1795),161,republiek_161,IT_GelderlandRekProv
8,IT_GeneraliteitAdAms.docx,Admiraliteit te Amsterdam (1586-1795),31,republiek_31,IT_GeneraliteitAdAms
9,IT_GeneraliteitAdFries.docx,Admiraliteit in Friesland (1596-1795),34,republiek_34,IT_GeneraliteitAdFries
10,IT_GeneraliteitAdMaze.docx,Admiraliteit op de Maze (1586-1795),30,republiek_30,IT_GeneraliteitAdMaze
11,IT_GeneraliteitAdNoord.docx,Admiraliteit in het Noorderkwartier (1589-1795),33,republiek_33,IT_GeneraliteitAdNoord
12,IT_GeneraliteitAdSup.docx,College van Superintendentie der Admiralteit (...,130,republiek_130,IT_GeneraliteitAdSup
13,IT_GeneraliteitAdZee.docx,Admiraliteit in Zeeland (1584-1795),32,republiek_32,IT_GeneraliteitAdZee
14,IT_GeneraliteitRaBra.docx,Raad van Brabant (1591-1795),46,republiek_46,IT_GeneraliteitRaBra
15,IT_GeneraliteitRaSta.docx,Raad van State (1588-1795),28,republiek_28,IT_GeneraliteitRaSta
16,IT_GeneraliteitRaVla.docx,Raad van Vlaanderen (1599-1795),47,republiek_47,IT_GeneraliteitRaVla
17,IT_GeneraliteitRek.docx,Generaliteitsrekenkamer (1608-1799),29,republiek_29,IT_GeneraliteitRek
18,IT_GeneraliteitStaGe.docx,Staten-Generaal der Verenigde Nederlanden (157...,27,republiek_27,IT_GeneraliteitStaGe
19,IT_GeneraliteitVocAms.docx,VOC ter Kamer Amsterdam,35,republiek_35,IT_GeneraliteitVocAms
20,IT_GeneraliteitVocDelft.docx,VOC ter Kamer Delft,37,republiek_37,IT_GeneraliteitVocDelft
21,IT_GeneraliteitVocEnk.docx,VOC ter Kamer Enkhuizen,40,republiek_40,IT_GeneraliteitVocEnk
22,IT_GeneraliteitVocHoorn.docx,VOC ter Kamer Hoorn,39,republiek_39,IT_GeneraliteitVocHoorn
23,IT_GeneraliteitVocMid.docx,VOC ter Kamer Zeeland,36,republiek_36,IT_GeneraliteitVocMid
24,IT_GeneraliteitVocRot.docx,VOC ter Kamer Rotterdam,38,republiek_38,IT_GeneraliteitVocRot
25,IT_GeneraliteitWicAms.docx,WIC ter Kamer Amsterdam,41,republiek_41,IT_GeneraliteitWicAms
26,IT_GeneraliteitWicGron.docx,WIC ter Kamer Stad en Lande,45,republiek_45,IT_GeneraliteitWicGron
27,IT_GeneraliteitWicMid.docx,WIC ter Kamer Zeeland,42,republiek_42,IT_GeneraliteitWicMid
28,IT_GeneraliteitWicNoord.docx,WIC ter Kamer van het Noorderkwartier,44,republiek_44,IT_GeneraliteitWicNoord
29,IT_GeneraliteitWicRot.docx,WIC ter Kamer op de Maze,43,republiek_43,IT_GeneraliteitWicRot
30,IT_GroningenGedSta.docx,Gedeputeerde Staten van Groningen (1595-1795),139,republiek_139,IT_GroningenGedSta
31,IT_GroningenHof.docx,"Hoofdmannenkamer, vanaf 1749 Hoge Justitiekame...",140,republiek_140,IT_GroningenHof
32,IT_GroningenRekProv.docx,Provinciale Rekenkamer van Groningen (1596-1795),138,republiek_138,IT_GroningenRekProv
33,IT_HollandGecRaNoord.docx,Gecommitteerde Raden van Holland in het Noorde...,8,republiek_8,IT_HollandGecRaNoord
34,IT_HollandGecRaZuid.docx,Gecommitteerde Raden van Holland in het Zuider...,7,republiek_7,IT_HollandGecRaZuid
35,IT_HollandGrafRek.docx,Grafelijkheidsrekenkamer van Holland (1588-1728),137,republiek_137,IT_HollandGrafRek
36,IT_HollandHof.docx,Hof van Holland en Zeeland (1572-1795),13,republiek_13,IT_HollandHof
37,IT_HollandHogeRaad.docx,Hoge Raad van Holland en Zeeland (1582-1795),12,republiek_12,IT_HollandHogeRaad
38,IT_HollandRekNoord.docx,Rekenkamer ter Auditie van Holland in het Noor...,10,republiek_10,IT_HollandRekNoord
39,IT_HollandRekProv.docx,Provinciale Rekenkamer van Holland (1752-1795),11,republiek_11,IT_HollandRekProv
40,IT_HollandRekZuid.docx,Rekenkamer ter Auditie van Holland in het Zuid...,9,republiek_9,IT_HollandRekZuid
41,IT_OverijsselGedSta.docx,Gedeputeerde Staten van Overijssel (1591-1795),22,republiek_22,IT_OverijsselGedSta
42,IT_UtrechtGedSta.docx,Gedeputeerde Staten van Utrecht (1577-1795),145,republiek_145,IT_UtrechtGedSta
43,IT_UtrechtHof.docx,Hof van Utrecht (1588-1795),143,republiek_143,IT_UtrechtHof
44,IT_UtrechtRekProv.docx,Kamer ter Finantie van Utrecht (1663-1795),144,republiek_144,IT_UtrechtRekProv
45,IT_ZeelandGecRa.docx,Gecommitteerde Raden van Zeeland (1578-1795),14,republiek_14,IT_ZeelandGecRa
46,IT_ZeelandRekProv.docx,Provinciale Rekenkamer van Zeeland (1596-1795),15,republiek_15,IT_ZeelandRekProv

In [ ]:
# colleges.merge(toelichting_conc, left_on='college_id',right_on='ID in Database')

,Unnamed: 0,college_id,college,old_idcollege,toelichting,filename,Bestandsnaam Word,Naam in Database,ID in Database,toel_id
0,7,7,Admiraliteit op de Maze (1586-1795),"['divperioden_45', 'republiek_30', 'republiek_...",NaN,./institutionele_toelichtingen/Admiraliteit op...,IT_HollandGecRaZuid.docx,Gecommitteerde Raden van Holland in het Zuider...,7,republiek_7
1,8,8,Admiraliteit te Amsterdam (1586-1795),"['divperioden_7', 'republiek_31', 'republiek_f...",NaN,./institutionele_toelichtingen/Admiraliteit te...,IT_HollandGecRaNoord.docx,Gecommitteerde Raden van Holland in het Noorde...,8,republiek_8
2,9,9,Agentschap van Buitenlandse Betrekkingen,['batfra_133'],NaN,NaN,IT_HollandRekZuid.docx,Rekenkamer ter Auditie van Holland in het Zuid...,9,republiek_9
3,10,10,Agentschap van Financiën,['batfra_127'],NaN,NaN,IT_HollandRekNoord.docx,Rekenkamer ter Auditie van Holland in het Noor...,10,republiek_10
4,11,11,Agentschap van Inwendige Politie en Waterstaat,['batfra_116'],NaN,NaN,IT_HollandRekProv.docx,Provinciale Rekenkamer van Holland (1752-1795),11,republiek_11
5,12,12,Agentschap van Justitie,['batfra_112'],NaN,NaN,IT_HollandHogeRaad.docx,Hoge Raad van Holland en Zeeland (1582-1795),12,republiek_12
6,13,13,Agentschap van Marine,['batfra_148'],NaN,NaN,IT_HollandHof.docx,Hof van Holland en Zeeland (1572-1795),13,republiek_13
7,14,14,Agentschap van Nationale Oeconomie,['batfra_124'],NaN,NaN,IT_ZeelandGecRa.docx,Gecommitteerde Raden van Zeeland (1578-1795),14,republiek_14
8,15,15,Agentschap van Nationale Opvoeding,['batfra_123'],NaN,NaN,IT_ZeelandRekProv.docx,Provinciale Rekenkamer van Zeeland (1596-1795),15,republiek_15
9,19,19,Algemene Administratie van de Waterstaat,['batfra_248'],NaN,NaN,IT_FrieslandGedSta.docx,Gedeputeerde Staten van Friesland (1577-1795),19,republiek_19
10,20,20,Algemene Directie der Posterijen (1813-1819),['negentiende_eeuw_31'],NaN,NaN,IT_FrieslandRekProv.docx,Provinciale Rekenkamer van Friesland (1582-1795),20,republiek_20
11,21,21,Algemene Rekenkamer (1813-1861),['negentiende_eeuw_19'],"b""<h3>Institutionele toelichting Algemene Reke...",./institutionele_toelichtingen/Algemene Rekenk...,IT_FrieslandHof.docx,Hof van Friesland (1515-1795),21,republiek_21
12,22,22,Algemene Secretarie van Staat,['batfra_229'],NaN,NaN,IT_OverijsselGedSta.docx,Gedeputeerde Staten van Overijssel (1591-1795),22,republiek_22
13,27,27,Betaalmeester van de Armée (van Oorlog),['batfra_244'],NaN,NaN,IT_GeneraliteitStaGe.docx,Staten-Generaal der Verenigde Nederlanden (157...,27,republiek_27
14,28,28,Bureau Statistique de l' Empire,['batfra_49'],NaN,NaN,IT_GeneraliteitRaSta.docx,Raad van State (1588-1795),28,republiek_28
15,29,29,College van Administratie van de Domeinen van ...,['batfra_444'],NaN,NaN,IT_GeneraliteitRek.docx,Generaliteitsrekenkamer (1608-1799),29,republiek_29
16,30,30,College van Geëligeerden van Utrecht,['republiek_96'],NaN,NaN,IT_GeneraliteitAdMaze.docx,Admiraliteit op de Maze (1586-1795),30,republiek_30
17,31,31,College van Superintendentie der Admiraliteit ...,['republiek_friezen_8'],NaN,NaN,IT_GeneraliteitAdAms.docx,Admiraliteit te Amsterdam (1586-1795),31,republiek_31
18,32,32,College van Superintendentie der Admiralteit (...,"['divperioden_8', 'republiek_130']",NaN,./institutionele_toelichtingen/College van Sup...,IT_GeneraliteitAdZee.docx,Admiraliteit in Zeeland (1584-1795),32,republiek_32
19,33,33,Comité tot de Algemene Zaken van het Bondgenoo...,['batfra_136'],NaN,NaN,IT_GeneraliteitAdNoord.docx,Admiraliteit in het Noorderkwartier (1589-1795),33,republiek_33
20,34,34,Comité tot de Oost-Indische Handel en Bezittingen,['batfra_151'],NaN,NaN,IT_GeneraliteitAdFries.docx,Admiraliteit in Friesland (1596-1795),34,republiek_34
21,35,35,Comité tot de Zaken van de Koloniën en Bezitti...,['batfra_153'],NaN,NaN,IT_GeneraliteitVocAms.docx,VOC ter Kamer Amsterdam,35,republiek_35
22,36,36,Comité tot de Zaken van de Marine,['batfra_147'],NaN,NaN,IT_GeneraliteitVocMid.docx,VOC ter Kamer Zeeland,36,republiek_36
23,37,37,"Comité van Algemeen Welzijn, Waakzaamheid en V...",['batfra_381'],NaN,NaN,IT_GeneraliteitVocDelft.docx,VOC ter Kamer Delft,37,republiek_37
24,38,38,Comité-Centraal van de Waterstaat,['batfra_120'],NaN,NaN,IT_GeneraliteitVocRot.docx,VOC ter Kamer Rotterdam,38,republiek_38
25,39,39,Commissariaat der Franse troepen in soldij der...,['batfra_142'],NaN,NaN,IT_GeneraliteitVocHoorn.docx,VOC ter Kamer Hoorn,39,republiek_39
26,40,40,Commissaris tot de Gecedeerde Landen aan de Ba...,['batfra_226'],NaN,NaN,IT_GeneraliteitVocEnk.docx,VOC ter Kamer Enkhuizen,40,republiek_40
27,41,41,Commissaris-Liquidateur van de Pretentiën van ...,['batfra_143'],NaN,NaN,IT_GeneraliteitWicAms.docx,WIC ter Kamer Amsterdam,41,republiek_41
28,42,42,Commissarissen der Bataafse Posterijen,['batfra_223'],NaN,NaN,IT_GeneraliteitWicMid.docx,WIC ter Kamer Zeeland,42,republiek_42
29,43,43,Commissarissen der Nationale Beleenbank,['batfra_263'],NaN,NaN,IT_GeneraliteitWicRot.docx,WIC ter Kamer op de Maze,43,republiek_43
30,44,44,Commissarissen van de Generale Beleenbank,['batfra_455'],NaN,NaN,IT_GeneraliteitWicNoord.docx,WIC ter Kamer van het Noorderkwartier,44,republiek_44
31,45,45,Commissarissen van de Nationale Rekening,['batfra_198'],NaN,NaN,IT_GeneraliteitWicGron.docx,WIC ter Kamer Stad en Lande,45,republiek_45
32,46,46,Commissarissen van het Uitvoerend Bewind bij d...,['batfra_449'],NaN,NaN,IT_GeneraliteitRaBra.docx,Raad van Brabant (1591-1795),46,republiek_46
33,47,47,Commissarissen van het Uitvoerend Bewind bij d...,['batfra_457'],NaN,NaN,IT_GeneraliteitRaVla.docx,Raad van Vlaanderen (1599-1795),47,republiek_47
34,130,130,Directie van de Landelijke Telegrafische Besei...,['batfra_146'],NaN,NaN,IT_GeneraliteitAdSup.docx,College van Superintendentie der Admiralteit (...,130,republiek_130
35,137,137,Direction-Générale de l' Imprimerie et de la L...,['batfra_89'],NaN,NaN,IT_HollandGrafRek.docx,Grafelijkheidsrekenkamer van Holland (1588-1728),137,republiek_137
36,138,138,Direction-Générale de la Caisse d' Amortissement,['batfra_177'],NaN,NaN,IT_GroningenRekProv.docx,Provinciale Rekenkamer van Groningen (1596-1795),138,republiek_138
37,139,139,Direction-Générale de la Comptabilité des Comm...,['batfra_175'],NaN,NaN,IT_GroningenGedSta.docx,Gedeputeerde Staten van Groningen (1595-1795),139,republiek_139
38,140,140,Direction-Générale de la Police en Hollande,['batfra_53'],NaN,NaN,IT_GroningenHof.docx,"Hoofdmannenkamer, vanaf 1749 Hoge Justitiekame...",140,republiek_140
39,142,142,Direction-Générale des Droits Réunis,['batfra_178'],NaN,NaN,IT_GelderlandHof.docx,Hof van Gelre en Zutphen (1588-1795),142,republiek_142
40,143,143,Direction-Générale des Forêts,['batfra_45'],NaN,NaN,IT_UtrechtHof.docx,Hof van Utrecht (1588-1795),143,republiek_143
41,144,144,Direction-Générale des Mines,['batfra_46'],NaN,NaN,IT_UtrechtRekProv.docx,Kamer ter Finantie van Utrecht (1663-1795),144,republiek_144
42,145,145,"Direction-Générale des Ponts et Chaussées, Nav...",['batfra_44'],NaN,NaN,IT_UtrechtGedSta.docx,Gedeputeerde Staten van Utrecht (1577-1795),145,republiek_145
43,161,161,Eerste Kamer der Staten-Generaal (1815-1861),['negentiende_eeuw_1'],"b""<h3>Institutionele toelichting Eerste Kamer ...",./institutionele_toelichtingen/Eerste Kamer de...,IT_GelderlandRekProv.docx,Provinciale Rekenkamer van Gelderland (1581-1795),161,republiek_161
44,162,162,"Eerste Nationale Vergadering, representerende ...",['batfra_98'],NaN,NaN,IT_GelderlandGedStaVeluwe.docx,Gedeputeerde Staten van het Kwartier Veluwe (1...,162,republiek_162
45,163,163,Essayeur-Generaal van de Munt,['batfra_74'],NaN,NaN,IT_GelderlandGedStaNijmegen.docx,Gedeputeerde Staten van het Kwartier Nijmegen ...,163,republiek_163
46,164,164,Financiële Commissie van Holland (1799-1802),['batfra_392'],NaN,NaN,IT_GelderlandGedStaZutphen.docx,Gedeputeerde Staten van het Graafschap Zutphen...,164,republiek_164

In [ ]:
# colleges[colleges.toelichting.notna()]

,Unnamed: 0,college_id,college,old_idcollege,toelichting,filename
17,17,17,Algemeen Bestuur (1813),['negentiende_eeuw_94'],"b""<h3>Institutionele toelichting Algemeen Best...",./institutionele_toelichtingen/Algemeen Bestuu...
21,21,21,Algemene Rekenkamer (1813-1861),['negentiende_eeuw_19'],"b""<h3>Institutionele toelichting Algemene Reke...",./institutionele_toelichtingen/Algemene Rekenk...
69,69,69,Criminele Rechtbank (1838-1841),['negentiende_eeuw_50'],"b""<h3>Institutionele toelichting Criminele Rec...",./institutionele_toelichtingen/Criminele Recht...
70,70,70,Departement van Binnenlandse Zaken (1813-1861),['negentiende_eeuw_9'],"b""<h3>Institutionele toelichting departement v...",./institutionele_toelichtingen/Departement van...
71,71,71,"Departement van Binnenlandse Zaken, Onderwijs ...",['negentiende_eeuw_21'],b'<h3>Institutionele toelichting departement v...,./institutionele_toelichtingen/Departement van...
...,...,...,...,...,...,...
453,453,453,Staatssecretarie (1813-1840),['negentiende_eeuw_10'],"b""<h3>Institutionele toelichting Staatssecreta...",./institutionele_toelichtingen/Staatssecretari...
465,465,465,Staten-Generaal,['me_86'],"b""<h3>Institutionele toelichting Staten-Genera...",NaN
466,466,466,Staten-Generaal (1814-1815),['negentiende_eeuw_3'],"b""<h3>Institutionele toelichting Staten-Genera...",./institutionele_toelichtingen/Staten-Generaal...
472,472,472,Tweede Kamer der Staten-Generaal (1815-1861),['negentiende_eeuw_4'],"b""<h3>Institutionele toelichting Tweede Kamer ...",./institutionele_toelichtingen/Tweede Kamer de...
484,484,484,Vergadering van Notabelen (1814),['negentiende_eeuw_2'],"b""<h3>Institutionele toelichting Vergadering v...",./institutionele_toelichtingen/Vergadering van...

## check database

In [ ]:
rege

NameError: name 'regent' is not defined